### ISSUE TITLE
Battle of Briatain Scenario on Channel map is broken

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1010]
**Describe the bug**
BoB campaign cannot be generated on Channel map. Error below is produced. Dunkirk scenario works fine on Channel map.

Traceback (most recent call last):
  File "gen\flights\ai_flight_planner.py", line 558, in critical_missions
  File "gen\flights\ai_flight_planner.py", line 474, in farthest_friendly_control_point
StopIteration

The above exception was the direct cause of the following exception:Traceback (most recent call last):
  File "qt_ui\windows\newgame\QNewGameWizard.py", line 117, in accept
  File "game\theater\start_generator.py", line 98, in generate
  File "game\game.py", line 135, in init
  File "gen\flights\ai_flight_planner.py", line 717, in plan_missions
  File "gen\flights\ai_flight_planner.py", line 600, in propose_missions
RuntimeError: generator raised StopIteration(edited)
[07:34]

**Comment by gorgefodder** [comment]
Is there any clue as to what causes this, I'm creating a custom campaign myself and i'm failing at the exact same step.

**Comment by DanAlbert** [comment]
Works for me now.
