### ISSUE TITLE
ASAP option generates error

### ISSUE THREAD

**Issue by rivvern** [dcs-liberation/dcs_liberation#1015]
DCS 2.7
dcs_liberation 2.5.0

When creating a flight and checking the ASAP option. It generates this error:

```
Traceback (most recent call last):
  File "qt_ui\windows\mission\QPackageDialog.py", line 157, in set_asap
  File "qt_ui\models.py", line 177, in set_asap
  File "qt_ui\models.py", line 181, in update_tot
  File "gen\ato.py", line 139, in set_tot_asap
  File "gen\flights\traveltime.py", line 75, in earliest_tot
ValueError: max() arg is an empty sequence
```

**Comment by rivvern** [comment]
Maybe i got this error because i had no flights added to the package.
