### ISSUE TITLE
Can't finish mission pushing accept results button

### ISSUE THREAD

**Issue by alrik11es** [dcs-liberation/dcs_liberation#1051]
**Describe the bug**
Once finishing the mission in the waiting for mission completion screen pushing ACCEPT RESULTS generates an error.

**To Reproduce**
1. Play a mission
2. Kill units not tracked by DCS Liberation
3. Quit mission
4. Push accept results
5. See error

**Expected behavior**
It should ignore destroyed not found units in the results.

**Additional information**
![image](https://user-images.githubusercontent.com/249844/116778167-a5d21600-aa70-11eb-91de-e57ddc4b1464.png)

```
2021-05-01 11:25:42,672 :: INFO :: Finishing event AirWar
2021-05-01 11:25:42,672 :: INFO :: Committing mission results
2021-05-01 11:25:42,672 :: ERROR :: Found killed <class 'dcs.planes.F_15E'> from Kobuleti but that airbase has none available.
2021-05-01 11:25:42,672 :: ERROR :: Found killed <class 'dcs.planes.F_15E'> from Kobuleti but that airbase has none available.
2021-05-01 11:25:42,672 :: ERROR :: Found killed <class 'dcs.planes.F_15E'> from Kobuleti but that airbase has none available.
2021-05-01 11:25:42,672 :: ERROR :: Found killed <class 'dcs.planes.F_15E'> from Kobuleti but that airbase has none available.
2021-05-01 11:25:42,672 :: ERROR :: Found killed <class 'dcs.planes.FA_18C_hornet'> from CVN-75 Harry S. Truman but that airbase has none available.
2021-05-01 11:25:42,672 :: ERROR :: Found killed <class 'dcs.planes.FA_18C_hornet'> from CVN-75 Harry S. Truman but that airbase has none available.
2021-05-01 11:25:42,672 :: ERROR :: Found killed <class 'dcs.planes.FA_18C_hornet'> from CVN-75 Harry S. Truman but that airbase has none available.
2021-05-01 11:25:42,672 :: ERROR :: Found killed <class 'dcs.planes.FA_18C_hornet'> from CVN-75 Harry S. Truman but that airbase has none available.
2021-05-01 11:25:42,672 :: ERROR :: Found killed <class 'dcs.planes.FA_18C_hornet'> from CVN-75 Harry S. Truman but that airbase has none available.
2021-05-01 11:25:42,672 :: ERROR :: Found killed <class 'dcs.planes.FA_18C_hornet'> from CVN-75 Harry S. Truman but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.planes.MiG_29S'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.planes.Su_27'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.planes.Su_27'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.planes.Su_24M'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.planes.Su_24M'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.planes.MiG_29S'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.planes.MiG_29S'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.planes.MiG_29S'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: INFO :: <class 'dcs.vehicles.Armor.IFV_M2A2_Bradley'> destroyed from Kobuleti
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.IFV_BMP_1'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.APC_BTR_80'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.vehicles.Artillery.MLRS_BM_27_Uragan_220mm'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.IFV_BMP_2'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,673 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.IFV_BMP_1'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,674 :: ERROR :: Found killed <class 'dcs.vehicles.Artillery.SPH_2S19_Msta_152mm'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,674 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.APC_BTR_80'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,674 :: ERROR :: Found killed <class 'dcs.vehicles.Artillery.MLRS_BM_27_Uragan_220mm'> from Sukhumi-Babushara but that airbase has none available.
2021-05-01 11:25:42,674 :: ERROR :: Found killed <class 'dcs.vehicles.Artillery.SPH_2S19_Msta_152mm'> from Sukhumi-Babushara but that airbase has none available.
Traceback (most recent call last):
  File "C:\things\dcs_liberation\qt_ui\windows\QWaitingForMissionResultWindow.py", line 209, in process_debriefing
    self.game.finish_event(event=self.gameEvent, debriefing=self.debriefing)
  File "C:\things\dcs_liberation\game\game.py", line 263, in finish_event
    event.commit(debriefing)
  File "C:\things\dcs_liberation\game\event\event.py", line 255, in commit
    self.commit_ground_object_losses(debriefing)
  File "C:\things\dcs_liberation\game\event\event.py", line 205, in commit_ground_object_losses
    loss.group.units.remove(loss.unit)
ValueError: list.remove(x): x not in list
```

**Version information (please complete the following information):**
 - DCS Liberation 3.0-preview (develop branch)

**Comment by gatorman22** [comment]
Getting the same results in 3.0-preview Build #5190 and #5192

**Comment by DanAlbert** [comment]
`x not in list` here is never the real error. There was an error earlier in the log that corrupted the game, and this is the result of trying to push accept again. We can't do anything with the data given. We need the save from before the problem and the state.json. If someone can provide that we'll reopen, but nothing we _can_ do here.
