### ISSUE TITLE
New Squadrons implementation won't allow custom flights

### ISSUE THREAD

**Issue by KeeseAF** [dcs-liberation/dcs_liberation#1139]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
After the first turn went off without a hitch, i am trying to make another turn full of flights. However, whenever i go to create a custom flight, nothing happens. I thought it was due to no available pilots, but i deleted all the flights so they *should* be all available right?

**To Reproduce**
1. Delete pre programmed flights
2. Make custom package
3. click "create" flight in a package
4.  nothing happens after this

**Expected behavior**
The flights to generate

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

C:/Users/Keese/Saved Games/DCS.openbeta/autosave.liberation
2021-05-27 12:47:18,735 :: INFO :: Loading last saved game : C:/Users/Keese/Saved Games/DCS.openbeta/autosave.liberation
2021-05-27 12:47:18,857 :: INFO :: Reading plugins list from resources\plugins\plugins.json
2021-05-27 12:47:18,857 :: INFO :: Loading plugin base from resources\plugins\base\plugin.json
2021-05-27 12:47:18,857 :: INFO :: Loading plugin jtacautolase from resources\plugins\jtacautolase\plugin.json
2021-05-27 12:47:18,858 :: INFO :: Loading plugin skynetiads from resources\plugins\skynetiads\plugin.json
2021-05-27 12:47:18,858 :: INFO :: Loading plugin ewrs from resources\plugins\ewrs\plugin.json
2021-05-27 12:47:18,858 :: INFO :: Loading plugin herculescargo from resources\plugins\herculescargo\plugin.json
2021-05-27 12:47:18,859 :: INFO :: Loading plugin splashdamage from resources\plugins\splashdamage\plugin.json
2021-05-27 12:47:18,859 :: INFO :: Loading plugin lotatc from resources\plugins\lotatc\plugin.json
2021-05-27 12:47:18,866 :: INFO :: Loaded faction : resources\factions\allies_1940.json
2021-05-27 12:47:18,866 :: INFO :: Loaded faction : resources\factions\allies_1944.json
2021-05-27 12:47:18,867 :: INFO :: Loaded faction : resources\factions\allies_1944_free.json
2021-05-27 12:47:18,867 :: INFO :: Loaded faction : resources\factions\australia_2005.json
2021-05-27 12:47:18,867 :: INFO :: Loaded faction : resources\factions\australia_2005_c130.json
2021-05-27 12:47:18,868 :: INFO :: Loaded faction : resources\factions\bluefor_coldwar.json
2021-05-27 12:47:18,868 :: INFO :: Loaded faction : resources\factions\bluefor_coldwar_a4.json
2021-05-27 12:47:18,868 :: INFO :: Loaded faction : resources\factions\bluefor_coldwar_a4_mb339.json
2021-05-27 12:47:18,869 :: INFO :: Loaded faction : resources\factions\bluefor_modern.json
2021-05-27 12:47:18,869 :: INFO :: Loaded faction : resources\factions\canada_2005.json
2021-05-27 12:47:18,869 :: INFO :: Loaded faction : resources\factions\canada_2005_c130.json
2021-05-27 12:47:18,869 :: INFO :: Loaded faction : resources\factions\china_2010.json
2021-05-27 12:47:18,870 :: INFO :: Loaded faction : resources\factions\dprk_1950_fictional.json
2021-05-27 12:47:18,870 :: INFO :: Loaded faction : resources\factions\france_1985_frenchpack.json
2021-05-27 12:47:18,870 :: INFO :: Loaded faction : resources\factions\france_1995.json
2021-05-27 12:47:18,871 :: INFO :: Loaded faction : resources\factions\france_2005_frenchpack.json
2021-05-27 12:47:18,871 :: INFO :: Loaded faction : resources\factions\gdr_1985.json
2021-05-27 12:47:18,871 :: INFO :: Loaded faction : resources\factions\georgia_2008.json
2021-05-27 12:47:18,872 :: INFO :: Loaded faction : resources\factions\germany_1940.json
2021-05-27 12:47:18,872 :: INFO :: Loaded faction : resources\factions\germany_1942.json
2021-05-27 12:47:18,872 :: INFO :: Loaded faction : resources\factions\germany_1944.json
2021-05-27 12:47:18,872 :: INFO :: Loaded faction : resources\factions\germany_1944_free.json
2021-05-27 12:47:18,873 :: INFO :: Loaded faction : resources\factions\germany_1990.json
2021-05-27 12:47:18,873 :: INFO :: Loaded faction : resources\factions\greece_2005.json
2021-05-27 12:47:18,873 :: INFO :: Loaded faction : resources\factions\india_2010.json
2021-05-27 12:47:18,874 :: INFO :: Loaded faction : resources\factions\insurgents.json
2021-05-27 12:47:18,875 :: INFO :: Loaded faction : resources\factions\insurgents_hard.json
2021-05-27 12:47:18,876 :: INFO :: Loaded faction : resources\factions\insurgents_modded.json
2021-05-27 12:47:18,876 :: INFO :: Loaded faction : resources\factions\iran_1988.json
2021-05-27 12:47:18,876 :: INFO :: Loaded faction : resources\factions\iran_2015.json
2021-05-27 12:47:18,877 :: INFO :: Loaded faction : resources\factions\iraq_1991.json
2021-05-27 12:47:18,877 :: INFO :: Loaded faction : resources\factions\israel_1948.json
2021-05-27 12:47:18,877 :: INFO :: Loaded faction : resources\factions\israel_1973.json
2021-05-27 12:47:18,877 :: INFO :: Loaded faction : resources\factions\israel_1982.json
2021-05-27 12:47:18,878 :: INFO :: Loaded faction : resources\factions\israel_2000.json
2021-05-27 12:47:18,878 :: INFO :: Loaded faction : resources\factions\italy_1990.json
2021-05-27 12:47:18,878 :: INFO :: Loaded faction : resources\factions\italy_1990_mb339.json
2021-05-27 12:47:18,879 :: INFO :: Loaded faction : resources\factions\japan_2005.json
2021-05-27 12:47:18,879 :: INFO :: Loaded faction : resources\factions\libya_2011.json
2021-05-27 12:47:18,879 :: INFO :: Loaded faction : resources\factions\NATO_Desert_Storm.json
2021-05-27 12:47:18,880 :: INFO :: Loaded faction : resources\factions\netherlands_1990.json
2021-05-27 12:47:18,880 :: INFO :: Loaded faction : resources\factions\north_korea_2000.json
2021-05-27 12:47:18,880 :: INFO :: Loaded faction : resources\factions\pakistan_2015.json
2021-05-27 12:47:18,880 :: INFO :: Loaded faction : resources\factions\pmc_russian.json
2021-05-27 12:47:18,881 :: INFO :: Loaded faction : resources\factions\pmc_us.json
2021-05-27 12:47:18,881 :: INFO :: Loaded faction : resources\factions\pmc_us_with_mb339.json
2021-05-27 12:47:18,881 :: INFO :: Loaded faction : resources\factions\poland_2010.json
2021-05-27 12:47:18,882 :: INFO :: Loaded faction : resources\factions\redfor_china_2010.json
2021-05-27 12:47:18,882 :: INFO :: Loaded faction : resources\factions\redfor_russia_2010.json
2021-05-27 12:47:18,882 :: INFO :: Loaded faction : resources\factions\russia_1955.json
2021-05-27 12:47:18,883 :: INFO :: Loaded faction : resources\factions\russia_1965.json
2021-05-27 12:47:18,883 :: INFO :: Loaded faction : resources\factions\russia_1970_limited_air.json
2021-05-27 12:47:18,883 :: INFO :: Loaded faction : resources\factions\russia_1975.json
2021-05-27 12:47:18,884 :: INFO :: Loaded faction : resources\factions\russia_1990.json
2021-05-27 12:47:18,884 :: INFO :: Loaded faction : resources\factions\russia_2010.json
2021-05-27 12:47:18,884 :: INFO :: Loaded faction : resources\factions\russia_2010_hds.json
2021-05-27 12:47:18,884 :: INFO :: Loaded faction : resources\factions\russia_2020.json
2021-05-27 12:47:18,885 :: INFO :: Loaded faction : resources\factions\soviet_union_1943.json
2021-05-27 12:47:18,885 :: INFO :: Loaded faction : resources\factions\spain_1990.json
2021-05-27 12:47:18,885 :: INFO :: Loaded faction : resources\factions\sweden_1970.json
2021-05-27 12:47:18,886 :: INFO :: Loaded faction : resources\factions\sweden_1990.json
2021-05-27 12:47:18,886 :: INFO :: Loaded faction : resources\factions\syria_1948.json
2021-05-27 12:47:18,886 :: INFO :: Loaded faction : resources\factions\syria_1967.json
2021-05-27 12:47:18,886 :: INFO :: Loaded faction : resources\factions\syria_1967_with_ww2_weapons.json
2021-05-27 12:47:18,887 :: INFO :: Loaded faction : resources\factions\syria_1973.json
2021-05-27 12:47:18,887 :: INFO :: Loaded faction : resources\factions\syria_1982.json
2021-05-27 12:47:18,887 :: INFO :: Loaded faction : resources\factions\syria_2011.json
2021-05-27 12:47:18,888 :: INFO :: Loaded faction : resources\factions\turkey_2005.json
2021-05-27 12:47:18,888 :: INFO :: Loaded faction : resources\factions\uae_2005.json
2021-05-27 12:47:18,888 :: INFO :: Loaded faction : resources\factions\uae_2015.json
2021-05-27 12:47:18,889 :: INFO :: Loaded faction : resources\factions\ukraine_2010.json
2021-05-27 12:47:18,889 :: INFO :: Loaded faction : resources\factions\uk_1944.json
2021-05-27 12:47:18,889 :: INFO :: Loaded faction : resources\factions\uk_1990.json
2021-05-27 12:47:18,889 :: INFO :: Loaded faction : resources\factions\unc_1950_fictional.json
2021-05-27 12:47:18,891 :: INFO :: Loaded faction : resources\factions\usa_1944.json
2021-05-27 12:47:18,891 :: INFO :: Loaded faction : resources\factions\usa_1955.json
2021-05-27 12:47:18,892 :: INFO :: Loaded faction : resources\factions\usa_1960.json
2021-05-27 12:47:18,892 :: INFO :: Loaded faction : resources\factions\usa_1965.json
2021-05-27 12:47:18,892 :: INFO :: Loaded faction : resources\factions\usa_1975.json
2021-05-27 12:47:18,892 :: INFO :: Loaded faction : resources\factions\usa_1990.json
2021-05-27 12:47:18,893 :: INFO :: Loaded faction : resources\factions\usa_2005.json
2021-05-27 12:47:18,893 :: INFO :: Loaded faction : resources\factions\usa_2005_c130.json
2021-05-27 12:47:18,893 :: INFO :: Loaded faction : resources\factions\usa_2005_modded.json
2021-05-27 12:47:18,894 :: INFO :: Loaded faction : resources\factions\usn_1985.json
2021-05-27 12:47:18,894 :: INFO :: Loaded faction : resources\factions\us_aggressors.json
2021-05-27 12:47:18,946 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.address`.
2021-05-27 12:47:18,949 :: DEBUG :: Provider `faker.providers.address` has been localized to `en_US`.
2021-05-27 12:47:18,950 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.automotive`.
2021-05-27 12:47:18,951 :: DEBUG :: Provider `faker.providers.automotive` has been localized to `en_US`.
2021-05-27 12:47:18,952 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.bank`.
2021-05-27 12:47:18,953 :: DEBUG :: Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2021-05-27 12:47:18,953 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.barcode`.
2021-05-27 12:47:18,954 :: DEBUG :: Provider `faker.providers.barcode` has been localized to `en_US`.
2021-05-27 12:47:18,954 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.color`.
2021-05-27 12:47:18,955 :: DEBUG :: Provider `faker.providers.color` has been localized to `en_US`.
2021-05-27 12:47:18,956 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.company`.
2021-05-27 12:47:18,957 :: DEBUG :: Provider `faker.providers.company` has been localized to `en_US`.
2021-05-27 12:47:18,957 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.credit_card`.
2021-05-27 12:47:18,958 :: DEBUG :: Provider `faker.providers.credit_card` has been localized to `en_US`.
2021-05-27 12:47:18,958 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.currency`.
2021-05-27 12:47:18,959 :: DEBUG :: Provider `faker.providers.currency` has been localized to `en_US`.
2021-05-27 12:47:18,959 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.date_time`.
2021-05-27 12:47:18,961 :: DEBUG :: Provider `faker.providers.date_time` has been localized to `en_US`.
2021-05-27 12:47:18,961 :: DEBUG :: Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-05-27 12:47:18,961 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.geo`.
2021-05-27 12:47:18,962 :: DEBUG :: Provider `faker.providers.geo` has been localized to `en_US`.
2021-05-27 12:47:18,962 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.internet`.
2021-05-27 12:47:18,964 :: DEBUG :: Provider `faker.providers.internet` has been localized to `en_US`.
2021-05-27 12:47:18,964 :: DEBUG :: Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-05-27 12:47:18,964 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.job`.
2021-05-27 12:47:18,966 :: DEBUG :: Provider `faker.providers.job` has been localized to `en_US`.
2021-05-27 12:47:18,966 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.lorem`.
2021-05-27 12:47:18,967 :: DEBUG :: Provider `faker.providers.lorem` has been localized to `en_US`.
2021-05-27 12:47:18,968 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.misc`.
2021-05-27 12:47:18,969 :: DEBUG :: Provider `faker.providers.misc` has been localized to `en_US`.
2021-05-27 12:47:18,969 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.person`.
2021-05-27 12:47:18,972 :: DEBUG :: Provider `faker.providers.person` has been localized to `en_US`.
2021-05-27 12:47:18,973 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.phone_number`.
2021-05-27 12:47:18,976 :: DEBUG :: Provider `faker.providers.phone_number` has been localized to `en_US`.
2021-05-27 12:47:18,976 :: DEBUG :: Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-05-27 12:47:18,976 :: DEBUG :: Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-05-27 12:47:18,976 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.ssn`.
2021-05-27 12:47:18,978 :: DEBUG :: Provider `faker.providers.ssn` has been localized to `en_US`.
2021-05-27 12:47:18,979 :: DEBUG :: Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-05-27 12:47:18,979 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.address`.
2021-05-27 12:47:18,981 :: DEBUG :: Provider `faker.providers.address` has been localized to `en_US`.
2021-05-27 12:47:18,981 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.automotive`.
2021-05-27 12:47:18,983 :: DEBUG :: Provider `faker.providers.automotive` has been localized to `en_US`.
2021-05-27 12:47:18,983 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.bank`.
2021-05-27 12:47:18,984 :: DEBUG :: Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2021-05-27 12:47:18,984 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.barcode`.
2021-05-27 12:47:18,985 :: DEBUG :: Provider `faker.providers.barcode` has been localized to `en_US`.
2021-05-27 12:47:18,985 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.color`.
2021-05-27 12:47:18,986 :: DEBUG :: Provider `faker.providers.color` has been localized to `en_US`.
2021-05-27 12:47:18,986 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.company`.
2021-05-27 12:47:18,988 :: DEBUG :: Provider `faker.providers.company` has been localized to `en_US`.
2021-05-27 12:47:18,988 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.credit_card`.
2021-05-27 12:47:18,989 :: DEBUG :: Provider `faker.providers.credit_card` has been localized to `en_US`.
2021-05-27 12:47:18,989 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.currency`.
2021-05-27 12:47:18,990 :: DEBUG :: Provider `faker.providers.currency` has been localized to `en_US`.
2021-05-27 12:47:18,990 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.date_time`.
2021-05-27 12:47:18,992 :: DEBUG :: Provider `faker.providers.date_time` has been localized to `en_US`.
2021-05-27 12:47:18,992 :: DEBUG :: Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-05-27 12:47:18,992 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.geo`.
2021-05-27 12:47:18,992 :: DEBUG :: Provider `faker.providers.geo` has been localized to `en_US`.
2021-05-27 12:47:18,993 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.internet`.
2021-05-27 12:47:18,994 :: DEBUG :: Provider `faker.providers.internet` has been localized to `en_US`.
2021-05-27 12:47:18,995 :: DEBUG :: Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-05-27 12:47:18,995 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.job`.
2021-05-27 12:47:18,996 :: DEBUG :: Provider `faker.providers.job` has been localized to `en_US`.
2021-05-27 12:47:18,996 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.lorem`.
2021-05-27 12:47:18,997 :: DEBUG :: Provider `faker.providers.lorem` has been localized to `en_US`.
2021-05-27 12:47:18,998 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.misc`.
2021-05-27 12:47:18,998 :: DEBUG :: Provider `faker.providers.misc` has been localized to `en_US`.
2021-05-27 12:47:18,998 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.person`.
2021-05-27 12:47:19,001 :: DEBUG :: Provider `faker.providers.person` has been localized to `en_US`.
2021-05-27 12:47:19,001 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.phone_number`.
2021-05-27 12:47:19,003 :: DEBUG :: Provider `faker.providers.phone_number` has been localized to `en_US`.
2021-05-27 12:47:19,004 :: DEBUG :: Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-05-27 12:47:19,004 :: DEBUG :: Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-05-27 12:47:19,004 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.ssn`.
2021-05-27 12:47:19,006 :: DEBUG :: Provider `faker.providers.ssn` has been localized to `en_US`.
2021-05-27 12:47:19,006 :: DEBUG :: Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-05-27 12:47:19,007 :: INFO :: On Game generated
2021-05-27 12:47:19,076 :: DEBUG :: Map reset took 0:00:00.026198
Traceback (most recent call last):
  File "windows\mission\flight\QFlightCreator.py", line 187, in create_flight
AttributeError: can't set attribute
Traceback (most recent call last):
  File "windows\mission\flight\QFlightCreator.py", line 187, in create_flight
AttributeError: can't set attribute

**Version information (please complete the following information):**
 DCS Liberation -V 3.0 1683 Preview

**Additional context**

**Comment by DanAlbert** [comment]
Hacked back into working order for now by auto-converting pilots into player slots if needed. What this actually needs is a roster editor like the flight edit dialog has, but before we can do that we also need squadron selection in the new flight UI, which we're not quite ready for.

Filed https://github.com/dcs-liberation/dcs_liberation/issues/1142 and https://github.com/dcs-liberation/dcs_liberation/issues/1143 for the follow up work, but this is back to no worse than it was before so closing.
