### ISSUE TITLE
Navmesh Error on Turn 0 on Nevada Map

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1140]
**Describe the bug**
Recieving this error on attempt to pass Turn 0.

Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 159, in passTurn
  File "game\game.py", line 356, in pass_turn
  File "game\game.py", line 412, in initialize_turn
  File "gen\flights\ai_flight_planner.py", line 786, in plan_missions
  File "gen\flights\ai_flight_planner.py", line 909, in plan_mission
  File "gen\flights\flightplan.py", line 874, in populate_flight_plan
  File "gen\flights\flightplan.py", line 962, in regenerate_package_waypoints
  File "gen\flights\flightplan.py", line 1006, in preferred_join_point
  File "game\navmesh.py", line 150, in shortest_path
game.navmesh.NavMeshError: Destination point Point(-224249.31150512, 32633.39168519) is outside the navmesh

**Version information (please complete the following information):**
#1689 preview

Scenario file and .liberation file included.
[Files.zip](https://github.com/dcs-liberation/dcs_liberation/files/6556781/Files.zip)

**Comment by DanAlbert** [comment]
Apparently you managed to place an objective _exactly_ on the boundary between two zones

![image](https://user-images.githubusercontent.com/315852/120052532-a1027280-bfda-11eb-8971-e38c584f22bb.png)

I would not have believed that was possible if the debugger wasn't telling me that's what happened.

The geometry library we use defines "contains" as "fully within the interior of the shape", so by being on the boundary it is not _within_ any zone.
