### ISSUE TITLE
List Index Out Of Range error when generating pilot name

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1144]
**Describe the bug**
Got this error upon generating a new campaign. Does not happen consistently.

Traceback (most recent call last):
  File "windows\newgame\QNewGameWizard.py", line 115, in accept
  File "game\theater\start_generator.py", line 101, in generate
  File "game\game.py", line 148, in __init__
  File "game\squadrons.py", line 204, in __init__
  File "game\squadrons.py", line 256, in random_nickname
  File "game\squadrons.py", line 237, in _make_random_nickname
  File "random.py", line 347, in choice
IndexError: list index out of range

**Version information (please complete the following information):**
#1691

**Comment by DanAlbert** [comment]
Probably fixed.
