### ISSUE TITLE
Battle for Abu Dhabi campaign fails passing turn zero with max enemy starting budget + player assists + 30 minute mission duration

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1154]
**Describe the bug**
The program does not advance on turn 0 after pressing turn under the conditions mentioned in the title

**To Reproduce**
1) Start new Battle for Abu Dhabi campaign
2) Set desired mission duration to 30 minutes
3) Set enemy starting budget to maximum
4) Select any of the "automate" player assists at the bottom
5) Press pass turn
6) Observe that game doesn't advance and throws error in command log:

> Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 159, in passTurn
  File "game\game.py", line 358, in pass_turn
  File "game\game.py", line 427, in initialize_turn
  File "gen\flights\ai_flight_planner.py", line 846, in plan_missions
  File "gen\flights\ai_flight_planner.py", line 1062, in stagger_missions
  File "gen\flights\ai_flight_planner.py", line 1013, in start_time_generator
ValueError: range() arg 3 must not be zero

Build 1715
[maxbudgeterror.zip](https://github.com/dcs-liberation/dcs_liberation/files/6565682/maxbudgeterror.zip)

**Comment by DanAlbert** [comment]
Apparently this happens whenever you have enough non-BARCAP packages that they need to be scheduled more quickly than once per minute.

**Comment by DanAlbert** [comment]
Switched to scheduling in seconds. If your game has more packages than it has seconds in the mission you should probably just quit :)

**Comment by Hornet2041** [comment]
Build 1795, same issue, this time with $4000 starting budget and no player assist:

[failedagain.zip](https://github.com/dcs-liberation/dcs_liberation/files/6603378/failedagain.zip)

Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 133, in passTurn
  File "game\game.py", line 357, in pass_turn
  File "game\game.py", line 426, in initialize_turn
  File "gen\flights\ai_flight_planner.py", line 840, in plan_missions
  File "gen\flights\ai_flight_planner.py", line 1056, in stagger_missions
  File "gen\flights\ai_flight_planner.py", line 1007, in start_time_generator
ValueError: range() arg 3 must not be zero


edit: should add I disabled auto generation of player-side flights

**Comment by Hornet2041** [comment]
as soon as I incremented the mission duration slider the program instantly updated and passed the turn 😮

**Comment by DanAlbert** [comment]
Because 1795 is too old to have the fix.

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/actions/runs/910135033

**Comment by Hornet2041** [comment]
> Because 1795 is too old to have the fix.

wow, i was more messed up on painkillers than i thought yesterday. sorry D:
