### ISSUE TITLE
3.0 Take Off Button

### ISSUE THREAD

**Issue by Eagle01ph** [dcs-liberation/dcs_liberation#1213]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
Nothing happens when the "Take Off" button is pressed if a pilot is assigned to any aircraft.  If there is no pilot assigned and the Take Off button is pressed.  You get the warning that only AI would fly the mission, after clicking "Ok", nothing happens.

**To Reproduce**
1. Download 3.0 
2. Unzip the 3.0 version of Liberation
3. Run Liberation
4. Start a new campaign and purchase units.  
5. Assign a player to a flight, that is flyable in DCS
6. Press the Take Off button

**Expected behavior**
I would expect a window to appear with the Manual Submit and Abort Mission buttons.  And a .miz file would be created.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:
Attached the Liberation Campaign file.
[3.0 Golan.zip](https://github.com/dcs-liberation/dcs_liberation/files/6641465/3.0.Golan.zip)

**Version information (please complete the following information):**
 - DCS Liberation 3.0.0

**Additional context**

**Comment by DanAlbert** [comment]
Works for me. What does the log say?

**Comment by Eagle01ph** [comment]
Hi Dan,

This is what is in the cmd window.

2021-06-12 09:35:19,416 :: INFO :: Generating AirWar (regular)
2021-06-12 09:35:19,421 :: INFO :: Set up fire task for missile group.
2021-06-12 09:35:19,422 :: INFO :: Set up fire task for missile group.
2021-06-12 09:35:19,424 :: INFO :: Set up fire task for missile group.
2021-06-12 09:35:19,506 :: INFO :: Generating flight: <class 'dcs.planes.E_2C'>
2021-06-12 09:35:19,506 :: INFO :: airgen: <class 'dcs.planes.E_2C'> for 15 at Distance(distance_in_meters=3000) at 500
2021-06-12 09:35:19,511 :: INFO :: Generating flight: <class 'dcs.planes.F_15C'>
2021-06-12 09:35:19,512 :: INFO :: airgen: <class 'dcs.planes.F_15C'> for 15 at Airport(Ramat David)
2021-06-12 09:35:19,541 :: INFO :: Generating flight: <class 'dcs.planes.M_2000C'>
2021-06-12 09:35:19,541 :: INFO :: airgen: <class 'dcs.planes.M_2000C'> for 15 at Airport(Ramat David)
2021-06-12 09:35:19,561 :: INFO :: Generating flight: <class 'dcs.planes.A_10C'>
2021-06-12 09:35:19,562 :: INFO :: airgen: <class 'dcs.planes.A_10C'> for 15 at Airport(Ramat David)
2021-06-12 09:35:19,598 :: INFO :: Generating flight: <class 'dcs.planes.F_16C_50'>
2021-06-12 09:35:19,598 :: INFO :: airgen: <class 'dcs.planes.F_16C_50'> for 15 at Airport(Ramat David)
2021-06-12 09:35:19,636 :: INFO :: Generating flight: <class 'dcs.planes.FA_18C_hornet'>
2021-06-12 09:35:19,636 :: INFO :: airgen: <class 'dcs.planes.FA_18C_hornet'> for 15 at Airport(Ramat David)
2021-06-12 09:35:19,667 :: INFO :: Generating flight: <class 'dcs.planes.F_16C_50'>
2021-06-12 09:35:19,667 :: INFO :: airgen: <class 'dcs.planes.F_16C_50'> for 15 at Airport(Ramat David)
2021-06-12 09:35:19,670 :: INFO :: Generating flight: <class 'dcs.planes.A_50'>
2021-06-12 09:35:19,671 :: INFO :: airgen: <class 'dcs.planes.A_50'> for 81 at Airport(Damascus)
2021-06-12 09:35:19,675 :: INFO :: Generating flight: <class 'dcs.planes.MiG_25PD'>
2021-06-12 09:35:19,676 :: INFO :: airgen: <class 'dcs.planes.MiG_25PD'> for 81 at Distance(distance_in_meters=3000) at 1003
2021-06-12 09:35:19,684 :: ERROR :: Plane MiG-25PD has no pylon 5.
2021-06-12 09:35:19,684 :: WARNING :: No room on runway or parking slots. Starting from the air.
2021-06-12 09:35:19,685 :: INFO :: airgen: <class 'dcs.planes.MiG_25PD'> for 81 at Distance(distance_in_meters=3000) at 1003
Traceback (most recent call last):
  File "gen\aircraft.py", line 1154, in generate_planned_flight
  File "gen\aircraft.py", line 929, in _generate_inflight
  File "dcs\mission.py", line 1197, in flight_group
  File "dcs\mission.py", line 1053, in flight_group_inflight
  File "dcs\mission.py", line 989, in _flying_group_inflight
  File "dcs\unitgroup.py", line 442, in load_task_default_loadout
  File "dcs\flyingunit.py", line 77, in load_pylon
RuntimeError: Plane MiG-25PD has no pylon 5.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 274, in launch_mission
  File "game\game.py", line 281, in initiate_event
  File "game\event\event.py", line 64, in generate
  File "game\operation\operation.py", line 315, in generate
  File "game\operation\operation.py", line 389, in _generate_air_units
  File "gen\aircraft.py", line 1032, in generate_flights
  File "gen\aircraft.py", line 1187, in generate_planned_flight
  File "gen\aircraft.py", line 929, in _generate_inflight
  File "dcs\mission.py", line 1197, in flight_group
  File "dcs\mission.py", line 1053, in flight_group_inflight
  File "dcs\mission.py", line 989, in _flying_group_inflight
  File "dcs\unitgroup.py", line 442, in load_task_default_loadout
  File "dcs\flyingunit.py", line 77, in load_pylon
RuntimeError: Plane MiG-25PD has no pylon 5.
2021-06-12 09:36:47,044 :: DEBUG :: Map reset took 0:00:00.039750

**Comment by DanAlbert** [comment]
Did you make a custom loadout for the MiG-25PD? If so it looks like it's broken. If not then I'm out of ideas, because this works just fine on my machine.

**Comment by Eagle01ph** [comment]
I once had the MiG-25PD mod.  But uninstalled it since 2.7 came out.  But no custom loadout for Liberation. This was actually the first mission for 3.0.

If Liberation reads what's already in DCS would you know where I can delete the Mig-25PD loadouts?

**Comment by Eagle01ph** [comment]
Fixed it.  Thank you for pointing me in the right direction.

I have 2 installs of DCS.  Stable and OpenBeta.  For some reason, even though I set Liberation to look at the Saved game\DCS.Openbeta folder in saved games.  It was also looking at the saved games\DCS folder which had the Mig-25PD custom loadout.
