### ISSUE TITLE
TypeError: '>' not supported between instances of 'float' and 'Speed'

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#1234]
**Describe the bug**
 
Using build 1936, hitting Take/Off results in the following in the log (and no indication of any issue in the UI, though there is no mission generated):
[test.zip](https://github.com/dcs-liberation/dcs_liberation/files/6646828/test.zip)

~~~
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 725, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 733, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 457, in timing
  File "gen\flights\flightplan.py", line 718, in tot_for_waypoint
  File "gen\flights\flightplan.py", line 707, in sweep_start_time
  File "gen\flights\flightplan.py", line 307, in travel_time_between_waypoints
  File "gen\flights\flightplan.py", line 199, in travel_time_between_waypoints
  File "gen\flights\flightplan.py", line 125, in speed_between_waypoints
  File "gen\flights\flightplan.py", line 122, in best_speed_between_waypoints
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'int' and 'Speed'
Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 460, in timing
  File "gen\flights\flightplan.py", line 301, in depart_time_for_waypoint
  File "gen\flights\flightplan.py", line 389, in push_time
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 260, in launch_mission
  File "widgets\QTopPanel.py", line 144, in negative_start_packages
  File "gen\flights\traveltime.py", line 64, in mission_start_time
  File "gen\flights\flightplan.py", line 239, in startup_time
  File "gen\flights\flightplan.py", line 236, in takeoff_time
  File "gen\flights\flightplan.py", line 192, in _travel_time_to_waypoint
  File "gen\flights\flightplan.py", line 307, in travel_time_between_waypoints
  File "gen\flights\flightplan.py", line 199, in travel_time_between_waypoints
  File "gen\flights\flightplan.py", line 592, in speed_between_waypoints
  File "gen\flights\flightplan.py", line 362, in speed_between_waypoints
  File "gen\flights\flightplan.py", line 125, in speed_between_waypoints
  File "gen\flights\flightplan.py", line 122, in best_speed_between_waypoints
  File "gen\flights\traveltime.py", line 35, in for_flight
TypeError: '>' not supported between instances of 'float' and 'Speed'
~~~

**Expected behavior**

A mission to be generated.

**Additional information**

Save file attached.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: Build 1936

**Comment by DanAlbert** [comment]
I assume this wasn't a new game? This looks like save compat issues.

**Comment by jeetsukumaran** [comment]
Ah, you might be right. May have got my saves confused. Closing this now. Will reopen if it reoccurs.
