### ISSUE TITLE
Campaigns with SCUDs cannot begin

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1255]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
campaign doesnt launch if faction has scuds/missile generator

**To Reproduce**
1. start new allied sword campaign
2. choose any enemy faction that has scud generator (syria 2012'ish tested)
3. press finish after all other campaign settings set
4. observe that it cannot launch

**Expected behavior**
for liberation to start a campaign

**Additional information**
fresh build, no custom factions used

**Version information (please complete the following information):**
 - DCS Liberation: build 1971

**Additional context**
Traceback (most recent call last):
  File "windows\newgame\QNewGameWizard.py", line 115, in accept
  File "game\theater\start_generator.py", line 111, in generate
  File "game\theater\start_generator.py", line 599, in generate
  File "game\theater\start_generator.py", line 624, in generate_for_control_point
  File "game\theater\start_generator.py", line 278, in generate
  File "game\theater\start_generator.py", line 293, in generate_ground_points
  File "game\theater\start_generator.py", line 486, in generate_missile_sites
  File "game\theater\start_generator.py", line 494, in generate_missile_site_at
  File "gen\missiles\missiles_group_generator.py", line 22, in generate_missile_group
  File "gen\missiles\scud_site.py", line 17, in generate
AttributeError: type object 'MissilesSS' has no attribute 'SSM_SS_1C_Scud_B'

**Comment by Hornet2041** [comment]
fixed as of https://github.com/dcs-liberation/dcs_liberation/commit/d8511fab1d596b7196a3a05302a0534ee5dc3b6f
