### ISSUE TITLE
unticking "generate infantry squads" prevents mission generation

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1256]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
campaign fails to launch mission after ATO generated

**To Reproduce**
1. begin new campaign of allied sword
2. choose russia 1990 as opfor to avoid current SCUDs bug
3. set up campaign + turn zero
4. generate ATO, assign player flight, select takeoff
5. see that mission does not launch

**Expected behavior**
for liberation to generate a mission

**Additional information**

[allied sword v1971.zip](https://github.com/dcs-liberation/dcs_liberation/files/6676586/allied.sword.v1971.zip)
.liberation file attached

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: build 1971

**Additional context**
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 274, in launch_mission
  File "game\game.py", line 281, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 303, in generate
  File "game\operation\operation.py", line 411, in _generate_ground_conflicts
  File "gen\armor.py", line 149, in generate
  File "gen\armor.py", line 775, in _generate_groups
  File "gen\armor.py", line 239, in gen_infantry_group_for_group
  File "dcs\mission.py", line 684, in vehicle_group
  File "dcs\mission.py", line 658, in vehicle
TypeError: issubclass() arg 1 must be a class

**Comment by Hornet2041** [comment]
update: ticking "generate infantry squads along vehicles" lets me generate the mission again.
