### ISSUE TITLE
Control Point Window won't open for Tiyas on Syria

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1314]
**Describe the bug**
Left-clicking on Tiyas won't open the regular Control Point window. This is the error in the log window. I have included the .liberation file.

Traceback (most recent call last):
  File "widgets\map\mapmodel.py", line 171, in showInfoDialog
  File "windows\basemenu\QBaseMenu2.py", line 87, in __init__
  File "windows\basemenu\QBaseMenuTabs.py", line 19, in __init__
  File "windows\basemenu\DepartingConvoysMenu.py", line 97, in __init__
  File "windows\basemenu\DepartingConvoysMenu.py", line 77, in __init__
  File "windows\basemenu\DepartingConvoysMenu.py", line 36, in __init__
AttributeError: 'GroundUnitType' object has no attribute 'id'

Preview #2105

[Peace Spring Post Cyprus Test 1.zip](https://github.com/dcs-liberation/dcs_liberation/files/6693095/Peace.Spring.Post.Cyprus.Test.1.zip)

**Comment by RndName** [comment]
i think this i connected with #1299
