### ISSUE TITLE
Anti-ship mission on Kuznetsov reverts to a closer enemy ship group

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#1346]
Build 2201. Tried to create an anti-ship mission on the Kuznetsov but the target waypoint snaps instead to a closer ship group with 1 ship left alive.

[antiship on kuz reverts to nearer ship group.zip](https://github.com/dcs-liberation/dcs_liberation/files/6714808/antiship.on.kuz.reverts.to.nearer.ship.group.zip)

Just throwing out a guess here that Liberation thinks the enemy carrier groups is an _airfield control point_ and not a ship group, despite being able to task anti-ship missions to it.

**Comment by Hornet2041** [comment]
![image](https://user-images.githubusercontent.com/55866858/123397068-057c0780-d570-11eb-9b5a-84c6ab6cd0e1.png)

**Comment by Hornet2041** [comment]
with the nearby enemy ship group destroyed, an anti-ship mission on the carrier generates no waypoints 

![image](https://user-images.githubusercontent.com/55866858/123485105-760a3f00-d5d7-11eb-91cf-b31ae870e5a5.png)


Traceback (most recent call last):
  File "windows\mission\QPackageDialog.py", line 186, in add_flight
  File "gen\flights\flightplan.py", line 899, in populate_flight_plan
  File "gen\flights\flightplan.py", line 913, in generate_flight_plan
  File "gen\flights\flightplan.py", line 1161, in generate_anti_ship
  File "gen\flights\flightplan.py", line 1800, in strike_flightplan
  File "gen\flights\flightplan.py", line 1703, in target_waypoint
  File "gen\flights\waypointbuilder.py", line 237, in bai_group
  File "gen\flights\waypointbuilder.py", line 252, in _target_point
  File "dcs\unitgroup.py", line 71, in position
IndexError: list index out of range
