### ISSUE TITLE
Errors after 1 mission completed

### ISSUE THREAD

**Issue by Tinchus2009** [dcs-liberation/dcs_liberation#1402]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
I installed version 4.0. stated a campaign, I changed the designated coalition. I finished the forst mission with no problems.
Today I wanted to go for the second round and I cant start the mission. After trying "take off"nothing happens and I get errors in the console. This is the copy of the console contents:

2021-07-01 22:20:59,140 :: INFO :: DCS Liberation 4.0.0
2021-07-01 22:20:59,140 :: DEBUG :: Python version 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
2021-07-01 22:20:59,228 :: ERROR :: Using default theme because liberation_theme.json does not exist
2021-07-01 22:20:59,228 :: INFO :: Loading stylesheet: style-dcs.css
2021-07-01 22:20:59,228 :: DEBUG :: Loading Liberation preferences from C:\Users\User\AppData\Local\DCSLiberation\liberation_preferences.json
2021-07-01 22:20:59,229 :: INFO :: Using C:\Users\User\Saved Games\DCS.openbeta as 'Saved Game Folder'
2021-07-01 22:20:59,229 :: INFO :: Using D:/Eagle Dynamics/DCS World OpenBeta as 'DCS installation folder'
C:/Users/User/Saved Games/DCS.openbeta/Liberation/Saves/camp1.liberation
2021-07-01 22:21:00,825 :: INFO :: Loading last saved game : C:/Users/User/Saved Games/DCS.openbeta/Liberation/Saves/camp1.liberation
2021-07-01 22:21:00,839 :: WARNING :: No data for Ka-27; it will not be available
2021-07-01 22:21:00,841 :: WARNING :: No data for SH-3W; it will not be available
2021-07-01 22:21:00,898 :: WARNING :: No data for F/A-18A; it will not be available
2021-07-01 22:21:00,899 :: WARNING :: No data for F/A-18C; it will not be available
2021-07-01 22:21:00,899 :: WARNING :: No data for F-14A; it will not be available
2021-07-01 22:21:00,914 :: WARNING :: No data for Su-25TM; it will not be available
2021-07-01 22:21:00,967 :: WARNING :: No data for F-16C bl.50; it will not be available
2021-07-01 22:21:00,968 :: WARNING :: No data for F-16C bl.52d; it will not be available
2021-07-01 22:21:00,969 :: WARNING :: No data for F-16A MLU; it will not be available
2021-07-01 22:21:01,023 :: WARNING :: No data for C-101EB; it will not be available
2021-07-01 22:21:01,032 :: WARNING :: No data for Christen Eagle II; it will not be available
2021-07-01 22:21:01,035 :: WARNING :: No data for F-5E; it will not be available
2021-07-01 22:21:01,051 :: WARNING :: No data for Hawk; it will not be available
2021-07-01 22:21:01,054 :: WARNING :: No data for L-39C; it will not be available
2021-07-01 22:21:01,071 :: WARNING :: No data for Yak-52; it will not be available
2021-07-01 22:21:01,077 :: WARNING :: No data for TF-51D; it will not be available
2021-07-01 22:21:01,259 :: INFO :: Reading plugins list from resources\plugins\plugins.json
2021-07-01 22:21:01,260 :: INFO :: Loading plugin base from resources\plugins\base\plugin.json
2021-07-01 22:21:01,260 :: INFO :: Loading plugin jtacautolase from resources\plugins\jtacautolase\plugin.json
2021-07-01 22:21:01,261 :: INFO :: Loading plugin skynetiads from resources\plugins\skynetiads\plugin.json
2021-07-01 22:21:01,262 :: INFO :: Loading plugin ewrs from resources\plugins\ewrs\plugin.json
2021-07-01 22:21:01,262 :: INFO :: Loading plugin herculescargo from resources\plugins\herculescargo\plugin.json
2021-07-01 22:21:01,263 :: INFO :: Loading plugin splashdamage from resources\plugins\splashdamage\plugin.json
2021-07-01 22:21:01,264 :: INFO :: Loading plugin lotatc from resources\plugins\lotatc\plugin.json
2021-07-01 22:21:01,338 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.address`.
2021-07-01 22:21:01,342 :: DEBUG :: Provider `faker.providers.address` has been localized to `ru_RU`.
2021-07-01 22:21:01,344 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.automotive`.
2021-07-01 22:21:01,346 :: DEBUG :: Provider `faker.providers.automotive` has been localized to `ru_RU`.
2021-07-01 22:21:01,347 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.bank`.
2021-07-01 22:21:01,349 :: DEBUG :: Provider `faker.providers.bank` has been localized to `ru_RU`.
2021-07-01 22:21:01,351 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.barcode`.
2021-07-01 22:21:01,352 :: DEBUG :: Specified locale `ru_RU` is not available for provider `faker.providers.barcode`. Locale reset to `en_US` for this provider.
2021-07-01 22:21:01,354 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.color`.
2021-07-01 22:21:01,356 :: DEBUG :: Provider `faker.providers.color` has been localized to `ru_RU`.
2021-07-01 22:21:01,357 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.company`.
2021-07-01 22:21:01,360 :: DEBUG :: Provider `faker.providers.company` has been localized to `ru_RU`.
2021-07-01 22:21:01,362 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.credit_card`.
2021-07-01 22:21:01,364 :: DEBUG :: Provider `faker.providers.credit_card` has been localized to `ru_RU`.
2021-07-01 22:21:01,366 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.currency`.
2021-07-01 22:21:01,368 :: DEBUG :: Provider `faker.providers.currency` has been localized to `ru_RU`.
2021-07-01 22:21:01,369 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.date_time`.
2021-07-01 22:21:01,371 :: DEBUG :: Provider `faker.providers.date_time` has been localized to `ru_RU`.
2021-07-01 22:21:01,372 :: DEBUG :: Provider `faker.providers.file` does not feature localization. Specified locale `ru_RU` is not utilized for this provider.
2021-07-01 22:21:01,373 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.geo`.
2021-07-01 22:21:01,374 :: DEBUG :: Specified locale `ru_RU` is not available for provider `faker.providers.geo`. Locale reset to `en_US` for this provider.
2021-07-01 22:21:01,375 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.internet`.
2021-07-01 22:21:01,377 :: DEBUG :: Provider `faker.providers.internet` has been localized to `ru_RU`.
2021-07-01 22:21:01,378 :: DEBUG :: Provider `faker.providers.isbn` does not feature localization. Specified locale `ru_RU` is not utilized for this provider.
2021-07-01 22:21:01,380 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.job`.
2021-07-01 22:21:01,382 :: DEBUG :: Provider `faker.providers.job` has been localized to `ru_RU`.
2021-07-01 22:21:01,383 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.lorem`.
2021-07-01 22:21:01,384 :: DEBUG :: Provider `faker.providers.lorem` has been localized to `ru_RU`.
2021-07-01 22:21:01,385 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.misc`.
2021-07-01 22:21:01,386 :: DEBUG :: Specified locale `ru_RU` is not available for provider `faker.providers.misc`. Locale reset to `en_US` for this provider.
2021-07-01 22:21:01,386 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.person`.
2021-07-01 22:21:01,389 :: DEBUG :: Provider `faker.providers.person` has been localized to `ru_RU`.
2021-07-01 22:21:01,390 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.phone_number`.
2021-07-01 22:21:01,393 :: DEBUG :: Provider `faker.providers.phone_number` has been localized to `ru_RU`.
2021-07-01 22:21:01,394 :: DEBUG :: Provider `faker.providers.profile` does not feature localization. Specified locale `ru_RU` is not utilized for this provider.
2021-07-01 22:21:01,396 :: DEBUG :: Provider `faker.providers.python` does not feature localization. Specified locale `ru_RU` is not utilized for this provider.
2021-07-01 22:21:01,396 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.ssn`.
2021-07-01 22:21:01,400 :: DEBUG :: Provider `faker.providers.ssn` has been localized to `ru_RU`.
2021-07-01 22:21:01,401 :: DEBUG :: Provider `faker.providers.user_agent` does not feature localization. Specified locale `ru_RU` is not utilized for this provider.
2021-07-01 22:21:01,401 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.address`.
2021-07-01 22:21:01,404 :: DEBUG :: Provider `faker.providers.address` has been localized to `en_US`.
2021-07-01 22:21:01,405 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.automotive`.
2021-07-01 22:21:01,407 :: DEBUG :: Provider `faker.providers.automotive` has been localized to `en_US`.
2021-07-01 22:21:01,408 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.bank`.
2021-07-01 22:21:01,410 :: DEBUG :: Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2021-07-01 22:21:01,412 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.barcode`.
2021-07-01 22:21:01,414 :: DEBUG :: Provider `faker.providers.barcode` has been localized to `en_US`.
2021-07-01 22:21:01,414 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.color`.
2021-07-01 22:21:01,416 :: DEBUG :: Provider `faker.providers.color` has been localized to `en_US`.
2021-07-01 22:21:01,416 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.company`.
2021-07-01 22:21:01,419 :: DEBUG :: Provider `faker.providers.company` has been localized to `en_US`.
2021-07-01 22:21:01,419 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.credit_card`.
2021-07-01 22:21:01,420 :: DEBUG :: Provider `faker.providers.credit_card` has been localized to `en_US`.
2021-07-01 22:21:01,421 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.currency`.
2021-07-01 22:21:01,422 :: DEBUG :: Provider `faker.providers.currency` has been localized to `en_US`.
2021-07-01 22:21:01,423 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.date_time`.
2021-07-01 22:21:01,427 :: DEBUG :: Provider `faker.providers.date_time` has been localized to `en_US`.
2021-07-01 22:21:01,428 :: DEBUG :: Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-07-01 22:21:01,429 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.geo`.
2021-07-01 22:21:01,430 :: DEBUG :: Provider `faker.providers.geo` has been localized to `en_US`.
2021-07-01 22:21:01,431 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.internet`.
2021-07-01 22:21:01,436 :: DEBUG :: Provider `faker.providers.internet` has been localized to `en_US`.
2021-07-01 22:21:01,437 :: DEBUG :: Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-07-01 22:21:01,437 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.job`.
2021-07-01 22:21:01,441 :: DEBUG :: Provider `faker.providers.job` has been localized to `en_US`.
2021-07-01 22:21:01,442 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.lorem`.
2021-07-01 22:21:01,445 :: DEBUG :: Provider `faker.providers.lorem` has been localized to `en_US`.
2021-07-01 22:21:01,446 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.misc`.
2021-07-01 22:21:01,447 :: DEBUG :: Provider `faker.providers.misc` has been localized to `en_US`.
2021-07-01 22:21:01,447 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.person`.
2021-07-01 22:21:01,451 :: DEBUG :: Provider `faker.providers.person` has been localized to `en_US`.
2021-07-01 22:21:01,453 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.phone_number`.
2021-07-01 22:21:01,456 :: DEBUG :: Provider `faker.providers.phone_number` has been localized to `en_US`.
2021-07-01 22:21:01,457 :: DEBUG :: Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-07-01 22:21:01,459 :: DEBUG :: Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-07-01 22:21:01,459 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.ssn`.
2021-07-01 22:21:01,464 :: DEBUG :: Provider `faker.providers.ssn` has been localized to `en_US`.
2021-07-01 22:21:01,466 :: DEBUG :: Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-07-01 22:21:01,469 :: INFO :: On Game generated
2021-07-01 22:21:01,579 :: DEBUG :: Map reset took 0:00:00.068479
2021-07-01 22:21:02,196 :: WARNING :: No data for Bunker; it will not be available
2021-07-01 22:21:02,199 :: WARNING :: No data for Sandbox; it will not be available
2021-07-01 22:21:02,205 :: WARNING :: No data for MLRS FDDM; it will not be available
2021-07-01 22:21:02,252 :: WARNING :: No data for Igla manpad INS; it will not be available
2021-07-01 22:21:02,262 :: WARNING :: No data for house1arm; it will not be available
2021-07-01 22:21:02,263 :: WARNING :: No data for house2arm; it will not be available
2021-07-01 22:21:02,263 :: WARNING :: No data for outpost_road; it will not be available
2021-07-01 22:21:02,264 :: WARNING :: No data for outpost; it will not be available
2021-07-01 22:21:02,264 :: WARNING :: No data for houseA_arm; it will not be available
2021-07-01 22:21:02,265 :: WARNING :: No data for TACAN_beacon; it will not be available
2021-07-01 22:21:02,287 :: WARNING :: No data for Ural-4320 APA-5D; it will not be available
2021-07-01 22:21:02,287 :: WARNING :: No data for ATMZ-5; it will not be available
2021-07-01 22:21:02,287 :: WARNING :: No data for ATZ-10; it will not be available
2021-07-01 22:21:02,292 :: WARNING :: No data for M978 HEMTT Tanker; it will not be available
2021-07-01 22:21:02,292 :: WARNING :: No data for HEMTT TFFT; it will not be available
2021-07-01 22:21:02,292 :: WARNING :: No data for IKARUS Bus; it will not be available
2021-07-01 22:21:02,295 :: WARNING :: No data for LAZ Bus; it will not be available
2021-07-01 22:21:02,295 :: WARNING :: No data for LiAZ Bus; it will not be available
2021-07-01 22:21:02,296 :: WARNING :: No data for Hummer; it will not be available
2021-07-01 22:21:02,297 :: WARNING :: No data for MAZ-6303; it will not be available
2021-07-01 22:21:02,297 :: WARNING :: No data for Predator GCS; it will not be available
2021-07-01 22:21:02,297 :: WARNING :: No data for Predator TrojanSpirit; it will not be available
2021-07-01 22:21:02,298 :: WARNING :: No data for Suidae; it will not be available
2021-07-01 22:21:02,298 :: WARNING :: No data for Tigr_233036; it will not be available
2021-07-01 22:21:02,299 :: WARNING :: No data for Trolley bus; it will not be available
2021-07-01 22:21:02,300 :: WARNING :: No data for Ural ATsP-6; it will not be available
2021-07-01 22:21:02,301 :: WARNING :: No data for Ural-375 PBU; it will not be available
2021-07-01 22:21:02,302 :: WARNING :: No data for VAZ Car; it will not be available
2021-07-01 22:21:02,302 :: WARNING :: No data for ZiL-131 APA-80; it will not be available
2021-07-01 22:21:02,303 :: WARNING :: No data for SKP-11; it will not be available
2021-07-01 22:21:02,303 :: WARNING :: No data for ZIL-131 KUNG; it will not be available
2021-07-01 22:21:02,303 :: WARNING :: No data for ZIL-4331; it will not be available
2021-07-01 22:21:02,304 :: WARNING :: No data for KrAZ6322; it will not be available
2021-07-01 22:21:02,304 :: WARNING :: No data for Electric locomotive; it will not be available
2021-07-01 22:21:02,305 :: WARNING :: No data for Locomotive; it will not be available
2021-07-01 22:21:02,307 :: WARNING :: No data for Coach cargo; it will not be available
2021-07-01 22:21:02,307 :: WARNING :: No data for Coach cargo open; it will not be available
2021-07-01 22:21:02,308 :: WARNING :: No data for Coach a tank blue; it will not be available
2021-07-01 22:21:02,308 :: WARNING :: No data for Coach a tank yellow; it will not be available
2021-07-01 22:21:02,309 :: WARNING :: No data for Coach a passenger; it will not be available
2021-07-01 22:21:02,309 :: WARNING :: No data for Coach a platform; it will not be available
2021-07-01 22:21:02,309 :: WARNING :: No data for Scud_B; it will not be available
2021-07-01 22:21:02,314 :: WARNING :: No data for RLS_19J6; it will not be available
2021-07-01 22:21:02,321 :: WARNING :: No data for generator_5i57; it will not be available
2021-07-01 22:21:02,322 :: WARNING :: No data for ATZ-5; it will not be available
2021-07-01 22:21:02,322 :: WARNING :: No data for AA8; it will not be available
2021-07-01 22:21:02,326 :: WARNING :: No data for ATZ-60_Maz; it will not be available
2021-07-01 22:21:02,326 :: WARNING :: No data for ZIL-135; it will not be available
2021-07-01 22:21:02,327 :: WARNING :: No data for TZ-22_KrAZ; it will not be available
2021-07-01 22:21:02,334 :: WARNING :: No data for hy_launcher; it will not be available
2021-07-01 22:21:02,334 :: WARNING :: No data for Silkworm_SR; it will not be available
2021-07-01 22:21:02,335 :: WARNING :: No data for ES44AH; it will not be available
2021-07-01 22:21:02,335 :: WARNING :: No data for Boxcartrinity; it will not be available
2021-07-01 22:21:02,337 :: WARNING :: No data for Tankcartrinity; it will not be available
2021-07-01 22:21:02,338 :: WARNING :: No data for Wellcarnsc; it will not be available
2021-07-01 22:21:02,366 :: WARNING :: No data for Horch_901_typ_40_kfz_21; it will not be available
2021-07-01 22:21:02,391 :: WARNING :: No data for SK_C_28_naval_gun; it will not be available
2021-07-01 22:21:02,392 :: WARNING :: No data for fire_control; it will not be available
2021-07-01 22:21:02,397 :: WARNING :: No data for v1_launcher; it will not be available
2021-07-01 22:21:02,400 :: WARNING :: No data for FuSe-65; it will not be available
2021-07-01 22:21:02,427 :: WARNING :: No data for DR_50Ton_Flat_Wagon; it will not be available
2021-07-01 22:21:02,427 :: WARNING :: No data for DRG_Class_86; it will not be available
2021-07-01 22:21:02,428 :: WARNING :: No data for German_covered_wagon_G10; it will not be available
2021-07-01 22:21:02,428 :: WARNING :: No data for German_tank_wagon; it will not be available
2021-07-01 22:21:02,429 :: WARNING :: No data for FieldHL; it will not be available
2021-07-01 22:21:02,429 :: WARNING :: No data for HARRIERH; it will not be available
2021-07-01 22:21:02,429 :: WARNING :: No data for SMOKESAM; it will not be available
2021-07-01 22:21:02,430 :: WARNING :: No data for SmokeD1; it will not be available
2021-07-01 22:21:02,431 :: WARNING :: No data for SmokeD3; it will not be available
2021-07-01 22:21:02,454 :: WARNING :: No data for SHERIDAN; it will not be available
2021-07-01 22:21:02,464 :: WARNING :: No data for T62; it will not be available
2021-07-01 22:21:02,465 :: WARNING :: No data for T64BV; it will not be available
2021-07-01 22:21:02,465 :: WARNING :: No data for T72M; it will not be available
2021-07-01 22:21:02,467 :: WARNING :: No data for KORNET; it will not be available
2021-07-01 22:21:02,489 :: WARNING :: No data for S_75M_Volhov_V759; it will not be available
2021-07-01 22:21:02,490 :: WARNING :: No data for HQ_2_Guideline_LN; it will not be available
2021-07-01 22:21:02,490 :: WARNING :: No data for 5p73 V-601P ln; it will not be available
2021-07-01 22:21:02,492 :: WARNING :: No data for SA-24 Igla-S manpad; it will not be available
2021-07-01 22:21:02,492 :: WARNING :: No data for SA-14 Strela-3 manpad; it will not be available
2021-07-01 22:21:02,494 :: WARNING :: No data for polyana-d4m1 cp; it will not be available
2021-07-01 22:21:02,494 :: WARNING :: No data for 34Ya6E Gazetchik E decoy; it will not be available
2021-07-01 22:22:27,794 :: INFO :: Generating AirWar (regular)
2021-07-01 22:22:27,844 :: INFO :: Generating flight: A-50
2021-07-01 22:22:27,844 :: INFO :: airgen: A-50 for 0 at Distance(distance_in_meters=3000) at 697
2021-07-01 22:22:27,868 :: INFO :: Generating flight: IL-78M
2021-07-01 22:22:27,868 :: INFO :: airgen: IL-78M for 0 at Distance(distance_in_meters=3000) at 697
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 279, in launch_mission
  File "game\game.py", line 276, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 299, in generate
  File "game\operation\operation.py", line 369, in _generate_air_units
  File "gen\aircraft.py", line 606, in generate_flights
  File "gen\aircraft.py", line 1136, in setup_flight_group
  File "gen\aircraft.py", line 1047, in configure_refueling
  File "gen\aircraft.py", line 361, in _setup_group
  File "gen\aircraft.py", line 584, in _setup_payload
AttributeError: 'NoneType' object has no attribute 'pylons'

[camp1.zip](https://github.com/dcs-liberation/dcs_liberation/files/6751550/camp1.zip)

**Comment by RndName** [comment]
Some investigation:
The Error was caused due to a None loadout of the IL-78M Refueling Flight

**Comment by DanAlbert** [comment]
It looks like the only way to get into this situation is to toggle the "custom loadout" checkbox on a flight that doesn't actually have any loadouts available. Skipping to the next turn repairs the save, but if I then open the IL-78M flight's loadout page, toggle "custom loadout" and then save the package I can no longer re-open the flight dialog.
