### ISSUE TITLE
Successful Anti-Convoy BAI Results in *Next* Turn Mission Generation Failing

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#1409]
**Describe the bug**

If in turn $n$, a mission against a ground convoy has some success (ground vehicles destroyed), then the subsequent round fails to generate a mission, with

```
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 289, in launch_mission
  File "game\game.py", line 277, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 303, in generate
  File "game\operation\operation.py", line 400, in _generate_ground_conflicts
KeyError: 1001
```

**To Reproduce**
1. Frag a mission against a convoy
2. In DCS: Destroy some vehicles in convoy
3. Back in Liberation, set up another mission(s), and click "Take Off"

**Expected behavior**

Successful mission generation.

**Additional information**

- This bug data was generated under build #2406
   - 20210628.02.liberation: Save file from previous (non-failing turn) for mission with convoy strike
   -  20210628.04.liberation: Save file for subsequent turn, that actually fails to generate DCS miz file
   - state.json: results from: "20210628.02.liberation"

[Saves.zip](https://github.com/dcs-liberation/dcs_liberation/files/6759680/Saves.zip)
[log.txt](https://github.com/dcs-liberation/dcs_liberation/files/6759683/log.txt)

- However, the last time I ran an anti-convoy BAI mission, I saw a very similar error. This was an earlier build, and unfortunately, I have lost the save file and mission file. The errior message was different, however:
```
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 279, in launch_mission
  File "game\game.py", line 276, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 297, in generate
  File "game\operation\operation.py", line 417, in _generate_transports
  File "gen\convoygen.py", line 31, in generate
  File "gen\convoygen.py", line 34, in generate_convoy
  File "gen\convoygen.py", line 63, in _create_mixed_unit_group
  File "dcs\mission.py", line 690, in vehicle_group
IndexError: list index out of range
```

**Comment by RndName** [comment]
danimal1306 from discord submitted this one:
```
2021-07-05 08:19:04,376 :: INFO :: Generating AirWar (regular)
2021-07-05 08:19:04,385 :: INFO :: Set up fire task for missile group.
2021-07-05 08:19:04,385 :: INFO :: Set up fire task for missile group.
2021-07-05 08:19:04,385 :: INFO :: Set up fire task for missile group.
2021-07-05 08:19:04,386 :: INFO :: Set up fire task for missile group.
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 279, in launch_mission
  File "game\game.py", line 276, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 297, in generate
  File "game\operation\operation.py", line 417, in _generate_transports
  File "gen\convoygen.py", line 31, in generate
  File "gen\convoygen.py", line 34, in generate_convoy
  File "gen\convoygen.py", line 63, in _create_mixed_unit_group
  File "dcs\mission.py", line 690, in vehicle_group
IndexError: list index out of range
```

The error here appears because the group_size is 0 (thats because its a mixed convoy of bradleys and hmmwv, where unit count of bradleys is 0). this will lead to an index error

[Full_Syria_1.zip](https://github.com/dcs-liberation/dcs_liberation/files/6766030/Full_Syria_1.zip)

**Comment by RndName** [comment]
The initial bug in this bug report here occured because the game identified a WIN (all runways of opfor are damaged / non operational). Thats why the Mission generation was not finished an no groundwar was generated for this round. The next "Takeoff" used the old generated groundwar from the previous round which lead to a keyerror.
This will be fixed with #978

**Comment by jeetsukumaran** [comment]
Interesting. Then maybe we can close this and open a new one based on danimal1306's report? As that seems to be an independent bug.

**Comment by RndName** [comment]
> 
> 
> Interesting. Then maybe we can close this and open a new one based on danimal1306's report? As that seems to be an independent bug.

Thanks to your attached save files that was very good to debug!

I already have a PR ready for the other issue. Would close this one here with it as you mentioned exactly the same bug in your additional information

**Comment by jeetsukumaran** [comment]
Thanks!

**Comment by DanAlbert** [comment]
Please keep issues open until the fixes are merged. It's how we know what still is missing from a release.
