### ISSUE TITLE
Index error: list index out of range ( fixed by passing turn, but should'nt be necessary.

### ISSUE THREAD

**Issue by danimal1306** [dcs-liberation/dcs_liberation#1412]
2021-07-05 08:19:04,376 :: INFO :: Generating AirWar (regular)
2021-07-05 08:19:04,385 :: INFO :: Set up fire task for missile group.
2021-07-05 08:19:04,385 :: INFO :: Set up fire task for missile group.
2021-07-05 08:19:04,385 :: INFO :: Set up fire task for missile group.
2021-07-05 08:19:04,386 :: INFO :: Set up fire task for missile group.
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 279, in launch_mission
  File "game\game.py", line 276, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 297, in generate
  File "game\operation\operation.py", line 417, in _generate_transports
  File "gen\convoygen.py", line 31, in generate
  File "gen\convoygen.py", line 34, in generate_convoy
  File "gen\convoygen.py", line 63, in _create_mixed_unit_group
  File "dcs\mission.py", line 690, in vehicle_group
IndexError: list index out of range
This happens when clicking take off
how to attach save game file?
danimal1306 — Today at 8:33 AM
Here's the save game
Attachment file type: unknown
Full_Syria_1.liberation
778.72 KB

**Comment by danimal1306** [comment]
I can't post he save game.  It's in discord under the same username

**Comment by DanAlbert** [comment]
> I can't post he save game. It's in discord under the same username

In the future, put the save file in a zip or just rename it to have a `.txt` extension.

**Comment by DanAlbert** [comment]
(https://github.com/dcs-liberation/dcs_liberation/issues/1409 had the log for this as well, and is now fixed)
