### ISSUE TITLE
Weapon CLSID used in more than one weapon type:

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#1436]
**Describe the bug**

In Turn 0, which clicking "Begin Campaign", we get:

```
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 148, in passTurn
  File "game\game.py", line 311, in pass_turn
  File "game\game.py", line 392, in initialize_turn
  File "game\game.py", line 406, in initialize_turn_for
  File "game\coalition.py", line 172, in initialize_turn
  File "game\coalition.py", line 191, in plan_missions
  File "game\commander\theatercommander.py", line 82, in plan_missions
  File "game\htn.py", line 82, in plan
  File "game\commander\tasks\primitive\barcap.py", line 17, in preconditions_met
  File "game\commander\tasks\packageplanningtask.py", line 52, in preconditions_met
  File "game\commander\tasks\packageplanningtask.py", line 90, in fulfill_mission
  File "game\commander\packagefulfiller.py", line 159, in plan_mission
  File "game\commander\packagefulfiller.py", line 82, in plan_flight
  File "game\commander\packagebuilder.py", line 56, in plan_flight
  File "gen\flights\flight.py", line 275, in __init__
  File "gen\flights\loadouts.py", line 135, in default_for
  File "gen\flights\loadouts.py", line 135, in <dictcomp>
  File "game\data\weapons.py", line 71, in with_clsid
  File "game\data\weapons.py", line 76, in _load_all
  File "game\data\weapons.py", line 185, in load_all
  File "game\data\weapons.py", line 160, in _each_weapon_group
  File "game\data\weapons.py", line 62, in register
ValueError: Weapon CLSID used in more than one weapon type: LAU-115 with 2 x LAU-127 AIM-120B AMRAAM - Active Rdr AAM and LAU-115 with 2 x LAU-127 AIM-120B AMRAAM - Active Rdr AAM
```

**To Reproduce**
1. Create new campaign (that probably includes factions that have the AIM-120B)
2. Click on 'Begin Campaign'
3. Observe error.

**Expected behavior**

We can begin the campaign.

**Additional information**

Build #2514. 
Campaigns tried: Battle of Abu Dhabi (with USN 2005 as player faction); Allied Sword (default factions).

[20210716-AlliedSword.liberation.txt](https://github.com/dcs-liberation/dcs_liberation/files/6828676/20210716-AlliedSword.liberation.txt)

**Comment by DanAlbert** [comment]
I fixed this at some point last night.
