### ISSUE TITLE
Cannot accept mission results: "Found killed ... but that airbase has none available" followed by "list.remove(x): x not in list"

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#1441]
**Describe the bug**

When trying to accept mission results, nothing happens.
Error is:
```
2021-07-19 02:58:50,441 :: INFO :: Finishing event AirWar
2021-07-19 02:58:50,442 :: INFO :: Committing mission results
2021-07-19 02:58:50,442 :: ERROR :: Found killed AV-8B Harrier II Night Attack from Ramat David but that airbase has none available.
2021-07-19 02:58:50,442 :: ERROR :: Found killed F/A-18C Hornet (Lot 20) from CVN-72 Abraham Lincoln but that airbase has none available.
2021-07-19 02:58:50,442 :: ERROR :: Found killed F/A-18C Hornet (Lot 20) from CVN-72 Abraham Lincoln but that airbase has none available.
2021-07-19 02:58:50,442 :: INFO :: Merkava Mk IV destroyed from Ramat David
2021-07-19 02:58:50,442 :: ERROR :: Found killed 2S1 Gvozdika from Damascus but that airbase has none available.
2021-07-19 02:58:50,442 :: ERROR :: Found killed T-55A from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed ZSU-57-2 'Sparka' from Damascus but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed ZSU-57-2 'Sparka' from Damascus but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed BMP-2 from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed BRDM-2 from Damascus but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed BMP-2 from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed MT-LB from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed MT-LB from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed T-55A from Damascus but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed BRDM-2 from Damascus but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed BMP-2 from Damascus but that airbase has none available.
2021-07-19 02:58:50,443 :: ERROR :: Found killed BTR-80 from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,444 :: ERROR :: Found killed T-55A from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,444 :: ERROR :: Found killed BTR-80 from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,444 :: ERROR :: Found killed BMP-1 from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,444 :: ERROR :: Found killed BRDM-2 from Damascus but that airbase has none available.
2021-07-19 02:58:50,444 :: ERROR :: Found killed BTR-80 from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,444 :: ERROR :: Found killed BMP-2 from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,444 :: ERROR :: Found killed MT-LB from Damascus but that airbase has none available.
2021-07-19 02:58:50,444 :: ERROR :: Found killed MT-LB from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,444 :: ERROR :: Found killed BTR-80 from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,445 :: ERROR :: Found killed BTR-80 from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,445 :: ERROR :: Found killed MT-LB from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,445 :: ERROR :: Found killed ZSU-57-2 'Sparka' from Damascus but that airbase has none available.
2021-07-19 02:58:50,445 :: ERROR :: Found killed BRDM-2 from Damascus but that airbase has none available.
2021-07-19 02:58:50,445 :: ERROR :: Found killed ZSU-57-2 'Sparka' from Damascus but that airbase has none available.
2021-07-19 02:58:50,445 :: ERROR :: Found killed BTR-80 from Damascus but that airbase has none available.
2021-07-19 02:58:50,445 :: ERROR :: Found killed T-55A from Damascus but that airbase has none available.
2021-07-19 02:58:50,445 :: ERROR :: Found killed BTR-80 from Damascus but that airbase has none available.
2021-07-19 02:58:50,445 :: ERROR :: Found killed 2S1 Gvozdika from Damascus but that airbase has none available.
2021-07-19 02:58:50,445 :: ERROR :: Found killed T-90A from Damascus but that airbase has none available.
2021-07-19 02:58:50,446 :: ERROR :: Found killed MT-LB from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,446 :: ERROR :: Found killed T-90A from Beirut-Rafic Hariri but that airbase has none available.
2021-07-19 02:58:50,446 :: ERROR :: Found killed T-55A from Beirut-Rafic Hariri but that airbase has none available.
Traceback (most recent call last):
  File "windows\QWaitingForMissionResultWindow.py", line 210, in process_debriefing
  File "game\game.py", line 219, in finish_event
  File "game\event\event.py", line 275, in commit
  File "game\event\event.py", line 224, in commit_ground_object_losses
ValueError: list.remove(x): x not in list
```

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- DCS Liberation save file (the `.liberation` file you save from the DCS Liberation window). By default these are located in your DCS saved games directory (`%USERPROFILE%/Saved Games/DCS`).
- The generated mission file (the `.miz` file that you load in DCS to play the turn). By default these are located in your missions directory (`%USERPROFILE%/Saved Games/DCS/Missions`).
- A tacview track file, especially when demonstrating an issue with AI behavior. By default these are located in your Tacview tracks directory (`%USERPROFILE%/Documents/Tacview`).
- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: Preview Build #2541

Save file, mission file, etc. attached: [20210719.zip](https://github.com/dcs-liberation/dcs_liberation/files/6839993/20210719.zip)

**Comment by RndName** [comment]
@jeetsukumaran do you have an state.json file for this one as well? Would be great to have a closer look into this one :)

**Comment by jeetsukumaran** [comment]
Sorry! Missed that. Attached here:
[state.json.txt](https://github.com/dcs-liberation/dcs_liberation/files/6844890/state.json.txt)

**Comment by RndName** [comment]
I can accept the mission results without any warnings or even errors. Can you ensure that you used the correct save for the correct state.json file and for example not a save from one turn before to submit the results?.
The error itself you have here shows that it tries to delete a unit which does not exist in the specific group so thats why my guess would be that its the wrong save file from another turn.

**Comment by jeetsukumaran** [comment]
Unfortunately, that's all I have. Closing this for now. Will reopen if I dig up more files or if  I can replicate reliably.
