### ISSUE TITLE
Nothing happens when I press "Take off"

### ISSUE THREAD

**Issue by currenthill** [dcs-liberation/dcs_liberation#1447]
**Describe the bug**
When trying to launch a mission (TAKE OFF button) nothing happens.

**To Reproduce**
1. I installed Liberation 4.0.0 from scratch (no leftovers from earlier versions etc)
2. I created a campaign (Caucasus - Northern Russia)
3. Changed Bluefor Modern to Sweden 2002 and Russia to 1990
4. I enabled the Gripen mod
5. I setup a few packages
6. I tried to launch the first mission
7. The error log shows an error (see attached file errorlog.txt)

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 279, in launch_mission
  File "game\game.py", line 276, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 299, in generate
  File "game\operation\operation.py", line 374, in _generate_air_units
  File "gen\aircraft.py", line 604, in generate_flights
  File "gen\aircraft.py", line 759, in generate_planned_flight
  File "gen\aircraft.py", line 501, in _generate_inflight
  File "dcs\mission.py", line 1205, in flight_group
  File "dcs\mission.py", line 1061, in flight_group_inflight
  File "dcs\mission.py", line 997, in _flying_group_inflight
  File "dcs\unitgroup.py", line 442, in load_task_default_loadout
  File "dcs\flyingunit.py", line 77, in load_pylon
RuntimeError: Plane MiG-31 has no pylon 8.
```

**Expected behavior**
I was expecting to get the text box indicating that I should start DCS etc.

**Additional information**
Attached Errorlog.txt and Liberation mission file.

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: 4.0.0

[Liberation bug report.zip](https://github.com/dcs-liberation/dcs_liberation/files/6857485/Liberation.bug.report.zip)

**Comment by bgreman** [comment]
Issue was not able to be duplicated on a fresh install.  After investigation, user confirmed that there were invalid Mig-31 loadouts present in user's Saved Games / DCS / ME /unitpayloads dir.
