### ISSUE TITLE
Mission not starting

### ISSUE THREAD

**Issue by Tinchus2009** [dcs-liberation/dcs_liberation#1452]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
I finished a mission, inmediatly I panned the next on  and it just wont start. I saved  the mission, closed DCS closed liberation. Restarted DCS, then started liberation and still wont start the new mission. I see the same errors :

2021-07-22 20:50:17,897 :: INFO :: DCS Liberation 4.0.0
2021-07-22 20:50:17,897 :: DEBUG :: Python version 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
2021-07-22 20:50:18,078 :: ERROR :: Using default theme because liberation_theme.json does not exist
2021-07-22 20:50:18,078 :: INFO :: Loading stylesheet: style-dcs.css
2021-07-22 20:50:18,079 :: DEBUG :: Loading Liberation preferences from C:\Users\User\AppData\Local\DCSLiberation\liberation_preferences.json
2021-07-22 20:50:18,079 :: INFO :: Using C:\Users\User\Saved Games\DCS.openbeta as 'Saved Game Folder'
2021-07-22 20:50:18,079 :: INFO :: Using D:/Eagle Dynamics/DCS World OpenBeta as 'DCS installation folder'
C:/Users/User/Saved Games/DCS.openbeta/Liberation/Saves/camp1.liberation
2021-07-22 20:50:20,318 :: INFO :: Loading last saved game : C:/Users/User/Saved Games/DCS.openbeta/Liberation/Saves/camp1.liberation
2021-07-22 20:50:20,331 :: WARNING :: No data for Ka-27; it will not be available
2021-07-22 20:50:20,335 :: WARNING :: No data for SH-3W; it will not be available
2021-07-22 20:50:20,369 :: WARNING :: No data for F/A-18A; it will not be available
2021-07-22 20:50:20,369 :: WARNING :: No data for F/A-18C; it will not be available
2021-07-22 20:50:20,369 :: WARNING :: No data for F-14A; it will not be available
2021-07-22 20:50:20,386 :: WARNING :: No data for Su-25TM; it will not be available
2021-07-22 20:50:20,451 :: WARNING :: No data for F-16C bl.50; it will not be available
2021-07-22 20:50:20,451 :: WARNING :: No data for F-16C bl.52d; it will not be available
2021-07-22 20:50:20,452 :: WARNING :: No data for F-16A MLU; it will not be available
2021-07-22 20:50:20,512 :: WARNING :: No data for C-101EB; it will not be available
2021-07-22 20:50:20,522 :: WARNING :: No data for Christen Eagle II; it will not be available
2021-07-22 20:50:20,526 :: WARNING :: No data for F-5E; it will not be available
2021-07-22 20:50:20,544 :: WARNING :: No data for Hawk; it will not be available
2021-07-22 20:50:20,546 :: WARNING :: No data for L-39C; it will not be available
2021-07-22 20:50:20,566 :: WARNING :: No data for Yak-52; it will not be available
2021-07-22 20:50:20,571 :: WARNING :: No data for TF-51D; it will not be available
2021-07-22 20:50:20,807 :: INFO :: Reading plugins list from resources\plugins\plugins.json
2021-07-22 20:50:20,812 :: INFO :: Loading plugin base from resources\plugins\base\plugin.json
2021-07-22 20:50:20,813 :: INFO :: Loading plugin jtacautolase from resources\plugins\jtacautolase\plugin.json
2021-07-22 20:50:20,815 :: INFO :: Loading plugin skynetiads from resources\plugins\skynetiads\plugin.json
2021-07-22 20:50:20,816 :: INFO :: Loading plugin ewrs from resources\plugins\ewrs\plugin.json
2021-07-22 20:50:20,817 :: INFO :: Loading plugin herculescargo from resources\plugins\herculescargo\plugin.json
2021-07-22 20:50:20,818 :: INFO :: Loading plugin splashdamage from resources\plugins\splashdamage\plugin.json
2021-07-22 20:50:20,821 :: INFO :: Loading plugin lotatc from resources\plugins\lotatc\plugin.json
2021-07-22 20:50:20,875 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.address`.
2021-07-22 20:50:20,878 :: DEBUG :: Provider `faker.providers.address` has been localized to `ru_RU`.
2021-07-22 20:50:20,885 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.automotive`.
2021-07-22 20:50:20,886 :: DEBUG :: Provider `faker.providers.automotive` has been localized to `ru_RU`.
2021-07-22 20:50:20,887 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.bank`.
2021-07-22 20:50:20,889 :: DEBUG :: Provider `faker.providers.bank` has been localized to `ru_RU`.
2021-07-22 20:50:20,890 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.barcode`.
2021-07-22 20:50:20,893 :: DEBUG :: Specified locale `ru_RU` is not available for provider `faker.providers.barcode`. Locale reset to `en_US` for this provider.
2021-07-22 20:50:20,895 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.color`.
2021-07-22 20:50:20,896 :: DEBUG :: Provider `faker.providers.color` has been localized to `ru_RU`.
2021-07-22 20:50:20,897 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.company`.
2021-07-22 20:50:20,898 :: DEBUG :: Provider `faker.providers.company` has been localized to `ru_RU`.
2021-07-22 20:50:20,900 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.credit_card`.
2021-07-22 20:50:20,901 :: DEBUG :: Provider `faker.providers.credit_card` has been localized to `ru_RU`.
2021-07-22 20:50:20,902 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.currency`.
2021-07-22 20:50:20,905 :: DEBUG :: Provider `faker.providers.currency` has been localized to `ru_RU`.
2021-07-22 20:50:20,908 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.date_time`.
2021-07-22 20:50:20,909 :: DEBUG :: Provider `faker.providers.date_time` has been localized to `ru_RU`.
2021-07-22 20:50:20,911 :: DEBUG :: Provider `faker.providers.file` does not feature localization. Specified locale `ru_RU` is not utilized for this provider.
2021-07-22 20:50:20,911 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.geo`.
2021-07-22 20:50:20,912 :: DEBUG :: Specified locale `ru_RU` is not available for provider `faker.providers.geo`. Locale reset to `en_US` for this provider.
2021-07-22 20:50:20,912 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.internet`.
2021-07-22 20:50:20,914 :: DEBUG :: Provider `faker.providers.internet` has been localized to `ru_RU`.
2021-07-22 20:50:20,916 :: DEBUG :: Provider `faker.providers.isbn` does not feature localization. Specified locale `ru_RU` is not utilized for this provider.
2021-07-22 20:50:20,916 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.job`.
2021-07-22 20:50:20,917 :: DEBUG :: Provider `faker.providers.job` has been localized to `ru_RU`.
2021-07-22 20:50:20,920 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.lorem`.
2021-07-22 20:50:20,921 :: DEBUG :: Provider `faker.providers.lorem` has been localized to `ru_RU`.
2021-07-22 20:50:20,922 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.misc`.
2021-07-22 20:50:20,923 :: DEBUG :: Specified locale `ru_RU` is not available for provider `faker.providers.misc`. Locale reset to `en_US` for this provider.
2021-07-22 20:50:20,924 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.person`.
2021-07-22 20:50:20,927 :: DEBUG :: Provider `faker.providers.person` has been localized to `ru_RU`.
2021-07-22 20:50:20,927 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.phone_number`.
2021-07-22 20:50:20,930 :: DEBUG :: Provider `faker.providers.phone_number` has been localized to `ru_RU`.
2021-07-22 20:50:20,931 :: DEBUG :: Provider `faker.providers.profile` does not feature localization. Specified locale `ru_RU` is not utilized for this provider.
2021-07-22 20:50:20,931 :: DEBUG :: Provider `faker.providers.python` does not feature localization. Specified locale `ru_RU` is not utilized for this provider.
2021-07-22 20:50:20,931 :: DEBUG :: Looking for locale `ru_RU` in provider `faker.providers.ssn`.
2021-07-22 20:50:20,935 :: DEBUG :: Provider `faker.providers.ssn` has been localized to `ru_RU`.
2021-07-22 20:50:20,937 :: DEBUG :: Provider `faker.providers.user_agent` does not feature localization. Specified locale `ru_RU` is not utilized for this provider.
2021-07-22 20:50:20,937 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.address`.
2021-07-22 20:50:20,939 :: DEBUG :: Provider `faker.providers.address` has been localized to `en_US`.
2021-07-22 20:50:20,942 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.automotive`.
2021-07-22 20:50:20,943 :: DEBUG :: Provider `faker.providers.automotive` has been localized to `en_US`.
2021-07-22 20:50:20,944 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.bank`.
2021-07-22 20:50:20,946 :: DEBUG :: Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider.
2021-07-22 20:50:20,947 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.barcode`.
2021-07-22 20:50:20,947 :: DEBUG :: Provider `faker.providers.barcode` has been localized to `en_US`.
2021-07-22 20:50:20,948 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.color`.
2021-07-22 20:50:20,949 :: DEBUG :: Provider `faker.providers.color` has been localized to `en_US`.
2021-07-22 20:50:20,951 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.company`.
2021-07-22 20:50:20,953 :: DEBUG :: Provider `faker.providers.company` has been localized to `en_US`.
2021-07-22 20:50:20,954 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.credit_card`.
2021-07-22 20:50:20,955 :: DEBUG :: Provider `faker.providers.credit_card` has been localized to `en_US`.
2021-07-22 20:50:20,955 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.currency`.
2021-07-22 20:50:20,957 :: DEBUG :: Provider `faker.providers.currency` has been localized to `en_US`.
2021-07-22 20:50:20,958 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.date_time`.
2021-07-22 20:50:20,959 :: DEBUG :: Provider `faker.providers.date_time` has been localized to `en_US`.
2021-07-22 20:50:20,961 :: DEBUG :: Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-07-22 20:50:20,961 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.geo`.
2021-07-22 20:50:20,962 :: DEBUG :: Provider `faker.providers.geo` has been localized to `en_US`.
2021-07-22 20:50:20,962 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.internet`.
2021-07-22 20:50:20,964 :: DEBUG :: Provider `faker.providers.internet` has been localized to `en_US`.
2021-07-22 20:50:20,965 :: DEBUG :: Provider `faker.providers.isbn` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-07-22 20:50:20,966 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.job`.
2021-07-22 20:50:20,968 :: DEBUG :: Provider `faker.providers.job` has been localized to `en_US`.
2021-07-22 20:50:20,969 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.lorem`.
2021-07-22 20:50:20,970 :: DEBUG :: Provider `faker.providers.lorem` has been localized to `en_US`.
2021-07-22 20:50:20,972 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.misc`.
2021-07-22 20:50:20,972 :: DEBUG :: Provider `faker.providers.misc` has been localized to `en_US`.
2021-07-22 20:50:20,973 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.person`.
2021-07-22 20:50:20,976 :: DEBUG :: Provider `faker.providers.person` has been localized to `en_US`.
2021-07-22 20:50:20,978 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.phone_number`.
2021-07-22 20:50:20,981 :: DEBUG :: Provider `faker.providers.phone_number` has been localized to `en_US`.
2021-07-22 20:50:20,982 :: DEBUG :: Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-07-22 20:50:20,983 :: DEBUG :: Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-07-22 20:50:20,985 :: DEBUG :: Looking for locale `en_US` in provider `faker.providers.ssn`.
2021-07-22 20:50:20,987 :: DEBUG :: Provider `faker.providers.ssn` has been localized to `en_US`.
2021-07-22 20:50:20,988 :: DEBUG :: Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider.
2021-07-22 20:50:20,990 :: INFO :: On Game generated
2021-07-22 20:50:21,214 :: DEBUG :: Map reset took 0:00:00.064340
2021-07-22 20:50:21,876 :: WARNING :: No data for Bunker; it will not be available
2021-07-22 20:50:21,880 :: WARNING :: No data for Sandbox; it will not be available
2021-07-22 20:50:21,887 :: WARNING :: No data for MLRS FDDM; it will not be available
2021-07-22 20:50:21,952 :: WARNING :: No data for Igla manpad INS; it will not be available
2021-07-22 20:50:21,964 :: WARNING :: No data for house1arm; it will not be available
2021-07-22 20:50:21,964 :: WARNING :: No data for house2arm; it will not be available
2021-07-22 20:50:21,965 :: WARNING :: No data for outpost_road; it will not be available
2021-07-22 20:50:21,965 :: WARNING :: No data for outpost; it will not be available
2021-07-22 20:50:21,965 :: WARNING :: No data for houseA_arm; it will not be available
2021-07-22 20:50:21,966 :: WARNING :: No data for TACAN_beacon; it will not be available
2021-07-22 20:50:21,991 :: WARNING :: No data for Ural-4320 APA-5D; it will not be available
2021-07-22 20:50:21,991 :: WARNING :: No data for ATMZ-5; it will not be available
2021-07-22 20:50:21,992 :: WARNING :: No data for ATZ-10; it will not be available
2021-07-22 20:50:21,998 :: WARNING :: No data for M978 HEMTT Tanker; it will not be available
2021-07-22 20:50:21,998 :: WARNING :: No data for HEMTT TFFT; it will not be available
2021-07-22 20:50:21,999 :: WARNING :: No data for IKARUS Bus; it will not be available
2021-07-22 20:50:22,000 :: WARNING :: No data for LAZ Bus; it will not be available
2021-07-22 20:50:22,001 :: WARNING :: No data for LiAZ Bus; it will not be available
2021-07-22 20:50:22,001 :: WARNING :: No data for Hummer; it will not be available
2021-07-22 20:50:22,003 :: WARNING :: No data for MAZ-6303; it will not be available
2021-07-22 20:50:22,003 :: WARNING :: No data for Predator GCS; it will not be available
2021-07-22 20:50:22,004 :: WARNING :: No data for Predator TrojanSpirit; it will not be available
2021-07-22 20:50:22,005 :: WARNING :: No data for Suidae; it will not be available
2021-07-22 20:50:22,006 :: WARNING :: No data for Tigr_233036; it will not be available
2021-07-22 20:50:22,008 :: WARNING :: No data for Trolley bus; it will not be available
2021-07-22 20:50:22,010 :: WARNING :: No data for Ural ATsP-6; it will not be available
2021-07-22 20:50:22,012 :: WARNING :: No data for Ural-375 PBU; it will not be available
2021-07-22 20:50:22,013 :: WARNING :: No data for VAZ Car; it will not be available
2021-07-22 20:50:22,013 :: WARNING :: No data for ZiL-131 APA-80; it will not be available
2021-07-22 20:50:22,013 :: WARNING :: No data for SKP-11; it will not be available
2021-07-22 20:50:22,014 :: WARNING :: No data for ZIL-131 KUNG; it will not be available
2021-07-22 20:50:22,014 :: WARNING :: No data for ZIL-4331; it will not be available
2021-07-22 20:50:22,015 :: WARNING :: No data for KrAZ6322; it will not be available
2021-07-22 20:50:22,015 :: WARNING :: No data for Electric locomotive; it will not be available
2021-07-22 20:50:22,015 :: WARNING :: No data for Locomotive; it will not be available
2021-07-22 20:50:22,016 :: WARNING :: No data for Coach cargo; it will not be available
2021-07-22 20:50:22,016 :: WARNING :: No data for Coach cargo open; it will not be available
2021-07-22 20:50:22,017 :: WARNING :: No data for Coach a tank blue; it will not be available
2021-07-22 20:50:22,017 :: WARNING :: No data for Coach a tank yellow; it will not be available
2021-07-22 20:50:22,017 :: WARNING :: No data for Coach a passenger; it will not be available
2021-07-22 20:50:22,018 :: WARNING :: No data for Coach a platform; it will not be available
2021-07-22 20:50:22,018 :: WARNING :: No data for Scud_B; it will not be available
2021-07-22 20:50:22,025 :: WARNING :: No data for RLS_19J6; it will not be available
2021-07-22 20:50:22,033 :: WARNING :: No data for generator_5i57; it will not be available
2021-07-22 20:50:22,033 :: WARNING :: No data for ATZ-5; it will not be available
2021-07-22 20:50:22,034 :: WARNING :: No data for AA8; it will not be available
2021-07-22 20:50:22,037 :: WARNING :: No data for ATZ-60_Maz; it will not be available
2021-07-22 20:50:22,037 :: WARNING :: No data for ZIL-135; it will not be available
2021-07-22 20:50:22,037 :: WARNING :: No data for TZ-22_KrAZ; it will not be available
2021-07-22 20:50:22,048 :: WARNING :: No data for hy_launcher; it will not be available
2021-07-22 20:50:22,049 :: WARNING :: No data for Silkworm_SR; it will not be available
2021-07-22 20:50:22,049 :: WARNING :: No data for ES44AH; it will not be available
2021-07-22 20:50:22,050 :: WARNING :: No data for Boxcartrinity; it will not be available
2021-07-22 20:50:22,050 :: WARNING :: No data for Tankcartrinity; it will not be available
2021-07-22 20:50:22,050 :: WARNING :: No data for Wellcarnsc; it will not be available
2021-07-22 20:50:22,080 :: WARNING :: No data for Horch_901_typ_40_kfz_21; it will not be available
2021-07-22 20:50:22,108 :: WARNING :: No data for SK_C_28_naval_gun; it will not be available
2021-07-22 20:50:22,108 :: WARNING :: No data for fire_control; it will not be available
2021-07-22 20:50:22,115 :: WARNING :: No data for v1_launcher; it will not be available
2021-07-22 20:50:22,117 :: WARNING :: No data for FuSe-65; it will not be available
2021-07-22 20:50:22,148 :: WARNING :: No data for DR_50Ton_Flat_Wagon; it will not be available
2021-07-22 20:50:22,148 :: WARNING :: No data for DRG_Class_86; it will not be available
2021-07-22 20:50:22,149 :: WARNING :: No data for German_covered_wagon_G10; it will not be available
2021-07-22 20:50:22,152 :: WARNING :: No data for German_tank_wagon; it will not be available
2021-07-22 20:50:22,152 :: WARNING :: No data for FieldHL; it will not be available
2021-07-22 20:50:22,153 :: WARNING :: No data for HARRIERH; it will not be available
2021-07-22 20:50:22,153 :: WARNING :: No data for SMOKESAM; it will not be available
2021-07-22 20:50:22,154 :: WARNING :: No data for SmokeD1; it will not be available
2021-07-22 20:50:22,154 :: WARNING :: No data for SmokeD3; it will not be available
2021-07-22 20:50:22,178 :: WARNING :: No data for SHERIDAN; it will not be available
2021-07-22 20:50:22,190 :: WARNING :: No data for T62; it will not be available
2021-07-22 20:50:22,191 :: WARNING :: No data for T64BV; it will not be available
2021-07-22 20:50:22,192 :: WARNING :: No data for T72M; it will not be available
2021-07-22 20:50:22,193 :: WARNING :: No data for KORNET; it will not be available
2021-07-22 20:50:22,218 :: WARNING :: No data for S_75M_Volhov_V759; it will not be available
2021-07-22 20:50:22,218 :: WARNING :: No data for HQ_2_Guideline_LN; it will not be available
2021-07-22 20:50:22,219 :: WARNING :: No data for 5p73 V-601P ln; it will not be available
2021-07-22 20:50:22,221 :: WARNING :: No data for SA-24 Igla-S manpad; it will not be available
2021-07-22 20:50:22,225 :: WARNING :: No data for SA-14 Strela-3 manpad; it will not be available
2021-07-22 20:50:22,225 :: WARNING :: No data for polyana-d4m1 cp; it will not be available
2021-07-22 20:50:22,226 :: WARNING :: No data for 34Ya6E Gazetchik E decoy; it will not be available
2021-07-22 20:50:27,793 :: INFO :: Generating AirWar (regular)
2021-07-22 20:50:27,801 :: WARNING :: Found empty group in Early Warning Radar
2021-07-22 20:50:27,807 :: WARNING :: Found empty group in Early Warning Radar
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 279, in launch_mission
  File "game\game.py", line 276, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 297, in generate
  File "game\operation\operation.py", line 417, in _generate_transports
  File "gen\convoygen.py", line 31, in generate
  File "gen\convoygen.py", line 34, in generate_convoy
  File "gen\convoygen.py", line 63, in _create_mixed_unit_group
  File "dcs\mission.py", line 690, in vehicle_group
IndexError: list index out of range
2021-07-22 20:52:36,010 :: WARNING :: ewr not in REWARDS
2021-07-22 20:52:39,441 :: WARNING :: ewr not in REWARDS
2021-07-22 20:52:42,093 :: WARNING :: ewr not in REWARDS
2021-07-22 20:52:45,620 :: WARNING :: ewr not in REWARDS
2021-07-22 20:52:53,204 :: WARNING :: ewr not in REWARDS

**To Reproduce**

**Expected behavior**

**Additional information**

[tmpsave.zip](https://github.com/dcs-liberation/dcs_liberation/files/6865977/tmpsave.zip)

**Version information (please complete the following information):**
 - DCS Liberation [e.g. 2.3.1]: 4.0

**Additional context**

**Comment by RndName** [comment]
#1409

**Comment by RndName** [comment]
this looks exactly like the thing i fixed with #1411. I am going to verify it

**Comment by RndName** [comment]
@Tinchus2009 can you provide the correct save file for this one: `camp1.liberation`. The one you attached can not be loaded at all

**Comment by Tinchus2009** [comment]
[campana1.zip](https://github.com/dcs-liberation/dcs_liberation/files/6874756/campana1.zip)
Here you have. Chande fro .rar. zip extension

**Comment by Tinchus2009** [comment]
readin about #1411, then seems to be related because ths mission probably would have ended with a WIN on my side, because I guess one the flight acomplish to destroy the last runaway of the enemy

**Comment by RndName** [comment]
> 
> 
> [campana1.zip](https://github.com/dcs-liberation/dcs_liberation/files/6874756/campana1.zip)
> Here you have. Chande fro .rar. zip extension

again i can not open this one as its invalid for DCS LIberation V4- This looks like an V3 save file which is not compatible to the V4 at all. So i can say your error above was not generated with this campaign you attached.

**Comment by Tinchus2009** [comment]
I dont know what to say. I dont have liberation V3 installed. Im using the V4.0.0 acording to what I read in the cmd screen when I start it. And on top of the windows it also says: DCS Liberation - V4.0.0

**Comment by Tinchus2009** [comment]
Still, y hae tried another campaign, and the same problem arises. Follow the reproduction steps I posted above, I have been able to reproduce that error choosing every campaign I tried (I confess I tried with on 4  different ones)

**Comment by bgreman** [comment]
I also cannot load that save in either 4.0.0 or the latest 4.x preview build.  It complains about the M1A2, and I'm wondering what faction file is being used?

**Comment by DanAlbert** [comment]
@Tinchus2009  Since no one else is able to run your saved games in 4.x for some reason, can you try with https://github.com/dcs-liberation/dcs_liberation/actions/runs/1085947977?

**Comment by DanAlbert** [comment]
No response. Nothing we can do without feedback. Closing until we get the info we need.

**Comment by RndName** [comment]
#1553
