### ISSUE TITLE
Unable to start missions when enemy is using WW2 Germany Equipment.

### ISSUE THREAD

**Issue by dankwilliams** [dcs-liberation/dcs_liberation#1519]
**Describe the bug**
Missions do not start when enemy is using WW2 german equipment. I think it has something to do with anti air locations because it also happens with 1950 North Korea. This same setup *will* generate missions when the map is switched for Syria full.

**To Reproduce**
1. Launch Liberation
2. Start new game on Multi-part Georgia, enemy faction 1950 North Korea
3. Proceed to Turn 1 as normal and click Take Off
4. Observe nothing happens, error appears in log.

Rate: 100%

**Expected behavior**
Mission starts like normal.

**Additional information**
Error from the log:
QLayout: Attempting to add QLayout "" to QLoadoutEditor "", which already has a layout
2021-08-08 00:23:23,642 :: INFO :: Generating AirWar (regular)
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 289, in launch_mission
  File "game\game.py", line 270, in initiate_event
  File "game\event\event.py", line 64, in generate
  File "game\operation\operation.py", line 287, in generate
  File "game\operation\operation.py", line 248, in _generate_ground_units
  File "gen\groundobjectsgen.py", line 701, in generate
  File "gen\groundobjectsgen.py", line 127, in generate
  File "gen\groundobjectsgen.py", line 145, in _register_unit_group
  File "game\unitmap.py", line 132, in add_ground_object_units
RuntimeError: Duplicate TGO unit: aa|3|4|BLITZ#1

**Version information (please complete the following information):**
 - DCS Liberation [4.1 preview #2710]:

**Comment by Starfire13** [comment]
Possibly could be fixed the same way as this, which was a fix implemented for flak sites that were generating this same error. https://github.com/dcs-liberation/dcs_liberation/actions/runs/760799564
