### ISSUE TITLE
Error When Pressing Take-Off

### ISSUE THREAD

**Issue by elblayko** [dcs-liberation/dcs_liberation#1522]
**Describe the bug**
When misison planning has been completed and I want to start playing, nothing happens when the green take-off button is pressed.

**To Reproduce**
1.  Open a mission within DCS Liberation. 
2.  Click the Take-Off button.

**Expected behavior**
Able to begin the mission.

**Additional information**

```
2021-08-08 16:22:11,777 :: INFO :: Generating AirWar (regular)
2021-08-08 16:22:11,782 :: INFO :: Set up fire task for missile group.
2021-08-08 16:22:11,782 :: INFO :: Set up fire task for missile group.
2021-08-08 16:22:11,783 :: INFO :: Set up fire task for missile group.
2021-08-08 16:22:11,786 :: INFO :: Set up fire task for missile group.
2021-08-08 16:22:11,789 :: INFO :: Set up fire task for missile group.
Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 279, in launch_mission
  File "game\game.py", line 276, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 299, in generate
  File "game\operation\operation.py", line 354, in _generate_air_units
  File "gen\airsupportgen.py", line 124, in generate
  File "dcs\mission.py", line 1309, in refuel_flight
  File "dcs\mission.py", line 1046, in flight_group_inflight
AttributeError: 'AircraftType' object has no attribute 'helicopter'
```

**Version information (please complete the following information):**
 - DCS Liberation 4.0.0:

.liberation file:
https://drive.google.com/file/d/1vQUb-rr7PX4YUJ1_q-YRwcaBqMJaVLZT/view

**Comment by elblayko** [comment]
I've discovered that the "Spawn invulnerable, always available" AEW&C/Tanker options cause this.

**Comment by DanAlbert** [comment]
You're using the old version.
