### ISSUE TITLE
Cannot create a new campaign on any map when user has a Marianas campaign installed.

### ISSUE THREAD

**Issue by dankwilliams** [dcs-liberation/dcs_liberation#1524]
**Describe the bug**
When I put my Marianas campaign in the campaigns folder, I am prevented from starting any new game.

**To Reproduce**
1. Grab the guam campaign from previous versions and update it to 8.0 (or try out the attached campaign)
2. Put the campaign files in the resources/campaign folder
3. Launch Liberation, hit New Game
4. See error and nothing happens

**Expected behavior**
Campaign select window pops up.

**Additional information**
Traceback (most recent call last):
  File "windows\QLiberationWindow.py", line 238, in newGame
  File "windows\newgame\QNewGameWizard.py", line 47, in init
  File "windows\newgame\QNewGameWizard.py", line 299, in init
  File "windows\newgame\QCampaignList.py", line 140, in init
  File "windows\newgame\QCampaignList.py", line 152, in setup_content
  File "windows\newgame\QCampaignList.py", line 120, in init
KeyError: 'Terrain_MarianaIslands'

Marianas Campaign:
[island_insurrection.zip](https://github.com/dcs-liberation/dcs_liberation/files/6951628/island_insurrection.zip)

**Version information (please complete the following information):**
 - DCS Liberation [4.1 Release]:

**Comment by magwo** [comment]
Fixed in 4.1.1
