### ISSUE TITLE
JF-17 Loadout Error prevents Altering generated Flights 'DIS_GBU_12_DUAL'

### ISSUE THREAD

**Issue by dasrehzockt** [dcs-liberation/dcs_liberation#1724]
Generated JF-17 Flights cannot be altered. When trying to open the Menu it pops the following Error:

```
'DIS_GBU_12_DUAL'

Traceback (most recent call last):
  File "widgets\ato.py", line 119, in on_double_click
  File "widgets\ato.py", line 124, in edit_flight
  File "dialogs.py", line 57, in open_edit_flight_dialog
  File "windows\mission\QEditFlightDialog.py", line 33, in __init__
  File "windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
  File "gen\flights\loadouts.py", line 120, in iter_for
  File "gen\flights\loadouts.py", line 120, in <dictcomp>
  File "game\data\weapons.py", line 73, in with_clsid
KeyError: 'DIS_GBU_12_DUAL'
```

The menu does not open.

**Comment by DanAlbert** [comment]
Please follow the template. We can't investigate without more information.

**Comment by dasrehzockt** [comment]
no problem, here you go:

**Describe the bug**
The dialogue to alter generated JF-17 flights does not open. The following Error appears:


```
'DIS_GBU_12_DUAL'

Traceback (most recent call last):
  File "widgets\ato.py", line 119, in on_double_click
  File "widgets\ato.py", line 124, in edit_flight
  File "dialogs.py", line 57, in open_edit_flight_dialog
  File "windows\mission\QEditFlightDialog.py", line 33, in __init__
  File "windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
  File "gen\flights\loadouts.py", line 120, in iter_for
  File "gen\flights\loadouts.py", line 120, in <dictcomp>
  File "game\data\weapons.py", line 73, in with_clsid
KeyError: 'DIS_GBU_12_DUAL'

```

**To Reproduce**
Steps to reproduce the behavior:
1. Double click auto generated JF-17 flight.

**Expected behavior**
the window opens.

**Additional information**
i don't know how to attach my save since only images are accepted. but this does not seem to be affected by a savegame, it is consistent with any campaign i am starting, independet of what faction or map i am using. 
This bug prevents me from making certain flights player/AI controlled or from changing loadouts.

**Version information (please complete the following information):**
v5.0.0-3022

if you need further information i am happy to get you whatever you need!
