### ISSUE TITLE
disable "invert" button in NGW if campaign doesn't support it

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#1752]
**Describe the bug**
First reported by ThatOneGuyC6 on Discord. Operation Dynamo generates the following error when inverted:

Traceback (most recent call last):
  File "windows\QLiberationWindow.py", line 318, in setGame
  File "widgets\map\QLiberationMap.py", line 58, in set_game
  File "widgets\map\mapmodel.py", line 1118, in reset
  File "widgets\map\mapmodel.py", line 1266, in reset_threat_zones
  File "game\game.py", line 446, in threat_zone_for
  File "game\coalition.py", line 82, in threat_zone
AssertionError

Generating campaign without inversion works fine. I also tested inverting a couple other campaigns in case it was something screwing up with campaign inversion across the board, but they all seemed to work fine. So, it appears to be an issue with inverting this specific campaign.

This error occurs in 4.1.1 (I guess no one ever inverted that campaign in the past couple of months!), 5.0 release, and the latest dev build.

**Comment by DanAlbert** [comment]
Not necessarily a bug. Inversion support is optional in campaigns. The campaign owner will need to answer that.

**Comment by Starfire13** [comment]
Any idea what is the cause of the error though? Is it simply because the campaign has not been setup for inversion?

**Comment by DanAlbert** [comment]
It's entirely possible that one coalition ends up with no bases at all if the designer hasn't planned for it.

**Comment by Starfire13** [comment]
Makes sense.
