### ISSUE TITLE
Asssertion error on round complete & and no enemy units left

### ISSUE THREAD

**Issue by Binary-System** [dcs-liberation/dcs_liberation#1846]
Before filing, please search the issue tracker to see if the issue has already been reported.

If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Describe the bug**
Assertion error when trying to generate the next round

**To Reproduce**
Win the campaign by destroying all units

**Expected behavior**
A "you have won" message

**Additional information**
Traceback (most recent call last):
  File "windows\QWaitingForMissionResultWindow.py", line 218, in process_debriefing
  File "game\game.py", line 320, in pass_turn
  File "game\game.py", line 381, in initialize_turn
  File "game\game.py", line 341, in set_bullseye
  File "game\theater\conflicttheater.py", line 234, in closest_opposing_control_points
AssertionError

list.remove(x): x not in list

Traceback (most recent call last):
  File "windows\QWaitingForMissionResultWindow.py", line 217, in process_debriefing
  File "game\game.py", line 233, in finish_event
  File "game\event\event.py", line 215, in commit
  File "game\event\event.py", line 169, in commit_ground_object_losses
ValueError: list.remove(x): x not in list

We will usually need more information for debugging. Include as much of the following as you are able:

- The state.json file from the finished mission when the problem is related to results processing. By default these are located in your Liberation install directory.

**Version information (please complete the following information):**
 - DCS Liberation 5.0.0:

**Additional context**
[state.zip](https://github.com/dcs-liberation/dcs_liberation/files/7715941/state.zip)

**Comment by Starfire13** [comment]
https://github.com/dcs-liberation/dcs_liberation/issues/978
