### ISSUE TITLE
I-16 KeyError: 'unitPayloads'

### ISSUE THREAD

**Issue by MetalStormGhost** [dcs-liberation/dcs_liberation#1871]
### Affected versions

Development build

### Development build

PR #1870

### Description

I-16 seems to cause an uncaught exception when used in campaigns. I was testing out the loadouts in PR #1870 and ran into the issue below.

```
2021-12-24 13:24:20,387 :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "G:\Games\dcs_liberation_development_fork\qt_ui\widgets\QTopPanel.py", line 150, in passTurn
    self.game.pass_turn(no_action=True)
  File "G:\Games\dcs_liberation_development_fork\game\game.py", line 280, in pass_turn
    self.initialize_turn()
  File "G:\Games\dcs_liberation_development_fork\game\game.py", line 357, in initialize_turn
    self.blue.initialize_turn()
  File "G:\Games\dcs_liberation_development_fork\game\coalition.py", line 182, in initialize_turn
    self.plan_missions()
  File "G:\Games\dcs_liberation_development_fork\game\coalition.py", line 203, in plan_missions
    TheaterCommander(self.game, self.player).plan_missions(tracer)
  File "G:\Games\dcs_liberation_development_fork\game\commander\theatercommander.py", line 83, in plan_missions
    result = self.plan(state)
  File "G:\Games\dcs_liberation_development_fork\game\htn.py", line 83, in plan
    if task.preconditions_met(planning_state.state):
  File "G:\Games\dcs_liberation_development_fork\game\commander\tasks\primitive\barcap.py", line 18, in preconditions_met
    return super().preconditions_met(state)
  File "G:\Games\dcs_liberation_development_fork\game\commander\tasks\packageplanningtask.py", line 51, in preconditions_met
    return self.fulfill_mission(state)
  File "G:\Games\dcs_liberation_development_fork\game\commander\tasks\packageplanningtask.py", line 102, in fulfill_mission
    self.package = fulfiller.plan_mission(
  File "G:\Games\dcs_liberation_development_fork\game\commander\packagefulfiller.py", line 159, in plan_mission
    self.plan_flight(
  File "G:\Games\dcs_liberation_development_fork\game\commander\packagefulfiller.py", line 78, in plan_flight
    if not builder.plan_flight(flight):
  File "G:\Games\dcs_liberation_development_fork\game\commander\packagebuilder.py", line 55, in plan_flight
    flight = Flight(
  File "G:\Games\dcs_liberation_development_fork\game\ato\flight.py", line 50, in __init__
    self.loadout = Loadout.default_for(self)
  File "G:\Games\dcs_liberation_development_fork\gen\flights\loadouts.py", line 176, in default_for
    flight.unit_type.dcs_unit_type.load_payloads()
  File "g:\games\dcs_liberation_development_fork\env\src\pydcs\dcs\unittype.py", line 135, in load_payloads
    pays = payload_main["unitPayloads"]
KeyError: 'unitPayloads'
```

Reproduction steps:

1. Start new Mozdok to Maykop campaign
2. Select Soviet Union 1943 as the player faction
3. Select Germany 1942 as the opposing faction
4. Verify that an I-16 squadron is created
5. If not, go back to step 1.
6. Begin the campaign, observe the error message

Re-generating the same campaign with the same factions without an I-16 squadron does not exhibit the error.

### Save game and other files

In the attached campaign file the error is also exhibited when clicking "Take off":
[I-16_KeyError_unitPayloads.zip](https://github.com/dcs-liberation/dcs_liberation/files/7774198/I-16_KeyError_unitPayloads.zip)

**Comment by MetalStormGhost** [comment]
I reproduced the problem with the latest development revision 023f89c26ccf25e54547046ab39744d7c3c024cf so it's not related to Starfire's loadouts. Took four retries, though, so might be related to certain mission types.
[I-16_KeyError_unitPayloads_023f89c26ccf25e54547046ab39744d7c3c024cf.zip](https://github.com/dcs-liberation/dcs_liberation/files/7774236/I-16_KeyError_unitPayloads_023f89c26ccf25e54547046ab39744d7c3c024cf.zip)

**Comment by DanAlbert** [comment]
The second attached save generates just fine for me, so it's probably something wrong with the PR.
