### ISSUE TITLE
Edit flight information for F18

### ISSUE THREAD

**Issue by Trini86** [dcs-liberation/dcs_liberation#1955]
### Affected versions

5.1.0

### Description

clicking on the flight to get flight information for F18  I get this Error

2022-01-17 11:20:06,794 :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "widgets\ato.py", line 119, in on_double_click
  File "widgets\ato.py", line 124, in edit_flight
  File "dialogs.py", line 57, in open_edit_flight_dialog
  File "windows\mission\QEditFlightDialog.py", line 33, in __init__
  File "windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
  File "gen\flights\loadouts.py", line 120, in iter_for
  File "gen\flights\loadouts.py", line 120, in <dictcomp>
  File "game\data\weapons.py", line 73, in with_clsid
KeyError: '{FPU_12_FUEL_TANK}'

### Save game and other files

[New_AirBase1_Cont.zip](https://github.com/dcs-liberation/dcs_liberation/files/7883459/New_AirBase1_Cont.zip)

**Comment by Starfire13** [comment]
The FPU12 is a 480 gallon external fuel tank carried by the Superhornet. You must have some sort of mod for that installed. It is not compatible with Liberation. That is the problem.
