### ISSUE TITLE
ValueError: Unhandled building category: fob in log on using cheat to capture a FOB

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#2139]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2048799345

### Description

An error is generated in the log (with no popup) when a FOB is cheat-captured. This error does not prevent the FOB from being cheat captured, but should probably be looked at in case it breaks anything else behind the scenes.

Traceback (most recent call last):
  File "uvicorn\protocols\http\httptools_impl.py", line 367, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "fastapi\applications.py", line 212, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\cors.py", line 84, in __call__
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 61, in app
  File "fastapi\routing.py", line 226, in app
  File "fastapi\routing.py", line 161, in run_endpoint_function
  File "starlette\concurrency.py", line 39, in run_in_threadpool
  File "anyio\to_thread.py", line 28, in run_sync
  File "anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 754, in run
  File "game\server\tgos\routes.py", line 19, in get_tgo
  File "game\server\tgos\models.py", line 52, in for_tgo
  File "game\sidc.py", line 346, in sidc
  File "game\theater\theatergroundobject.py", line 323, in symbol_set_and_entity
ValueError: Unhandled building category: fob
2022-03-29 18:24:41,670 :: root :: ERROR :: Uncaught (in promise) Error: Request failed with status code 500

### Save game and other files

[Cheat Capture Test File #3733.zip](https://github.com/dcs-liberation/dcs_liberation/files/8369056/Cheat.Capture.Test.File.3733.zip)

**Comment by Raffson** [comment]
Came across this one as well, let's put that on my TODO list shall we 🤣
