### ISSUE TITLE
Naquora, Syria is unusable for helicopters

### ISSUE THREAD

**Issue by nickjzx** [dcs-liberation/dcs_liberation#2149]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2081970415

### Description

Moving helicopters to Naquora in Syria and attempting to generate a mission causes an error, moving them back to Haifa fixes the issue.  To reproduce the error load the attached save and click the take off button, the following error will appear:

2022-04-02 10:30:49,958 :: root :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 285, in launch_mission
  File "qt_ui\simcontroller.py", line 76, in generate_miz
  File "game\sim\gameloop.py", line 67, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 50, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 106, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 257, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 110, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 180, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupconfigurator.py", line 73, in configure
  File "game\theater\controlpoint.py", line 1043, in active_runway
  File "game\runways.py", line 115, in get_preferred_runway
IndexError: list index out of range.

Attached the log, save and campaign I've made below.

### Save game and other files

[ah64syria.zip](https://github.com/dcs-liberation/dcs_liberation/files/8402967/ah64syria.zip)
[Northbound Lightning.zip](https://github.com/dcs-liberation/dcs_liberation/files/8402968/Northbound.Lightning.zip)
[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/8402971/liberation.log)

**Comment by DanAlbert** [comment]
The code around runway enumeration was completely redone since then, so assuming fixed. Let us know if you see this again.
