### ISSUE TITLE
Unable to generate new campaigns

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#2224]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2324309577

### Description

I am unable to generate any campaign from the new campaign wizard.  (Campain or faction choice does not matter)

```
Traceback (most recent call last):
  File "MyPath\dcs_liberation\qt_ui\windows\newgame\QNewGameWizard.py", line 190, in accept
    self.generatedGame = generator.generate()
  File "MyPath\dcs_liberation\game\theater\start_generator.py", line 93, in generate
    game = Game(
  File "MyPath\dcs_liberation\game\game.py", line 125, in __init__
    self.blue = Coalition(self, player_faction, player_budget, player=True)
  File "MyPath\dcs_liberation\game\coalition.py", line 45, in __init__
    self.armed_forces = ArmedForces(self.faction)
  File "MyPath\dcs_liberation\game\armedforces\armedforces.py", line 20, in __init__
    self._load_forces(faction)
  File "MyPath\dcs_liberation\game\armedforces\armedforces.py", line 41, in _load_forces
    if layout.generic and layout.usable_by_faction(faction):
  File "MyPath\dcs_liberation\game\layout\layout.py", line 210, in usable_by_faction
    return all(
  File "MyPath\dcs_liberation\game\layout\layout.py", line 210, in <genexpr>
    return all(
  File "MyPath\dcs_liberation\game\layout\layout.py", line 234, in all_unit_groups
    yield from group.unit_groups
AttributeError: 'str' object has no attribute 'unit_groups'
```

### Save game and other files

Not available.

**Comment by Starfire13** [comment]
I wonder if something's messed up with your install. Campaigns are generating fine on #3851 (the same build you're on) for me.

**Comment by SnappyComebacks** [comment]
Some strange dev environment issue on my end.  I have no idea why it happened.
I normally run the `Python: Main` vscode run.  I tried `Python: Debug` run it failed, but running `Python: Main` after worked fine.  I did also add the `PYTHONPATH=. python ./qt_ui/main.py;`, but if I remove `PYTHONPATH=. python ./qt_ui/main.py;` again, it still works.
