### ISSUE TITLE
Exception: 'DeadFlightPlan' object has no attribute 'targets'

### ISSUE THREAD

**Issue by Raffson** [dcs-liberation/dcs_liberation#2247]
### Affected versions

Development build

### Description

Upon trying to delete a waypoint of a flight that derives from `FormationAttackFlightPlan`, the following exception is raied:

````
Traceback (most recent call last):
  File "qt_ui\windows\mission\flight\waypoints\QFlightWaypointTab.py", line 107, in on_delete_waypoint
    self.delete_waypoint(waypoint)
  File "qt_ui\windows\mission\flight\waypoints\QFlightWaypointTab.py", line 116, in delete_waypoint
    is_target = waypoint in self.flight.flight_plan.targets
AttributeError: 'DeadFlightPlan' object has no attribute 'targets'
````

Another exception is raised in a specific case:

- Create a package with a DEAD flight for example
- Edit the flight and try deleting a waypoint (raises the exception above)
- Close ~~all edit flight/~~ the package window WITHOUT saving the package

This raises the following assertion error twice:

````
Traceback (most recent call last):
  File "qt_ui\windows\mission\flight\settings\FlightAirfieldDisplay.py", line 57, in update_departure_time
    delay = estimator.mission_start_time(self.flight)
  File "game\ato\traveltime.py", line 62, in mission_start_time
    startup_time = flight.flight_plan.startup_time()
  File "game\ato\flightplans\flightplan.py", line 262, in startup_time
    takeoff_time = self.takeoff_time()
  File "game\ato\flightplans\flightplan.py", line 259, in takeoff_time
    return self.tot - self._travel_time_to_waypoint(tot_waypoint)
  File "game\ato\flightplans\flightplan.py", line 219, in _travel_time_to_waypoint
    total += self.travel_time_between_waypoints(previous_waypoint, waypoint)
  File "game\ato\flightplans\loiter.py", line 39, in travel_time_between_waypoints
    travel_time = super().travel_time_between_waypoints(a, b)
  File "game\ato\flightplans\flightplan.py", line 226, in travel_time_between_waypoints
    a.position, b.position, self.speed_between_waypoints(a, b)
  File "game\ato\flightplans\formationattack.py", line 46, in speed_between_waypoints
    return super().speed_between_waypoints(a, b)
  File "game\ato\flightplans\formation.py", line 65, in speed_between_waypoints
    assert self.package.formation_speed is not None
AssertionError
````

While fixing the first exception also resolves the second one, I first want to examine the second exception so I understand why it's not raised after fixing the first exception. Expect a solution soon ^^

### Save game and other files

Any campaign file should do...

**Comment by Raffson** [comment]
Turns out the exceptions are unrelated! After applying a fix for the first exception, the second one can still be triggered as follows:

- Create any package that derives from `FormationAttackPlan`, as these to be the ones that are affected
- Open up the dialog to edit the flight (there should only be 1 at this point) and close it
- Cancel the package, i.e. close with 'X' in top right of window

I guess it's better to move this to a separate issue, I'll make a PR solving only the first exception.
