### ISSUE TITLE
Exception: AssertionError 'self.package.formation_speed is not None'

### ISSUE THREAD

**Issue by Raffson** [dcs-liberation/dcs_liberation#2250]
### Affected versions

Development build

### Description

Initially discovered in #2247:

````
Traceback (most recent call last):
  File "qt_ui\windows\mission\flight\settings\FlightAirfieldDisplay.py", line 57, in update_departure_time
    delay = estimator.mission_start_time(self.flight)
  File "game\ato\traveltime.py", line 62, in mission_start_time
    startup_time = flight.flight_plan.startup_time()
  File "game\ato\flightplans\flightplan.py", line 262, in startup_time
    takeoff_time = self.takeoff_time()
  File "game\ato\flightplans\flightplan.py", line 259, in takeoff_time
    return self.tot - self._travel_time_to_waypoint(tot_waypoint)
  File "game\ato\flightplans\flightplan.py", line 219, in _travel_time_to_waypoint
    total += self.travel_time_between_waypoints(previous_waypoint, waypoint)
  File "game\ato\flightplans\loiter.py", line 39, in travel_time_between_waypoints
    travel_time = super().travel_time_between_waypoints(a, b)
  File "game\ato\flightplans\flightplan.py", line 226, in travel_time_between_waypoints
    a.position, b.position, self.speed_between_waypoints(a, b)
  File "game\ato\flightplans\formationattack.py", line 46, in speed_between_waypoints
    return super().speed_between_waypoints(a, b)
  File "game\ato\flightplans\formation.py", line 65, in speed_between_waypoints
    assert self.package.formation_speed is not None
AssertionError
````

Steps to recreate the problem:

- Create any package that derives from `FormationAttackPlan`, as these seem to be the ones that are affected
- Open up the dialog to edit the flight (there should only be 1 at this point) and close it
- Cancel the package, i.e. close with 'X' in top right of window

### Save game and other files

Any campaign file should do...

**Comment by DanAlbert** [comment]
Assuming you filed this for yourself since there's no save file attached.

**Comment by Raffson** [comment]
No save file should be needed since it's present in any campaign at any time. I just tried starting a brand new campaign, buy some units, start the campaign and plan a package.

**Comment by DanAlbert** [comment]
Things that appear reproducible are not always reproducible. I've wasted plenty of time trying to repro bugs without save games.

**Comment by Raffson** [comment]
In that case, this is the save-file I originally worked with:

[liberation-v6_test3.zip](https://github.com/dcs-liberation/dcs_liberation/files/8886817/liberation-v6_test3.zip)

**Comment by Raffson** [comment]
Continue the conversation in PR if needed...

**Comment by DanAlbert** [comment]
Reopening the bug for release tracking.
