### ISSUE TITLE
Can't edit SEAD/DEAD flight of F/A-18Cs

### ISSUE THREAD

**Issue by TristanPFox** [dcs-liberation/dcs_liberation#2291]
### Affected versions

5.2.0

### Description

When I try to edit a flight I get the following error:
'{BRU_42A_x3_ADM_141A}'

Traceback (most recent call last):
  File "widgets\ato.py", line 226, in on_edit
  File "widgets\ato.py", line 124, in edit_flight
  File "dialogs.py", line 57, in open_edit_flight_dialog
  File "windows\mission\QEditFlightDialog.py", line 33, in __init__
  File "windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
  File "gen\flights\loadouts.py", line 120, in iter_for
  File "gen\flights\loadouts.py", line 120, in <dictcomp>
  File "game\data\weapons.py", line 78, in with_clsid
KeyError: '{BRU_42A_x3_ADM_141A}'

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9031798/liberation.log)

**Comment by Starfire13** [comment]
5.2 was released in March. Hornet TALDs was released last week. Hence, TALDs are not supported.
