### ISSUE TITLE
Error when trying to edit Tomcat flight, KeyError: '{SHOULDER AIM-7P}'

### ISSUE THREAD

**Issue by AShyBiBlob** [dcs-liberation/dcs_liberation#2299]
### Affected versions

5.2.0

### Description

I don't know what went wrong but every time I try to access the tomcats in the liberation launcher it gives me this error.
![image](https://user-images.githubusercontent.com/108694190/177207834-1e7aa46e-d7ba-4b1d-a376-97b60f69aa02.png)

My friend don't have this issue, but re-installing didn't work.

Apologies for the clumsy report.

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/9041691/liberation.log)

Traceback (most recent call last):
  File "widgets\ato.py", line 119, in on_double_click
  File "widgets\ato.py", line 124, in edit_flight
  File "dialogs.py", line 57, in open_edit_flight_dialog
  File "windows\mission\QEditFlightDialog.py", line 33, in __init__
  File "windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
  File "gen\flights\loadouts.py", line 120, in iter_for
  File "gen\flights\loadouts.py", line 120, in <dictcomp>
  File "game\data\weapons.py", line 78, in with_clsid
KeyError: '{SHOULDER AIM-7P}'

This repeats over and over in logs.

**Comment by AShyBiBlob** [comment]
Addendum 1:

The error is caused by having a custom payload to carry said missile, problem was solved via changing payload composition. I feel a little dumber now.
