### ISSUE TITLE
Error when editing A4 flight

### ISSUE THREAD

**Issue by JeffreyLeftovers** [dcs-liberation/dcs_liberation#2306]
### Affected versions

5.2.0

### Description

When clicking edit on a previously created flight in package I get an error code. 

'{D-704_Buddy_Pod}'
Traceback (most recent call last):
  File "widgets\ato.py", line 226, in on_edit
  File "widgets\ato.py", line 124, in edit_flight
  File "dialogs.py", line 57, in open_edit_flight_dialog
  File "windows\mission\QEditFlightDialog.py", line 33, in __init__
  File "windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
  File "gen\flights\loadouts.py", line 120, in iter_for
  File "gen\flights\loadouts.py", line 120, in <dictcomp>
  File "game\data\weapons.py", line 78, in with_clsid
KeyError: '{D-704_BUDDY_POD}'

Fresh install of liberation. Fresh install of A4E. Removed all custom loadouts from savedgames/misioneditor/UnitPaylouds

Also tried deleting all preset loudouts in the ME for the A4. No luck.

Factions used USN1985 and BluFor ColdWar.

A4E box ticked in campaign creation.

### Save game and other files

![image](https://user-images.githubusercontent.com/109010890/178130323-a9a74cab-77e1-490f-92a4-1f140eda7a32.png)
[cantedita4flight.zip](https://github.com/dcs-liberation/dcs_liberation/files/9078384/cantedita4flight.zip)

**Comment by Starfire13** [comment]
I tried editing the flights in the attached save file, and was able to do so with no errors on 5.2 and the A-4 mod v2.0.1

**Comment by Starfire13** [comment]
Issue resolved. User had A-4 mod v1.5 installed in an old Steam DCS directory.
