### ISSUE TITLE
Add flights when no adequate aircraft available produces error

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#2310]
### Affected versions

Development build

### Development build

https://github.com/dcs-liberation/dcs_liberation/actions/runs/2646267533

### Description

If you right click on an objective and try to add a flight to a package with no aircraft available, or with no aircraft available to be tasked for the default objective type, you will receive:

```
2022-07-10 20:21:42,971 :: root :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "G:\...\dcs_liberation\qt_ui\windows\mission\QPackageDialog.py", line 175, in on_add_flight
    self.add_flight_dialog = QFlightCreator(
  File "G:\...\dcs_liberation\qt_ui\windows\mission\flight\QFlightCreator.py", line 119, in __init__
    home_base: ControlPoint = squadron.location
AttributeError: 'NoneType' object has no attribute 'location'
```

Attached is the same campaign, at turn zero and turn one.
To reproduce:
In the first campaign try to create any package.
In the second campaign, try to create another package on any SAM site.

### Save game and other files

[4090_ExerciseVegasNerve.zip](https://github.com/dcs-liberation/dcs_liberation/files/9080483/4090_ExerciseVegasNerve.zip)

**Comment by Raffson** [comment]
Fixed #2326
