### ISSUE TITLE
Mirage 2000c error changing or creating mission - M2KC_RAFAUT_SAMP250HD 

### ISSUE THREAD

**Issue by cazubris** [dcs-liberation/dcs_liberation#2471]
### Affected versions

5.2.0

### Description

Hey all, I think this has to do with the SAMP-250 bomb being added "recently".  any idea what to do to fix this, can somebody maybe point me to the "game\data\weapons.py" file, I'm having some trouble finding that.  It happens on all campaigns and all mission types. I can't create a new mission but if one is created automatically I can't edit it. I am using the last 5.2 release build. 

----------------------------ERROR DUMP:----------------------------
'{M2KC_RAFAUT_SAMP250HD}'

Traceback (most recent call last):
  File "widgets\ato.py", line 119, in on_double_click
  File "widgets\ato.py", line 124, in edit_flight
  File "dialogs.py", line 57, in open_edit_flight_dialog
  File "windows\mission\QEditFlightDialog.py", line 33, in __init__
  File "windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 39, in __init__
  File "windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
  File "gen\flights\loadouts.py", line 120, in iter_for
  File "gen\flights\loadouts.py", line 120, in <dictcomp>
  File "game\data\weapons.py", line 78, in with_clsid
KeyError: '{M2KC_RAFAUT_SAMP250HD}'
----------------------------END ERROR DUMP:----------------------------

### Save game and other files

[SAMPBUG.zip](https://github.com/dcs-liberation/dcs_liberation/files/9740529/SAMPBUG.zip)

**Comment by cazubris** [comment]
logs

**Comment by DanAlbert** [comment]
Was already fixed in 6
