### ISSUE TITLE
BUG Impossible to buy base defenses in build acbd453

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#251]
![image](https://user-images.githubusercontent.com/29724443/97099169-31b05300-1686-11eb-868f-e93e855d3fd2.png)

Syria map with bluefor modern
Select campaign invasion from Turkey
Click HATAY airbase and attempt to swap base defenses

Notice the error

Traceback (most recent call last):
  File "qt_ui\windows\groundobject\QGroundObjectMenu.py", line 185, in buy_group
  File "qt_ui\windows\groundobject\QGroundObjectMenu.py", line 219, in __init__
  File "qt_ui\windows\groundobject\QGroundObjectMenu.py", line 228, in init_ui
AttributeError: 'str' object has no attribute 'name'

**Comment by s3-chardonjf** [comment]
Fixed in https://github.com/Khopa/dcs_liberation/commit/839f163ac5cd77f6b180e0a11ebd66f4358d4714
