### ISSUE TITLE
Key Error:  AIM-7P

### ISSUE THREAD

**Issue by BarryManaloe** [dcs-liberation/dcs_liberation#2518]
### Affected versions

5.2.0

### Description

The following message appears when attempting to start initial turn or double clicking on a flight of F-18's.

Traceback (most recent call last):
  File "widgets\QTopPanel.py", line 148, in passTurn
  File "game\game.py", line 320, in pass_turn
  File "game\game.py", line 397, in initialize_turn
  File "game\coalition.py", line 182, in initialize_turn
  File "game\coalition.py", line 203, in plan_missions
  File "game\commander\theatercommander.py", line 82, in plan_missions
  File "game\htn.py", line 82, in plan
  File "game\commander\tasks\primitive\dead.py", line 22, in preconditions_met
  File "game\commander\tasks\packageplanningtask.py", line 51, in preconditions_met
  File "game\commander\tasks\packageplanningtask.py", line 102, in fulfill_mission
  File "game\commander\packagefulfiller.py", line 198, in plan_mission
  File "game\commander\packagefulfiller.py", line 77, in plan_flight
  File "game\commander\packagebuilder.py", line 55, in plan_flight
  File "gen\flights\flight.py", line 309, in __init__
  File "gen\flights\loadouts.py", line 181, in default_for
  File "gen\flights\loadouts.py", line 181, in <dictcomp>
  File "game\data\weapons.py", line 78, in with_clsid
KeyError: '{AIM-7P}'

### Save game and other files

Will not let me attach a .liberation or .miz file.

**Comment by Starfire13** [comment]
AIM-7P is a new missile and is not supported in 5.2. To get around the error, remove that missile from all your F-14 loadouts in the DCS mission editor.

**Comment by BarryManaloe** [comment]
Thank you sir!   Too easy.
