### ISSUE TITLE
Failure to Launch

### ISSUE THREAD

**Issue by WingNt** [dcs-liberation/dcs_liberation#2613]
### Affected versions

6.0.0

### Campaign name

None selected

### Blue faction

none

### Red faction

none

### Description

Game will not install. 

### Log file

Traceback (most recent call last):
  File "qt_ui\main.py", line 13, in <module>
  File "C:\Users\jmast\AppData\Local\Temp\embedded.wbxuf677.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "dcs\__init__.py", line 1, in <module>
  File "C:\Users\jmast\AppData\Local\Temp\embedded.wbxuf677.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "dcs\mission.py", line 16, in <module>
  File "C:\Users\jmast\AppData\Local\Temp\embedded.wbxuf677.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "dcs\coalition.py", line 3, in <module>
  File "C:\Users\jmast\AppData\Local\Temp\embedded.wbxuf677.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "dcs\countries.py", line 3, in <module>
  File "C:\Users\jmast\AppData\Local\Temp\embedded.wbxuf677.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "dcs\country.py", line 1, in <module>
  File "C:\Users\jmast\AppData\Local\Temp\embedded.wbxuf677.zip\shibokensupport\__feature__.py", line 142, in _import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "dcs\helicopters.py", line 14, in <module>
  File "dcs\helicopters.py", line 28, in Mi_24V
  File "dcs\liveries_scanner.py", line 166, in __init__
  File "dcs\liveries_scanner.py", line 35, in read_liberation_preferences
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DanAlbert** [comment]
There is no install. Extract it and run. It looks like you tried to run directly from the zip file.

If that's not it, no idea.

**Comment by WingNt** [comment]
No, it's extracted to my desktop. I try to run the .exe and that's the error I get. I have no idea what's going on with it....

**Comment by Starfire13** [comment]
Try extracting it again. And make sure it completes the extraction process.

**Comment by tomwabinski** [comment]
I just ran into this. After a blue screen liberation wouldn't start anymore with above errors which was very odd. The reason was an empty ~\AppData\Local\DCSLiberation\liberation_preferences.json file. I didn't save anything at the time of the blue screen thus it's odd how it all could end up in this state. Obviously re-extracting didn't help as the file was still there but deleting the corrupted pref file did. Came up fine after reinitizalization. Easily to be reproduced clearing out the file too.

**Comment by DanAlbert** [comment]
Thanks! I'm a bit surprised because I could have sworn I'd seen real error messages whenever that file was borked. I've been wanting to take a hammer to that code anyway though.

**Comment by DanAlbert** [comment]
Ah, that's why. Liberation is handling this just fine. The bug is in the new livery scanner in pydcs. I'll send a fix upstream.

**Comment by DanAlbert** [comment]
Actually both are broken :) https://github.com/dcs-liberation/dcs_liberation/pull/2828
