### ISSUE TITLE
campaign mission

### ISSUE THREAD

**Issue by Panther2-1** [dcs-liberation/dcs_liberation#2624]
### Affected versions

6.0.0

### Build information

Plane F-16C_50 has no pylon 13.

Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 288, in launch_mission
  File "qt_ui\simcontroller.py", line 76, in generate_miz
  File "game\sim\gameloop.py", line 67, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 50, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 107, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 250, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 110, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 166, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 77, in create_flight_group
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 118, in generate_flight_at_departure
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 174, in _generate_at_airport
  File "dcs\mission.py", line 1119, in flight_group_from_airport
  File "dcs\mission.py", line 968, in _flying_group_from_airport
  File "dcs\unitgroup.py", line 454, in load_task_default_loadout
  File "dcs\flyingunit.py", line 90, in load_pylon
RuntimeError: Plane F-16C_50 has no pylon 13.

### Description

Plane F-16C_50 has no pylon 13.

Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 288, in launch_mission
  File "qt_ui\simcontroller.py", line 76, in generate_miz
  File "game\sim\gameloop.py", line 67, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 50, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 107, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 250, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 110, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 166, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 77, in create_flight_group
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 118, in generate_flight_at_departure
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 174, in _generate_at_airport
  File "dcs\mission.py", line 1119, in flight_group_from_airport
  File "dcs\mission.py", line 968, in _flying_group_from_airport
  File "dcs\unitgroup.py", line 454, in load_task_default_loadout
  File "dcs\flyingunit.py", line 90, in load_pylon
RuntimeError: Plane F-16C_50 has no pylon 13.

### Save game and other files

Plane F-16C_50 has no pylon 13.

Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 288, in launch_mission
  File "qt_ui\simcontroller.py", line 76, in generate_miz
  File "game\sim\gameloop.py", line 67, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 50, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 107, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 250, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 110, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 166, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 77, in create_flight_group
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 118, in generate_flight_at_departure
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 174, in _generate_at_airport
  File "dcs\mission.py", line 1119, in flight_group_from_airport
  File "dcs\mission.py", line 968, in _flying_group_from_airport
  File "dcs\unitgroup.py", line 454, in load_task_default_loadout
  File "dcs\flyingunit.py", line 90, in load_pylon
RuntimeError: Plane F-16C_50 has no pylon 13.

**Comment by DanAlbert** [comment]
No repro instructions, no save game.
