### ISSUE TITLE
Error message on "Finish"

### ISSUE THREAD

**Issue by loopium** [dcs-liberation/dcs_liberation#2684]
### Affected versions

Development build

### Build information

build 4665

### Campaign name

Persian Gulf : Battle for Abu Dhabi -

### Blue faction

Bluefor 2015

### Red faction

Iran 2015

### Modifications to default settings

Supercarrier enabled

### Description

Error dialog :+1: 

'SquadronBaseSelector' object has no attribute 'AdjustToContents'

Traceback (most recent call last):
  File "qt_ui\windows\newgame\QNewGameWizard.py", line 194, in accept
  File "qt_ui\windows\AirWingConfigurationDialog.py", line 527, in __init__
  File "qt_ui\windows\AirWingConfigurationDialog.py", line 438, in __init__
  File "qt_ui\windows\AirWingConfigurationDialog.py", line 322, in __init__
  File "qt_ui\windows\AirWingConfigurationDialog.py", line 335, in new_page_for_type
  File "qt_ui\windows\AirWingConfigurationDialog.py", line 288, in __init__
  File "qt_ui\windows\AirWingConfigurationDialog.py", line 255, in __init__
  File "qt_ui\windows\AirWingConfigurationDialog.py", line 274, in add_squadron
  File "qt_ui\windows\AirWingConfigurationDialog.py", line 174, in __init__
  File "qt_ui\windows\AirWingConfigurationDialog.py", line 118, in __init__
AttributeError: 'SquadronBaseSelector' object has no attribute 'AdjustToContents'

### Log file

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/10343999/liberation.log)

**Comment by DanAlbert** [comment]
Nothing reproducible. We need repro steps and the save game they work for (follow the template if you want bugs fixed, we can't do anything without the information it asks for).

**Comment by DanAlbert** [comment]
(never mind earlier message, was mistakenly on 6.x on my end, sorry for the confusion!)

**Comment by DanAlbert** [comment]
The "fix" will be to just delete that line, but it's possible that we need to figure out what the new API for that is in Qt 6 if it's actually important, and presumably it is...

**Comment by DanAlbert** [comment]
https://github.com/dcs-liberation/dcs_liberation/pull/2685 fixes the issue. It was present in a few other parts of the UI as well.

**Comment by DanAlbert** [comment]
Fix is merged. New builds shouldn't have the issue any more. Thanks for the report 👍
