### ISSUE TITLE
Sunken Kuznetkov Bug

### ISSUE THREAD

**Issue by reslox** [dcs-liberation/dcs_liberation#2693]
### Affected versions

6.0.0

### Build information

Liberation 6.1

### Description

Enemy Carrier Kuznetsov got sunk and now save got broken.

2023-01-11 23:44:45,684 :: root :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 288, in launch_mission
  File "qt_ui\simcontroller.py", line 76, in generate_miz
  File "game\sim\gameloop.py", line 67, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 51, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 107, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 255, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 110, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 181, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupconfigurator.py", line 105, in configure
  File "game\missiongenerator\aircraft\waypoints\waypointgenerator.py", line 115, in create_waypoints
  File "game\missiongenerator\aircraft\waypoints\pydcswaypointbuilder.py", line 65, in build
  File "game\missiongenerator\aircraft\waypoints\recoverytanker.py", line 13, in add_tasks
  File "game\missiongenerator\aircraft\waypoints\recoverytanker.py", line 36, in _get_carrier_group_id
UnboundLocalError: local variable 'theater_mapping' referenced before assignment
2023-01-11 23:44:56,679 :: uvicorn.access :: INFO :: ::1:19200 - "GET /game HTTP/1.1" 307
2023-01-11 23:44:57,381 :: uvicorn.access :: INFO :: ::1:19200 - "GET /game/ HTTP/1.1" 200
2023-01-11 23:44:57,469 :: root :: ERROR :: Error while loading terrain zones [object Object]
2023-01-11 23:45:24,220 :: root :: INFO :: Generating flight: F/A-18C Hornet (Lot 20)
2023-01-11 23:45:24,228 :: root :: ERROR :: Could not find group for BAI mission 0213 | STURGEON (Carrier)
2023-01-11 23:45:24,229 :: root :: INFO :: Generating flight: F/A-18C Hornet (Lot 20)
2023-01-11 23:45:24,235 :: root :: ERROR :: Could not find group for BAI mission 0213 | STURGEON (Carrier)
2023-01-11 23:45:24,236 :: root :: INFO :: Generating flight: AV-8B Harrier II Night Attack
2023-01-11 23:45:24,238 :: root :: INFO :: Generating flight: AV-8B Harrier II Night Attack
2023-01-11 23:45:24,240 :: root :: INFO :: Generating flight: Su-25T Frogfoot
2023-01-11 23:45:24,245 :: root :: INFO :: Generating flight: JF-17 Thunder
2023-01-11 23:45:24,248 :: root :: INFO :: Generating flight: E-3A
2023-01-11 23:45:24,250 :: root :: INFO :: Generating flight: MiG-29S Fulcrum-C
2023-01-11 23:45:24,254 :: root :: INFO :: Generating flight: F/A-18C Hornet (Lot 20)
2023-01-11 23:45:24,258 :: root :: INFO :: Generating flight: JF-17 Thunder
2023-01-11 23:45:24,263 :: root :: INFO :: Generating flight: A-50
2023-01-11 23:45:24,266 :: root :: DEBUG :: A-50 max_speed * 0.7 is Speed(speed_in_kph=595.0)
2023-01-11 23:45:24,267 :: root :: DEBUG :: A-50 max_speed * 0.7 is Speed(speed_in_kph=595.0)
2023-01-11 23:45:24,269 :: root :: INFO :: Generating flight: IL-78M
2023-01-11 23:45:24,272 :: root :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 288, in launch_mission
  File "qt_ui\simcontroller.py", line 76, in generate_miz
  File "game\sim\gameloop.py", line 67, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 51, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 107, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 255, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 110, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 181, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupconfigurator.py", line 105, in configure
  File "game\missiongenerator\aircraft\waypoints\waypointgenerator.py", line 115, in create_waypoints
  File "game\missiongenerator\aircraft\waypoints\pydcswaypointbuilder.py", line 65, in build
  File "game\missiongenerator\aircraft\waypoints\recoverytanker.py", line 13, in add_tasks
  File "game\missiongenerator\aircraft\waypoints\recoverytanker.py", line 36, in _get_carrier_group_id
UnboundLocalError: local variable 'theater_mapping' referenced before assignment

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/10397784/liberation.log)
[CaucHDS.zip](https://github.com/dcs-liberation/dcs_liberation/files/10397793/CaucHDS.zip)

**Comment by reslox** [comment]
a bug due to the refuel flight getting an invalid unit ID, I modified it to a random high number so the mission would generate as a workaround

**Comment by DanAlbert** [comment]
I don't think your workaround is actually related? I can't explain why that changed anything. The problem is that the code that generates recovery tanker tasks is entirely broken when the carrier has sunk. PyCharm even highlights that code as broken. Improving the error handling there a bit, we get a better error message:

> RuntimeError: Could not find a carrier in the mission matching Admiral Kuznetsov at (-110922.37694208, 268824.67354682)

That's not actually the problem though. That mission should not have been generated in the first place. That problem appears to be caused by all the refueling missions sharing a common type, and only differentiating based on the type and allegiance of the target. The theater-wide refueling target is placed at the friendly control point that's closest to the enemy: https://github.com/dcs-liberation/dcs_liberation/blob/f8c1d291ed3253e011c8c571181467c798779539/game/commander/theaterstate.py#L173

That code however allows any type of control point other than off-map spawns: https://github.com/dcs-liberation/dcs_liberation/blob/f8c1d291ed3253e011c8c571181467c798779539/game/commander/objectivefinder.py#L212-L228

The three refueling tasks probably need to be split so this kind of bug wouldn't have been possible to write in the first place, but that's invasive and a save-compat break, so for 6.1.1 I think the best we can do is filter out carriers in that function: https://github.com/dcs-liberation/dcs_liberation/pull/2706
