### ISSUE TITLE
Mig29S create error when restricting weapons by date

### ISSUE THREAD

**Issue by e0s888** [dcs-liberation/dcs_liberation#2743]
### Affected versions

6.1.1

### Description

I tried to start mission with MIig29s with option ,,restrict weapons by date", but it won't start. Same error shows when trying to enter loadout of this wing.

'R-3R'

Traceback (most recent call last):
  File "qt_ui\widgets\ato.py", line 140, in <lambda>
  File "qt_ui\widgets\ato.py", line 125, in edit_flight
  File "qt_ui\dialogs.py", line 57, in open_edit_flight_dialog
  File "qt_ui\windows\mission\QEditFlightDialog.py", line 35, in __init__
  File "qt_ui\windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "qt_ui\windows\mission\flight\payload\QFlightPayloadTab.py", line 33, in __init__
  File "qt_ui\windows\mission\flight\payload\QLoadoutEditor.py", line 37, in __init__
  File "qt_ui\windows\mission\flight\payload\QPylonEditor.py", line 74, in set_from
  File "qt_ui\windows\mission\flight\payload\QPylonEditor.py", line 67, in matching_weapon_name
  File "game\ato\loadouts.py", line 74, in degrade_for_date
  File "game\ato\loadouts.py", line 53, in _fallback_for
  File "game\data\weapons.py", line 92, in fallbacks
  File "game\data\weapons.py", line 137, in fallback
  File "game\data\weapons.py", line 159, in named
KeyError: 'R-3R'

[Mig29SBug.zip](https://github.com/dcs-liberation/dcs_liberation/files/10797342/Mig29SBug.zip)

### Save game and other files

[Mig29SBug.zip](https://github.com/dcs-liberation/dcs_liberation/files/10797347/Mig29SBug.zip)

**Comment by Nosajthedevil** [comment]
Dan, this was fixed in development via pull request 2782.

e0s888, sorry about that - the fix is to go into your liberation installation and open the file at resources/weapons/a2a-missiles/R-24R.yaml, then change the line that says "fallback: R-3R" to "fallback: R-3R - AAM, radar guided".

**Comment by DanAlbert** [comment]
Thanks for confirming!

I'm not sure if there's going to be a 6.1.2. I'm going to leave this open as a reminder for later so I can set up the triage for 6.1.2 at least so we don't forget to cherry pick that if we do.

**Comment by e0s888** [comment]
Nosajthedevil, Thanks a lot for the instructions on how to correct it!

**Comment by DanAlbert** [comment]
> I'm not sure if there's going to be a 6.1.2. I'm going to leave this open as a reminder for later so I can set up the triage for 6.1.2 at least so we don't forget to cherry pick that if we do.

Upgrading pydcs would break save compat. I'd rather ship a feature-lite 7.0.0 with the latest DCS features than a bug fix release without them, so going to close this.
