### ISSUE TITLE
Refuel package causing crash on "take-off"

### ISSUE THREAD

**Issue by jGROETEN** [dcs-liberation/dcs_liberation#2770]
### Affected versions

6.1.1

### Build information

6.1.1

### Campaign name

Persian Gulf Scenic

### Blue faction

USA 2005

### Red faction

Iran 2015

### Modifications to default settings

I created all packages myself.

### Description

The mission crashes when click "take-off"
When I remove the refuel package the mission works
If I remove and add refuel package again it works
Only change I had made to refuel pack was moving a waypoint more to the left from CVN

### Log file

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/11067814/liberation.log)

**Comment by jGROETEN** [comment]
[Persian Gulf 1_Planned.zip](https://github.com/dcs-liberation/dcs_liberation/files/11067854/Persian.Gulf.1_Planned.zip)

**Comment by DanAlbert** [comment]
I don't know which of the many crashes in the log is the one you're reporting here (the log file is reused between multiple runs, so some of those crashes might be unrelated), but the attached save generates fine for me. That does mean you're probably talking about this one though:

```
2023-03-25 03:18:17,801 :: root :: ERROR :: Uncaught exception
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 288, in launch_mission
  File "qt_ui\simcontroller.py", line 76, in generate_miz
  File "game\sim\gameloop.py", line 67, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 51, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 107, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 250, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 111, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 167, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 74, in create_flight_group
  File "game\ato\flightstate\uninitialized.py", line 27, in is_waiting_for_start
RuntimeError: Attempted to simulate flight that is not fully initialized
```

Which was a dup of https://github.com/dcs-liberation/dcs_liberation/issues/2735
