### ISSUE TITLE
Pylon Error with UH-60L

### ISSUE THREAD

**Issue by bubbles03** [dcs-liberation/dcs_liberation#2920]
### Affected versions

7.0.0

### Build information

DCS Liberation 7.0.0

### Description

When scheduling an air assault by a UH-60L (1.3.1), I get an error saying "Plane UH-60L has no pylon 8." The issue persists for both AI and player flights and earlier versions of Liberation. 

Error details: 
Plane UH-60L has no pylon 8.

Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 297, in launch_mission
  File "qt_ui\simcontroller.py", line 91, in generate_miz
  File "game\sim\gameloop.py", line 74, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 50, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 109, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 273, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 111, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 167, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 77, in create_flight_group
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 110, in generate_flight_at_departure
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 220, in _generate_at_group
  File "dcs\mission.py", line 1201, in flight_group_from_unit
  File "dcs\unitgroup.py", line 454, in load_task_default_loadout
  File "dcs\flyingunit.py", line 90, in load_pylon
RuntimeError: Plane UH-60L has no pylon 8.

### Save game and other files

[black_sea.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11582698/black_sea.liberation.zip)

**Comment by DanAlbert** [comment]
Mod data needs to be regenerated, probably. Those are community contributions not maintained by the dev team, so we'll need a volunteer to update it.

@Nosajthedevil, you've done a lot of.the mods lately. Feel like taking this on?

**Comment by Nosajthedevil** [comment]
Sure, might be a few days before I get a moment.

**Comment by DanAlbert** [comment]
No rush, thanks!

**Comment by Nosajthedevil** [comment]
@bubbles03 I have 1.3.2 installed ( which should be identical to 1.3.1 from a liberation perspective) and I can't duplicate the error, the mod is working fine for me with liberation 7.0 - both running the mission you attached and creating a new mission. 

I noticed that the current mod only has 7 pylons though, which is aligned with the data injected into liberation. I'm trying to think through what else would trigger that error, and usually it's because a loadout in either DCS or liberation has a loaded pylon that's not defined in liberation and liberation doesn't know what to do with it. 

So a couple questions - First, are you using one of the submod  versions? If not, have you made any edits to either the liberation payloads for the UH-60L or the payloads in the mod itself? If it's the former, let me know which one and I'll see if we can add support for it. If it's the latter, could you double check that there aren't any payloads that have an 8th pylon accidentally defined? If so, remove that payload and see if the mod works.

I'll still make sure that all of the detailed payload data in the mod matches what's defined in liberation and that I'm not missing something, but I want to cross off any easy fixes that might be causing the problem first.

**Comment by bubbles03** [comment]
@Nosajthedevil Thanks for the fast reply. I was previously using version 1.3.2 with the Armed Blackhawk mod before I deleted it and switched back to 1.3.1. Following your advice, I deleted all of my loadouts and the issue seems to have been resolved. Thanks for the help!
