### ISSUE TITLE
[Bug] TypeError on opening base menu

### ISSUE THREAD

**Issue by walterroach** [dcs-liberation/dcs_liberation#293]
Traceback (most recent call last):
  File "qt_ui\widgets\map\QMapObject.py", line 38, in mousePressEvent
  File "qt_ui\widgets\map\QMapControlPoint.py", line 66, in on_click
  File "qt_ui\windows\basemenu\QBaseMenu2.py", line 25, in __init__
  File "qt_ui\windows\basemenu\QBaseMenuTabs.py", line 26, in __init__
  File "qt_ui\windows\basemenu\airfield\QAirfieldCommand.py", line 16, in __init__
  File "qt_ui\windows\basemenu\airfield\QAirfieldCommand.py", line 25, in init_ui
  File "qt_ui\windows\mission\QPlannedFlightsView.py", line 21, in __init__
  File "qt_ui\windows\mission\QPlannedFlightsView.py", line 46, in set_flight_planner
  File "qt_ui\windows\mission\QPlannedFlightsView.py", line 28, in setup_content
  File "qt_ui\windows\mission\QFlightItem.py", line 25, in __init__
TypeError: unsupported type for timedelta seconds component: datetime.timedelta

**Comment by walterroach** [comment]
Latest dev branch Logs and save attached for me to investigate later.

[issue293.zip](https://github.com/Khopa/dcs_liberation/files/5470206/issue293.zip)
