### ISSUE TITLE
Unable to open airbase window after passing first turn

### ISSUE THREAD

**Issue by s3-chardonjf** [dcs-liberation/dcs_liberation#294]
Downloaded latest develop build (256)
![image](https://user-images.githubusercontent.com/29724443/97796057-d940fe80-1c0d-11eb-812e-20722f31d85a.png)

Created a new game. I purchased units and passed turn.
Now I can no longer open Ramat David window.

[autosave.zip](https://github.com/Khopa/dcs_liberation/files/5470257/autosave.zip)
- Load the save
- Click Ramat David airbase to buy some planes and notice the error

```
=============================
Traceback (most recent call last):
  File "qt_ui\widgets\map\QMapObject.py", line 38, in mousePressEvent
  File "qt_ui\widgets\map\QMapControlPoint.py", line 66, in on_click
  File "qt_ui\windows\basemenu\QBaseMenu2.py", line 25, in __init__
  File "qt_ui\windows\basemenu\QBaseMenuTabs.py", line 26, in __init__
  File "qt_ui\windows\basemenu\airfield\QAirfieldCommand.py", line 16, in __init__
  File "qt_ui\windows\basemenu\airfield\QAirfieldCommand.py", line 25, in init_ui
  File "qt_ui\windows\mission\QPlannedFlightsView.py", line 21, in __init__
  File "qt_ui\windows\mission\QPlannedFlightsView.py", line 46, in set_flight_planner
  File "qt_ui\windows\mission\QPlannedFlightsView.py", line 28, in setup_content
  File "qt_ui\windows\mission\QFlightItem.py", line 25, in __init__
TypeError: unsupported type for timedelta seconds component: datetime.timedelta
```

**Comment by walterroach** [comment]
Same as #293
