### ISSUE TITLE
SA-342L pylons change prevents mission start

### ISSUE THREAD

**Issue by henrikoldcorn** [dcs-liberation/dcs_liberation#3012]
### Affected versions

7.1.0

### Build information

DCS Liberation 7.1.0

### Description

Campaign Operation Allied Sword includes enemy SA-342L units, and presumably sends them to do some CAS. While starting Turn 1 ("Take Off") an error occurs, giving message at the end. This may be because Polychop recently changed some SA-342 things. 

Creating a "Liberation CAS" loadout in DCS with dust filter and 4xHOT changes the below error message slightly to "pylon 4". 
I've tried to see what's causing the error myself but without any experience with this code or indeed working on anything similar I'm not getting far; my best guess is that resources/customized_payloads/SA342L.lua needs changing. 

Savefile attached. 

Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 297, in launch_mission
  File "qt_ui\simcontroller.py", line 91, in generate_miz
  File "game\sim\gameloop.py", line 74, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 50, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 109, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 278, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 111, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 167, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 77, in create_flight_group
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 118, in generate_flight_at_departure
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 174, in _generate_at_airport
  File "dcs\mission.py", line 1156, in flight_group_from_airport
  File "dcs\mission.py", line 1005, in _flying_group_from_airport
  File "dcs\unitgroup.py", line 454, in load_task_default_loadout
  File "dcs\flyingunit.py", line 90, in load_pylon
RuntimeError: Plane SA342L has no pylon 3.

### Save game and other files

[alied_sword.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/11773104/alied_sword.liberation.zip)

**Comment by DanAlbert** [comment]
Has already been fixed in 8.
