### ISSUE TITLE
its somehow looking for my arma 3 folder

### ISSUE THREAD

**Issue by ArcasIII** [dcs-liberation/dcs_liberation#3019]
### Affected versions

7.1.0

### Build information

DCS Liberation 7.1.0

### Description

[Errno 2] No such file or directory: 'E:\\GAMES\\Arma 3\\Steam\\steamapps\\libraryfolders.vdf'

Traceback (most recent call last):
  File "qt_ui\windows\newgame\QNewGameWizard.py", line 217, in accept
  File "game\campaignloader\campaign.py", line 126, in load_theater
  File "game\campaignloader\mizcampaignloader.py", line 99, in __init__
  File "dcs\mission.py", line 378, in load_file
  File "dcs\coalition.py", line 160, in load_from_dict
  File "dcs\flyingunit.py", line 235, in __init__
  File "dcs\flyingunit.py", line 29, in __init__
  File "dcs\unittype.py", line 133, in load_payloads
  File "dcs\payloads.py", line 79, in payload_dirs
  File "dcs\payloads.py", line 60, in user
  File "dcs\installation.py", line 51, in get_dcs_saved_games_directory
  File "dcs\installation.py", line 37, in get_dcs_install_directory
  File "dcs\installation.py", line 92, in _dcs_steam_path
  File "dcs\installation.py", line 79, in _steam_library_directories
  File "pathlib.py", line 1058, in read_text
  File "pathlib.py", line 1044, in open
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\GAMES\\Arma 3\\Steam\\steamapps\\libraryfolders.vdf'

i even reinstalled liberation a bunch of times and redirecting the save and install folder a lot of times too and its still looking at a non existent arma 3 folder

### Save game and other files

[liberation.log](https://github.com/dcs-liberation/dcs_liberation/files/11779428/liberation.log)

**Comment by DanAlbert** [comment]
That's not an arma 3 directory, that's a steam install directory named "Arma 3" that wasn't properly uninstalled. You registry still thinks that's where steam is installed. I'm not really sure how that happened, but this is bad data on your machine that's lying to pydcs. If you look at the `SteamPath` entry in `HKEY_CURRENT_USER\Software\Valve\Steam` in regedit you'll find the bad data.

**Comment by ArcasIII** [comment]
damn i never would have thought it was something in my registry, thanks bro
fixed it by changing the steampath to the actual location of my steam directory
