### ISSUE TITLE
Unable to use Hornet

### ISSUE THREAD

**Issue by sirpecka** [dcs-liberation/dcs_liberation#306]
Whenever there's a flight of Hornets (AI or player) the mission is not created and I get following error:

INFO:root:Generating flight :
2020-10-26 00:48:18,218 :: INFO :: Generating flight :
INFO:root:airgen: for 80 at Airport(King Hussein Air College)
2020-10-26 00:48:18,219 :: INFO :: airgen: for 80 at Airport(King Hussein Air College)
ERROR:root:'tasks'
2020-10-26 00:48:18,257 :: ERROR :: 'tasks'
WARNING:root:No room on runway or parking slots. Starting from the air.
2020-10-26 00:48:18,259 :: WARNING :: No room on runway or parking slots. Starting from the air.
INFO:root:airgen: for 80 at 3000 at 550
2020-10-26 00:48:18,261 :: INFO :: airgen: for 80 at 3000 at 550
Traceback (most recent call last):
File "gen\aircraft.py", line 862, in generate_planned_flight
File "gen\aircraft.py", line 624, in _generate_at_airport
File "pydcs\dcs\mission.py", line 1072, in flight_group_from_airport
File "pydcs\dcs\mission.py", line 929, in _flying_group_from_airport
File "pydcs\dcs\unitgroup.py", line 429, in load_task_default_loadout
File "pydcs\dcs\unittype.py", line 153, in loadout
KeyError: 'tasks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "qt_ui\windows\mission\QMissionPlanning.py", line 156, in on_start
File "game\game.py", line 178, in initiate_event
File "game\event\event.py", line 111, in generate
File "game\operation\frontlineattack.py", line 39, in generate
File "game\operation\operation.py", line 195, in generate
File "gen\aircraft.py", line 774, in generate_flights
File "gen\aircraft.py", line 875, in generate_planned_flight
File "gen\aircraft.py", line 682, in _generate_group
File "gen\aircraft.py", line 648, in _generate_inflight
File "pydcs\dcs\mission.py", line 1173, in flight_group
File "pydcs\dcs\mission.py", line 1030, in flight_group_inflight
File "pydcs\dcs\mission.py", line 966, in _flying_group_inflight
File "pydcs\dcs\unitgroup.py", line 429, in load_task_default_loadout
File "pydcs\dcs\unittype.py", line 153, in loadout
KeyError: 'tasks

**Comment by DanAlbert** [comment]
I play with hornets all the time, so there's something more going on. Please upload the liberation save file.

**Comment by sirpecka** [comment]
There you go.

[Syria.zip](https://github.com/Khopa/dcs_liberation/files/5502147/Syria.zip)

**Comment by DanAlbert** [comment]
Is this issue still present on the latest release with new games?
