### ISSUE TITLE
No module named 'shapely._geos?'

### ISSUE THREAD

**Issue by Nosajthedevil** [dcs-liberation/dcs_liberation#3127]
### Affected versions

Development build

### Build information

All recent development builds (5390 through 5406)

### Description

I'm assuming you are already aware of this, but running a recent development build immediately gives the following error:

Unhandled exception in script

Failed to execute script 'main' due to unhandled exception: No module named shapely._geos'

Traceback (most recent call last):
  File "qt_ui\main.py", line 19, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "game\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "game\game.py", line 17, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "game\ato\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "game\ato\flight.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "game\ato\flightmembers.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "game\ato\flightmember.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "game\ato\loadouts.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "game\data\weapons.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "game\dcs\aircrafttype.py", line 39, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "game\utils.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "shapely\__init__.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "shapely\_geometry.py", line 6, in <module>
  File "shapely\_geometry_helpers.pyx", line 1, in init shapely._geometry_helpers
ModuleNotFoundError: No module named 'shapely._geos'

### Save game and other files (save game required, bugs without saves will be closed)

I don't think these save files will be helpful since they are from 8.1.

9 won't open, I don't have an opportunity to save anything and nothing is getting logged.
[Guam Resurgance.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/12231309/Guam.Resurgance.liberation.zip)

**Comment by DanAlbert** [comment]
No, I hadn't seen this because I never run the fully assembled builds.

I guess there's something extra we need to do to keep pyinstaller working.

**Comment by Nosajthedevil** [comment]
Ha, there's always something extra that needs to be done. Thanks for looking at it.
