### ISSUE TITLE
add support for editbox property controls

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#3277]
### Affected versions

Development build

### Build information

DCS Liberation 10.0.0
Build 5663
Git revision 9271717a5be3b3df1b9e4af2f0782d9bbe90c85e

### Description

I am seeing multiple errors in the log when double-clicking on most flights (but not all) in packages.

There's typically three generated by each double-click, and they look like this:
Traceback (most recent call last):
  File "qt_ui\windows\mission\flight\payload\propertyeditor.py", line 44, in __init__
  File "qt_ui\windows\mission\flight\payload\propertyeditor.py", line 93, in control_for_property
qt_ui.windows.mission.flight.payload.propertyeditor.UnhandledControlTypeError: Unhandled control type editbox
2023-12-02 09:20:20,821 :: root :: ERROR :: Cannot create property control for property VoiceCallsignLabel of F-16CM Fighting Falcon (Block 50)
Traceback (most recent call last):
  File "qt_ui\windows\mission\flight\payload\propertyeditor.py", line 44, in __init__
  File "qt_ui\windows\mission\flight\payload\propertyeditor.py", line 93, in control_for_property
qt_ui.windows.mission.flight.payload.propertyeditor.UnhandledControlTypeError: Unhandled control type editbox
2023-12-02 09:20:20,822 :: root :: ERROR :: Cannot create property control for property VoiceCallsignNumber of F-16CM Fighting Falcon (Block 50)
Traceback (most recent call last):
  File "qt_ui\windows\mission\flight\payload\propertyeditor.py", line 44, in __init__
  File "qt_ui\windows\mission\flight\payload\propertyeditor.py", line 93, in control_for_property
qt_ui.windows.mission.flight.payload.propertyeditor.UnhandledControlTypeError: Unhandled control type editbox
2023-12-02 09:20:20,823 :: root :: ERROR :: Cannot create property control for property STN_L16 of F-16CM Fighting Falcon (Block 50)

I am not 100% certain yet, but my testing so far suggests it happens with specific aircraft types rather than mission types. It always appears to happen with Hornets and Vipers, but I don't get the error with Harriers.

You also don't get any errors with F-15Es unless you set a player slot, at which point you get one error. No errors on Harriers regardless if there is a player slot.

2023-12-02 09:27:05,476 :: root :: ERROR :: Cannot create property control for property IFF_M2_CODE of F-15E Strike Eagle (Suite 4+)
Traceback (most recent call last):
  File "qt_ui\windows\mission\flight\payload\propertyeditor.py", line 44, in __init__
  File "qt_ui\windows\mission\flight\payload\propertyeditor.py", line 93, in control_for_property
qt_ui.windows.mission.flight.payload.propertyeditor.UnhandledControlTypeError: Unhandled control type editbox

On two occasions that I have not since been able to replicate, double-clicking on a flight in the package window has failed (i.e. flight window doesn't open), and I get this error instead of the ones above. Once this happens, I have to restart Liberation. This error window appears upon shutting down Liberation. The same error appears in the log.

Edit: Just encountered the error below a third time. Even replicating the exact steps I took to create that package did not generate the error again.

Edit2: Just encountered the error a 4th time. I can't seem to figure out what causes it to trigger this error instead of the previous ones. It just seems to happen sometimes, and recreating the same steps that lead to it doesn't seem to trigger it again.

![Screenshot 2023-12-02 090227](https://github.com/dcs-liberation/dcs_liberation/assets/72491792/cba78077-d3d3-4364-9ced-1d931c8ffa7a)

### Save game and other files (save game required, bugs without saves will be closed)

[Noisy Cricket #5663 Turn 1.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/13532326/Noisy.Cricket.5663.Turn.1.liberation.zip)

**Comment by DanAlbert** [comment]
The `UnhandledControlTypeError` messages are non-fatal, and not new. 2.9 added a new type of control for text entry that we don't handle. That doesn't cause any problems, it just means that those properties aren't editable in Liberation. It's only on some flights because the only properties that use that control type are the datalink properties, and only a few aircraft support that.

The other problem is unrelated, but without knowing how to repro I'm not sure what to do about it anyway.

**Comment by DanAlbert** [comment]
Reclassifying this as the FR for editbox support. If you can work out how to repro the other problem that's worth filing. I've never seen it myself, despite spending quite a bit of time working on that UI recently.

**Comment by Starfire13** [comment]
It's possible that second problem was just something specific to 5663. If I encounter it again, I'll investigate further.

**Comment by DanAlbert** [comment]
If you do run into it again and we can't explain it, the code that was throwing the error is the guts that power the log window. I could just remove that and make the log window button open the log in whatever text editor instead.

**Comment by Starfire13** [comment]
> If you do run into it again and we can't explain it, the code that was throwing the error is the guts that power the log window. I could just remove that and make the log window button open the log in whatever text editor instead.

Ok, I figured out at least one way to replicate the error consistently. The error window will pop up if you close Liberation while the log window is still open. I checked and this doesn't occur in 9.0.

I'll file this separately.
