### ISSUE TITLE
AH-64 Pylon Issue, DCS 2.9.4.53707

### ISSUE THREAD

**Issue by bubbles03** [dcs-liberation/dcs_liberation#3384]
### Affected versions

11.0.0

### Build information

V10.0.0

### Description

Attempting to start a mission with the non-AI AH64 produces the error:

Plane AH-64D_BLK_II has no pylon 6.

Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 316, in launch_mission
  File "qt_ui\simcontroller.py", line 91, in generate_miz
  File "game\sim\gameloop.py", line 74, in pause_and_generate_miz
  File "game\sim\missionsimulation.py", line 50, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 107, in generate_miz
  File "game\missiongenerator\missiongenerator.py", line 269, in generate_air_units
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 111, in generate_flights
  File "game\missiongenerator\aircraft\aircraftgenerator.py", line 169, in create_and_configure_flight
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 77, in create_flight_group
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 116, in generate_flight_at_departure
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 238, in _generate_at_cp_helipad
  File "game\missiongenerator\aircraft\flightgroupspawner.py", line 222, in _generate_at_group
  File "dcs\mission.py", line 1207, in flight_group_from_unit
  File "dcs\unitgroup.py", line 454, in load_task_default_loadout
  File "dcs\flyingunit.py", line 90, in load_pylon
RuntimeError: Plane AH-64D_BLK_II has no pylon 6.

This happens regardless of what I put on the loadout. I suspect that this has something to do with the AH64 FCR slot, but am not sure because this problem didn't come up when the FCR slot was first added. 

This error may also be present in 11.0.0 because it doesn't seem to be mentioned in the patch notes.

### Save game and other files (save game required, bugs without saves will be closed)

[CT.liberation.zip](https://github.com/dcs-liberation/dcs_liberation/files/15085012/CT.liberation.zip)

**Comment by zhexu14** [comment]
This issue is due to DCS changing the way the Apache FCR is loaded in the mission editor with version 2.9.3.51704 and is fixed in Version 11 of Liberation.

**Comment by Starfire13** [comment]
This is due to ED changing the FCR from a checkbox to being part of the loadout. It was fixed 2 months ago. Please update to Liberation 11.
