### ISSUE TITLE
Latest update ver 2.2.0 stops me opening previous liberation campaigns

### ISSUE THREAD

**Issue by Scubamurph** [dcs-liberation/dcs_liberation#370]
When I try to open a liberation campaign since the update I get the following:

2020-11-15 15:01:54,537 :: INFO :: Using D:/DCS World OpenBeta as 'DCS installation folder'
2020-11-15 15:01:54,823 :: INFO :: On Game generated
2020-11-15 15:02:02,672 :: ERROR :: Invalid Save game
Traceback (most recent call last):
  File "game\persistency.py", line 52, in load_game
  File "C:\Users\scuba\AppData\Local\Temp\embedded.7z3iwyig.zip\shibokensupport\__feature__.py", line 146, in _import
ModuleNotFoundError: No module named 'theater.caucasus'

Previous campaign creates on Caucus map and area of setting was Western Georgia.
Can create new instances without issue.

Is there any other info I can provide?

**Comment by DanAlbert** [comment]
Saves are not compatible across minor releases. The game is extremely different and it's not feasible to use 2.1 games in 2.2.
