### ISSUE TITLE
Failure to load save-file from v2.1.5

### ISSUE THREAD

**Issue by root0fall** [dcs-liberation/dcs_liberation#372]
Loading the previous save file from v2.1.5 results in a module error.

```
:: INFO :: Using C:/Users/dcs/Saved Games/DCS.openbeta_server as 'Saved Game Folder'
:: INFO :: Using E:/Program Files/Eagle Dynamics/DCS World OpenBeta Server as 'DCS installation folder'
:: INFO :: On Game generated
:: ERROR :: Invalid Save game
Traceback (most recent call last):
  File "game\persistency.py", line 52, in load_game
  File "C:\Users\dcs\AppData\Local\Temp\embedded.xrdqezd9.zip\shibokensupport\__feature__.py", line 146, in _import
ModuleNotFoundError: No module named 'theater.syria'
```

**Comment by Starfire13** [comment]
Saves from previous version are not compatible with latest release. Too much has changed.

**Comment by root0fall** [comment]
Are you just assuming that, or is that an official statement from the contributors?

**Comment by Khopa** [comment]
Yes it not compatible. 
Saves from 2.1.X are not compatible with 2.2.X.

**Comment by root0fall** [comment]
@Khopa please add a "known issues" section to the release notes.
