### ISSUE TITLE
It is possible to create empty flights inside of packages, this is probably not desired?

### ISSUE THREAD

**Issue by SnappyComebacks** [dcs-liberation/dcs_liberation#373]
In 2.2.0 it is possible to make flights inside packages that have 0 members.  I'm not sure there is a reason for this?
I believe this was preventing me from successfully creating the mission, but am unsure.  I received the following:

```Syria USA
2020-11-15 12:42:15,601 :: INFO :: Generating Frontline attack (regular)
USA
<class 'dcs.countries.USA'>
2,USA,[]
['USA']
['Syria']
2020-11-15 12:42:15,783 :: INFO :: Generating flight: <class 'dcs.planes.A_10C_2'>
2020-11-15 12:42:15,783 :: INFO :: airgen: <class 'dcs.planes.A_10C_2'> for 2 at Airport(Bandar Abbas Intl)
2020-11-15 12:42:15,784 :: INFO :: Loaded overridden payload for <class 'dcs.planes.A_10C_2'> - CAS for task <class 'dcs.task.CAS'>
2020-11-15 12:42:15,786 :: INFO :: Generating flight: <class 'dcs.planes.F_16C_50'>
2020-11-15 12:42:15,786 :: ERROR ::
2020-11-15 12:42:15,786 :: WARNING :: No room on runway or parking slots. Starting from the air.
Traceback (most recent call last):
  File "gen\aircraft.py", line 960, in generate_planned_flight
  File "gen\aircraft.py", line 794, in _generate_inflight
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 234, in launch_mission
  File "game\game.py", line 185, in initiate_event
  File "game\event\event.py", line 96, in generate
  File "game\operation\frontlineattack.py", line 38, in generate
  File "game\operation\operation.py", line 273, in generate
  File "gen\aircraft.py", line 904, in generate_flights
  File "gen\aircraft.py", line 988, in generate_planned_flight
  File "gen\aircraft.py", line 794, in _generate_inflight
AssertionError
QLayout: Attempting to add QLayout "" to QLoadoutEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to QLoadoutEditor "", which already has a layout
2020-11-15 12:52:15,375 :: INFO :: Saving game
2020-11-15 12:52:15,413 :: DEBUG :: Reloading Map Canvas
```

while only having 6 planes at Bandar Abbas.  When I removed the zero size flights I was able to successfully generate the mission.

**Comment by DanAlbert** [comment]
That error is unrelated.
