### ISSUE TITLE
Viggen - Unable to generate mission with generic CAS

### ISSUE THREAD

**Issue by Winzarten** [dcs-liberation/dcs_liberation#402]
When I try to fly an autogenerated frontline CAS mission with the AJS Viggen, the "Take off" button doesn't work (nothing is shown) as there is an error during mission generation.

This error is in the log:
2020-11-19 15:57:06,602 :: INFO :: Loaded overridden payload for <class 'dcs.planes.AJS37'> - CAS for task <class 'dcs.task.CAS'>
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 234, in launch_mission
  File "game\game.py", line 185, in initiate_event
  File "game\event\event.py", line 96, in generate
  File "game\operation\frontlineattack.py", line 38, in generate
  File "game\operation\operation.py", line 273, in generate
  File "gen\aircraft.py", line 907, in generate_flights
  File "gen\aircraft.py", line 1165, in create_waypoints
  File "random.py", line 248, in randint
  File "random.py", line 226, in randrange
ValueError: empty range for randrange() (0, 0, 0)

Flying a strike mission with selected target works without issues.

**Comment by walterroach** [comment]
I'm unable to reproduce, what version are you on and what campaign is being used?

Can you share your save game?

**Comment by Winzarten** [comment]
Sure thing
I'm using 2.2.0 version, Persian Gulf - Desert War is the campaign

[Viggen.zip](https://github.com/Khopa/dcs_liberation/files/5568835/Viggen.zip)
