### ISSUE TITLE
crash on mission launch for dev branch

### ISSUE THREAD

**Issue by DanAlbert** [dcs-liberation/dcs_liberation#451]
```
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\qt_ui\widgets\QTopPanel.py", line 226, in launch_mission
    unit_map = self.game.initiate_event(game_event)
  File "C:\Users\dan\src\dcs_liberation\game\game.py", line 180, in initiate_event
    return event.generate()
  File "C:\Users\dan\src\dcs_liberation\game\event\event.py", line 65, in generate
    unit_map = Operation.generate()
  File "C:\Users\dan\src\dcs_liberation\game\operation\operation.py", line 281, in generate
    cls._generate_air_units()
  File "C:\Users\dan\src\dcs_liberation\game\operation\operation.py", line 340, in _generate_air_units
    cls.airsupportgen.generate()
  File "C:\Users\dan\src\dcs_liberation\gen\airsupportgen.py", line 82, in generate
    tanker_group = self.mission.refuel_flight(
  File "C:\Users\dan\src\dcs_liberation\pydcs\dcs\mission.py", line 1289, in refuel_flight
    tanker = self.flight_group_inflight(country, name, plane_type, p, altitude, speed, task.Refueling)
  File "C:\Users\dan\src\dcs_liberation\pydcs\dcs\mission.py", line 1037, in flight_group_inflight
    p = self.aircraft(name + " Pilot #{nr}".format(nr=i), aircraft_type, country)
  File "C:\Users\dan\src\dcs_liberation\pydcs\dcs\mission.py", line 874, in aircraft
    return Plane(self.next_unit_id(), self.string(name), _type, country)
  File "C:\Users\dan\src\dcs_liberation\pydcs\dcs\flyingunit.py", line 219, in __init__
    super(Plane, self).__init__(_id, name, _type, _country)
  File "C:\Users\dan\src\dcs_liberation\pydcs\dcs\flyingunit.py", line 15, in __init__
    self.unit_type.load_payloads()
  File "C:\Users\dan\src\dcs_liberation\pydcs\dcs\unittype.py", line 124, in load_payloads
    if FlyingType._payload_cache[payload_filename] == cls.id and os.path.exists(payload_filename):
KeyError: 'C:\\Users\\dan\\src\\dcs_liberation\\qt_ui\\..\\resources\\customized_payloads\\F-22A.lua'

```

Seems like it's maybe related to the F-22 not having any loadouts?

**Comment by DanAlbert** [comment]
The opposite, actually. Deleting the F-22 custom loadouts fixed it for me.

**Comment by DanAlbert** [comment]
Not seeing this any more.
