### ISSUE TITLE
Can't generate new mission - Duplicate TGO unit Error

### ISSUE THREAD

**Issue by skeletonwburg** [dcs-liberation/dcs_liberation#517]
I am using the latest preview build (627) and following error occurs when I hit the "Take Off" Button:

> Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 232, in launch_mission
  File "game\game.py", line 201, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 303, in generate
  File "game\operation\operation.py", line 271, in _generate_ground_units
  File "gen\groundobjectsgen.py", line 420, in generate
  File "gen\groundobjectsgen.py", line 93, in generate
  File "gen\groundobjectsgen.py", line 109, in _register_unit_group
  File "game\unitmap.py", line 104, in add_ground_object_units
RuntimeError: Duplicate TGO unit: RED|SAM|8|AAA#2

I created new campaigns."Inherent Resolve" on syria and "Battle of Britain" on Channel and the error occurs in both campaigns with different units.

[brokenCampaigns.zip](https://github.com/Khopa/dcs_liberation/files/5648828/brokenCampaigns.zip)

**Comment by DanAlbert** [comment]
Fixed in the latest build, but does require a new game.
