### ISSUE TITLE
Libya Faction Broken in RC10

### ISSUE THREAD

**Issue by P4nts** [dcs-liberation/dcs_liberation#56]
When using the Libya faction in RC10 (misspelled as Lybia in the release, but no bother) Liberation will not create a mission file. The terminal in the background outputs this.

Lybia USA
INFO:root:<theater.base.Base object at 0x0000024D356FD128> for <class 'dcs.task.PinpointStrike'> (0): {<class 'dcs.vehicles.Armor.MBT_T_55'>: 2, <class 'dcs.vehicles.Artillery.MLRS_BM_21_Grad'>: 2, <class 'dcs.vehicles.Armor.FDDM_Grad'>: 4}
2020-08-16 04:11:15,053 :: INFO :: <theater.base.Base object at 0x0000024D356FD128> for <class 'dcs.task.PinpointStrike'> (0): {<class 'dcs.vehicles.Armor.MBT_T_55'>: 2, <class 'dcs.vehicles.Artillery.MLRS_BM_21_Grad'>: 2, <class 'dcs.vehicles.Armor.FDDM_Grad'>: 4}
WARNING:root:<theater.base.Base object at 0x0000024D356E8E48>: no units for <class 'dcs.task.PinpointStrike'>
2020-08-16 04:11:15,055 :: WARNING :: <theater.base.Base object at 0x0000024D356E8E48>: no units for <class 'dcs.task.PinpointStrike'>
INFO:root:<theater.base.Base object at 0x0000024D356FD128> for <class 'dcs.task.CAP'> (0): {<class 'dcs.planes.MiG_23MLD'>: 4}
2020-08-16 04:11:15,057 :: INFO :: <theater.base.Base object at 0x0000024D356FD128> for <class 'dcs.task.CAP'> (0): {<class 'dcs.planes.MiG_23MLD'>: 4}
INFO:root:Generating Frontline attack (regular)
2020-08-16 04:11:15,058 :: INFO :: Generating Frontline attack (regular)
USA
<class 'dcs.countries.USA'>
2,USA,[]
Traceback (most recent call last):
  File "qt_ui\windows\mission\QMissionPlanning.py", line 156, in on_start
  File "game\game.py", line 178, in initiate_event
  File "game\event\event.py", line 125, in generate
  File "game\operation\frontlineattack.py", line 31, in prepare
  File "game\operation\operation.py", line 95, in prepare
KeyError: -1

Cheers for all your hard work Liberation team, your stuff is the best.

**Comment by Khopa** [comment]
This is now fixed in 2.0.11 😀 

Please reopen if you encounter the issue again.
