### ISSUE TITLE
Cant take off due to Error

### ISSUE THREAD

**Issue by SlvrBuletNChil** [dcs-liberation/dcs_liberation#573]
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 232, in launch_mission
  File "game\game.py", line 206, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 308, in generate
  File "game\operation\operation.py", line 407, in _generate_ground_conflicts
  File "gen\armor.py", line 126, in generate
  File "gen\armor.py", line 643, in _generate_groups
  File "gen\armor.py", line 621, in get_valid_position_for_group
TypeError: 'int' object is not subscriptable

**Comment by DanAlbert** [comment]
I'm guessing I broke this when I cleaned up our projections, so I'll take it. Weird that I haven't seen the problem myself though... @SlvrBuletNChil can you upload the Liberation save that caused the problem?

**Comment by SlvrBuletNChil** [comment]
I tried to but it said the file type wasn't accepted. I'm sorry this is my first time submitting a bug here.

**Comment by SlvrBuletNChil** [comment]
[syriabeta.zip](https://github.com/Khopa/dcs_liberation/files/5685442/syriabeta.zip)

**Comment by DanAlbert** [comment]
Works for me on the latest beta. Could you check? A few changes went in since you filed this so maybe one of those fixed it.

**Comment by DanAlbert** [comment]
Yeah, @walterroach fixed this with d9ea33cbb96b9f2e47ab96a68dcc7687bd80c77a.

**Comment by SlvrBuletNChil** [comment]
Its working now, thanks a lot for the help man!
