### ISSUE TITLE
move group manipulation out of the UI so UI crashes can't break the game

### ISSUE THREAD

**Issue by vanson77** [dcs-liberation/dcs_liberation#582]
as described in Issue #581 the buttons in the repair window of e.g. a sam site does not update. If you click a repair button more than once you and want to start the mission, you get a "Duplicate TGO unit..." error message.

e.g.:
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 232, in launch_mission
  File "game\game.py", line 206, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 303, in generate
  File "game\operation\operation.py", line 271, in _generate_ground_units
  File "gen\groundobjectsgen.py", line 429, in generate
  File "gen\groundobjectsgen.py", line 94, in generate
  File "gen\groundobjectsgen.py", line 110, in _register_unit_group
  File "game\unitmap.py", line 104, in add_ground_object_units
RuntimeError: Duplicate TGO unit: RED|SAM|147|LN#2

**Comment by vanson77** [comment]
Attached a savegame. The problematic SAM-site is COLD at Gudauta, where i bought a launcher tiwce. Selling the whole site and rebuying it, and the savegame works again.


[my_black_sea_678.zip](https://github.com/Khopa/dcs_liberation/files/5691932/my_black_sea_678.zip)

**Comment by DanAlbert** [comment]
Hmm, this is different than the bug I thought was being described. It's not the whole site being duplicated, just the one unit. The former would have been a quick fix (I think), but the UI is doing a lot of things it shouldn't here which is why it was allowed to happen at all.

I fixed the UI bug that was exposing this. Will take longer to fix the underlying issue.
