### ISSUE TITLE
unchecking generate infantry groups along vehicles causing an error

### ISSUE THREAD

**Issue by Stondeeez** [dcs-liberation/dcs_liberation#584]
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 232, in launch_mission
  File "game\game.py", line 206, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 308, in generate
  File "game\operation\operation.py", line 407, in _generate_ground_conflicts
  File "gen\armor.py", line 126, in generate
  File "gen\armor.py", line 676, in _generate_groups
  File "gen\armor.py", line 204, in gen_infantry_group_for_group
  File "random.py", line 290, in choice
IndexError: Cannot choose from an empty sequence

**Comment by DanAlbert** [comment]
Were you on an older build? @Khopa added the check for this on Saturday.

**Comment by DanAlbert** [comment]
Ah, the fix didn't make it to 2.3. Fixing.
