### ISSUE TITLE
TypeError: '<=' not supported between instances of 'int' and 'Distance'

### ISSUE THREAD

**Issue by jeetsukumaran** [dcs-liberation/dcs_liberation#622]
[Current-002.zip](https://github.com/Khopa/dcs_liberation/files/5720697/Current-002.zip)

**Describe the bug**

Error on "Take Off":

```
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 232, in launch_mission
  File "game\game.py", line 207, in initiate_event
  File "game\event\event.py", line 65, in generate
  File "game\operation\operation.py", line 309, in generate
  File "game\operation\operation.py", line 377, in _generate_air_units
  File "gen\aircraft.py", line 939, in generate_flights
  File "gen\aircraft.py", line 1284, in create_waypoints
  File "gen\aircraft.py", line 1338, in set_takeoff_time
  File "gen\flights\traveltime.py", line 70, in mission_start_time
  File "gen\flights\flightplan.py", line 210, in startup_time
  File "gen\flights\flightplan.py", line 207, in takeoff_time
  File "gen\flights\flightplan.py", line 176, in _travel_time_to_waypoint
  File "gen\flights\flightplan.py", line 183, in travel_time_between_waypoints
  File "gen\flights\flightplan.py", line 112, in speed_between_waypoints
  File "gen\flights\flightplan.py", line 108, in best_speed_between_waypoints
  File "gen\flights\traveltime.py", line 42, in for_flight
  File "game\utils.py", line 171, in mach
  File "game\utils.py", line 123, in from_mach
TypeError: '<=' not supported between instances of 'int' and 'Distance'
```

**To Reproduce**

Click on "Take off"

**Expected behavior**

No such error.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

- Using Preview Build #819

**Comment by DanAlbert** [comment]
Was this with a new game?

**Comment by jeetsukumaran** [comment]
Ah, no, it was from campaign started in 2.3. 

I stupidly thought it was just the major upgrades that were incompatible. If this is a campaign compatibility, apologies for the noise.

**Comment by DanAlbert** [comment]
819 is from the main branch. `develop` breaks compat frequently.
