### ISSUE TITLE
KeyError: <class 'dcs.vehicles.Armor.SPG_M1128_Stryker_MGS'>

### ISSUE THREAD

**Issue by isotaan** [dcs-liberation/dcs_liberation#646]
When starting a new campaign with the Stryker MGS available as a ground unit (such as the "NATO Desert Storm" coalition) and with the "auto-purchase front line units" option ticked, the game will get hung with the following:

Traceback (most recent call last):
  File "qt_ui\windows\newgame\QNewGameWizard.py", line 101, in accept
  File "game\theater\start_generator.py", line 94, in generate
  File "game\game.py", line 127, in __init__
  File "game\game.py", line 313, in plan_procurement
  File "game\procurement.py", line 52, in spend_budget
  File "game\procurement.py", line 94, in reinforce_front_line
  File "game\procurement.py", line 78, in random_affordable_ground_unit
  File "game\procurement.py", line 79, in <listcomp>
KeyError: <class 'dcs.vehicles.Armor.SPG_M1128_Stryker_MGS'>

Interestingly, when you leave the auto-buy front line units unchecked, the MGS is not showing as available for purchase manually.

Notably

**Comment by Khopa** [comment]
Thanks, the unit isn't registered in our db which is why this is causing the bug.
Working on a fix.
