### ISSUE TITLE
TARCAP TOT cannot be calculated. #863

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#650]
[Golan life is peaceful there.zip](https://github.com/Khopa/dcs_liberation/files/5737902/Golan.life.is.peaceful.there.zip)

**Comment by Starfire13** [comment]
It appears TOT cannot be calculated for certain targets, such as unit groups at FOBs, unit groups at airfields (or the airfield directly for that matter), and certain resource points. For example, TARCAP planning works for Worm (Tech Combine and Tech Hangars) but does not work for ORCA (Warehouse and Hangars).

**Comment by DanAlbert** [comment]
![image](https://user-images.githubusercontent.com/315852/103064427-ce994a80-4568-11eb-8d94-6481f6e3c6b4.png)

The log shows this when attempting to plan the flight:

```
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\qt_ui\windows\mission\flight\waypoints\QFlightWaypointTab.py", line 65, in closure
    return self.confirm_recreate(arg)
  File "C:\Users\dan\src\dcs_liberation\qt_ui\windows\mission\flight\waypoints\QFlightWaypointTab.py", line 154, in confirm_recreate
    self.planner.populate_flight_plan(self.flight)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 741, in populate_flight_plan
    flight.flight_plan = self.generate_flight_plan(flight, custom_targets)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 771, in generate_flight_plan
    return self.generate_tarcap(flight)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 1043, in generate_tarcap
    nav_to=builder.nav_path(flight.departure.position, orbit0p,
  File "C:\Users\dan\src\dcs_liberation\gen\flights\waypointbuilder.py", line 465, in nav_path
    path = self.clean_nav_points(self.navmesh.shortest_path(a, b))
  File "C:\Users\dan\src\dcs_liberation\game\navmesh.py", line 147, in shortest_path
    raise ValueError(
ValueError: Origin point Point(-218705.07085438125, 83292.54556130621) is outside the navmesh
```

![image](https://user-images.githubusercontent.com/315852/103064534-099b7e00-4569-11eb-8407-bdaca0914dc0.png)

The target area got pruned out of the navmesh. I spent all my time working with complex campaign shapes assume the problems would be there but it looks like the simple one is causing problems :)

**Comment by DanAlbert** [comment]
It looks like this is already fixed. I had to expand the "map borders" that the navigation area uses for other reasons and I think that was sufficient to fix this as well. A newly generated Golan Heights campaign doesn't do this.
