### ISSUE TITLE
Selling or replacing ground unit groups is broken [build #892]

### ISSUE THREAD

**Issue by Hornet2041** [dcs-liberation/dcs_liberation#664]
**Describe the bug**
In previous builds, was able to sell and change the ground unit groups freely. Now in current build, selling it or replacing it results in blank screen and an inability to re-access that airbase or unit group menu.
Additionally can not access that menu on the subsequent turn after passing turn.
Notably does not prevent playing game, just can no longer access that base or unit window :(

**To Reproduce**
1. Go to any airbase
2. Click on a defence group (tanks, IFVs, SAMs, etc)
3. Select sell or buy/replace
4. See blank screen

**Expected behavior**
A replacement group plus the ability to access the base menu.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

2020-12-25 22:00:40,777 :: WARNING :: aa not in REWARDS
2020-12-25 22:00:45,708 :: WARNING :: aa not in REWARDS
Remove 0, 0
Remove 0, 1
2020-12-25 22:01:04,852 :: DEBUG :: Reloading Map Canvas
Traceback (most recent call last):
  File "qt_ui\widgets\map\QMapObject.py", line 38, in mousePressEvent
  File "qt_ui\widgets\map\QMapControlPoint.py", line 71, in on_click
  File "qt_ui\windows\basemenu\QBaseMenu2.py", line 81, in __init__
  File "qt_ui\windows\basemenu\QBaseMenuTabs.py", line 32, in __init__
  File "qt_ui\windows\basemenu\base_defenses\QBaseDefensesHQ.py", line 15, in __init__
  File "qt_ui\windows\basemenu\base_defenses\QBaseDefensesHQ.py", line 20, in init_ui
  File "qt_ui\windows\basemenu\base_defenses\QBaseInformation.py", line 23, in __init__
  File "qt_ui\windows\basemenu\base_defenses\QBaseInformation.py", line 33, in init_ui
TypeError: object of type 'generator' has no len()

Traceback (most recent call last):
  File "qt_ui\widgets\map\QMapGroundObject.py", line 95, in paint
  File "qt_ui\widgets\map\QMapGroundObject.py", line 102, in draw_health_gauge
TypeError: object of type 'generator' has no len()

**Version information (please complete the following information):**
 - DCS Liberation 2.4 build #892

**Comment by DanAlbert** [comment]
Works for me. If it's an older save it's probably just a save compat issue? If it's happening with new games, upload that save.

**Comment by Hornet2041** [comment]
2020-12-25 22:31:43,122 :: ERROR :: Could not save game
Traceback (most recent call last):
  File "game\persistency.py", line 49, in save_game
TypeError: cannot pickle 'generator' object

**Comment by DanAlbert** [comment]
Hmm, yeah, that makes sense. I'll need to try to make that happen.

Default settings for the game? Factions? Campaign?

**Comment by Starfire13** [comment]
I am experiencing the same error on my end. New campaign, so not a save compatibility issue. It is happening to me on both Caucasus and Syria, USA 2005 faction.
