### ISSUE TITLE
Unable to Accept Results (#909)

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#677]
**Describe the bug**
Clicking Accept Results at the end of a mission generates this error.
2020-12-27 23:22:35,731 :: INFO :: Finishing event AirWar
2020-12-27 23:22:35,732 :: INFO :: Committing mission results
2020-12-27 23:22:35,733 :: ERROR :: Found killed <class 'dcs.planes.FA_18C_hornet'> from Ramat David but that airbase has none available.
2020-12-27 23:22:35,733 :: INFO :: <class 'dcs.planes.AV8BNA'> destroyed from LHA-3 Belleau Wood
2020-12-27 23:22:35,733 :: ERROR :: Found killed <class 'dcs.planes.FA_18C_hornet'> from Ramat David but that airbase has none available.
2020-12-27 23:22:35,734 :: ERROR :: Found killed <class 'dcs.planes.F_15E'> from Ramat David but that airbase has none available.
2020-12-27 23:22:35,734 :: INFO :: <class 'dcs.planes.AV8BNA'> destroyed from LHA-3 Belleau Wood
2020-12-27 23:22:35,735 :: INFO :: <class 'dcs.planes.AV8BNA'> destroyed from LHA-3 Belleau Wood
2020-12-27 23:22:35,735 :: INFO :: <class 'dcs.planes.AV8BNA'> destroyed from LHA-3 Belleau Wood
2020-12-27 23:22:35,735 :: INFO :: <class 'dcs.planes.AV8BNA'> destroyed from LHA-3 Belleau Wood
2020-12-27 23:22:35,736 :: ERROR :: Found killed <class 'dcs.planes.F_15E'> from Ramat David but that airbase has none available.
2020-12-27 23:22:35,736 :: ERROR :: Found killed <class 'dcs.planes.F_15E'> from Ramat David but that airbase has none available.
2020-12-27 23:22:35,737 :: ERROR :: Found killed <class 'dcs.planes.F_15E'> from Ramat David but that airbase has none available.
2020-12-27 23:22:35,737 :: ERROR :: Found killed <class 'dcs.planes.FA_18C_hornet'> from Ramat David but that airbase has none available.
2020-12-27 23:22:35,738 :: INFO :: <class 'dcs.planes.F_14B'> destroyed from CVN-72 Abraham Lincoln
2020-12-27 23:22:35,739 :: ERROR :: Found killed <class 'dcs.planes.FA_18C_hornet'> from Ramat David but that airbase has none available.
2020-12-27 23:22:35,739 :: ERROR :: Found killed <class 'dcs.planes.F_15E'> from Ramat David but that airbase has none available.
2020-12-27 23:22:35,739 :: ERROR :: Found killed <class 'dcs.planes.MiG_19P'> from Marj Ruhayyil but that airbase has none available.
2020-12-27 23:22:35,740 :: ERROR :: Found killed <class 'dcs.planes.MiG_19P'> from Marj Ruhayyil but that airbase has none available.
2020-12-27 23:22:35,740 :: ERROR :: Found killed <class 'dcs.planes.MiG_25PD'> from Damascus but that airbase has none available.
2020-12-27 23:22:35,741 :: ERROR :: Found killed <class 'dcs.planes.MiG_25PD'> from Damascus but that airbase has none available.
2020-12-27 23:22:35,744 :: ERROR :: Found killed <class 'dcs.planes.MiG_19P'> from Marj Ruhayyil but that airbase has none available.
2020-12-27 23:22:35,744 :: ERROR :: Found killed <class 'dcs.planes.MiG_19P'> from Marj Ruhayyil but that airbase has none available.
2020-12-27 23:22:35,744 :: ERROR :: Found killed <class 'dcs.planes.MiG_19P'> from Marj Ruhayyil but that airbase has none available.
2020-12-27 23:22:35,745 :: ERROR :: Found killed <class 'dcs.planes.MiG_23MLD'> from Damascus but that airbase has none available.
2020-12-27 23:22:35,745 :: ERROR :: Found killed <class 'dcs.planes.MiG_23MLD'> from Damascus but that airbase has none available.
2020-12-27 23:22:35,745 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Damascus
2020-12-27 23:22:35,746 :: INFO :: <class 'dcs.planes.MiG_19P'> destroyed from Damascus
2020-12-27 23:22:35,746 :: ERROR :: Found killed <class 'dcs.planes.MiG_19P'> from Marj Ruhayyil but that airbase has none available.
2020-12-27 23:22:35,747 :: ERROR :: Found killed <class 'dcs.helicopters.Mi_8MT'> from Damascus but that airbase has none available.
2020-12-27 23:22:35,747 :: ERROR :: Found killed <class 'dcs.planes.Su_24M'> from Damascus but that airbase has none available.
2020-12-27 23:22:35,748 :: INFO :: <class 'dcs.planes.MiG_19P'> destroyed from Damascus
2020-12-27 23:22:35,748 :: INFO :: <class 'dcs.planes.MiG_19P'> destroyed from Damascus
2020-12-27 23:22:35,748 :: INFO :: <class 'dcs.planes.MiG_19P'> destroyed from Damascus
2020-12-27 23:22:35,749 :: INFO :: <class 'dcs.planes.MiG_19P'> destroyed from Damascus
2020-12-27 23:22:35,749 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Damascus
2020-12-27 23:22:35,749 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Damascus
2020-12-27 23:22:35,750 :: ERROR :: Found killed <class 'dcs.planes.MiG_23MLD'> from Damascus but that airbase has none available.
Traceback (most recent call last):
  File "qt_ui\windows\QWaitingForMissionResultWindow.py", line 190, in process_debriefing
  File "game\game.py", line 217, in finish_event
  File "game\event\event.py", line 175, in commit
  File "game\event\event.py", line 153, in commit_ground_object_losses
ValueError: list.remove(x): x not in list

**To Reproduce**
Click Accept Results.

**Expected behavior**
I expected the mission to end.

**Additional information**

[Can't Accept Results.zip](https://github.com/Khopa/dcs_liberation/files/5744546/Can.t.Accept.Results.zip)

**Version information (please complete the following information):**
 - DCS Liberation #909

**Comment by DanAlbert** [comment]
Save is too old to load even on 2.4 (and state.json was useless in 2.3), but this is probably the same as https://github.com/Khopa/dcs_liberation/issues/833
