### ISSUE TITLE
Editing an existing flight in a package fails

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#744]
**Describe the bug**
In #996, editing a flight in a package generates this error.
[23:49]
QLayout: Attempting to add QLayout "" to QLoadoutEditor "", which already has a layout
Traceback (most recent call last):
  File "qt_ui\widgets\ato.py", line 213, in <lambda>
  File "qt_ui\widgets\ato.py", line 196, in edit_flight
  File "qt_ui\dialogs.py", line 61, in open_edit_flight_dialog
  File "qt_ui\windows\mission\QEditFlightDialog.py", line 28, in init
  File "qt_ui\windows\mission\flight\QFlightPlanner.py", line 28, in init
  File "qt_ui\windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in init
  File "qt_ui\windows\mission\flight\payload\QLoadoutEditor.py", line 34, in init
  File "qt_ui\windows\mission\flight\payload\QPylonEditor.py", line 33, in init
  File "qt_ui\windows\mission\flight\payload\QPylonEditor.py", line 52, in default_loadout
UnboundLocalError: local variable 'loadout' referenced before assignment

**To Reproduce**
1. Create flight in package.
2. Attemptt to edit flight in package

**Comment by Malakhit** [comment]
Should now be fixed - thanks!
