### ISSUE TITLE
Error on Accept Results. Appears related to base capture. (#1020)

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#756]
**Describe the bug**
Got this error on clicking "Accept Results" after a turn that involved a capture event.

[17:09]
2021-01-11 17:07:11,516 :: INFO :: Finishing event AirWar
2021-01-11 17:07:11,517 :: INFO :: Committing mission results
2021-01-11 17:07:11,517 :: INFO :: <class 'dcs.planes.FA_18C_hornet'> destroyed from Nellis AFB
2021-01-11 17:07:11,518 :: ERROR :: Found killed <class 'dcs.planes.MiG_21Bis'> from Tonopah Test but that airbase has none available.
2021-01-11 17:07:11,518 :: ERROR :: Found killed <class 'dcs.planes.MiG_21Bis'> from Tonopah Test but that airbase has none available.
2021-01-11 17:07:11,518 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Tonopah Airport
2021-01-11 17:07:11,519 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Tonopah Airport
2021-01-11 17:07:11,519 :: ERROR :: Found killed <class 'dcs.helicopters.Mi_8MT'> from Tonopah Test but that airbase has none available.
2021-01-11 17:07:11,520 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Tonopah Airport
2021-01-11 17:07:11,520 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Tonopah Airport
[17:09]
2021-01-11 17:07:11,519 :: ERROR :: Found killed <class 'dcs.helicopters.Mi_8MT'> from Tonopah Test but that airbase has none available.
2021-01-11 17:07:11,520 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Tonopah Airport
2021-01-11 17:07:11,520 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Tonopah Airport
2021-01-11 17:07:11,520 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.MBT_M1A2_Abrams'> from Groom Lake but that airbase has none available.
2021-01-11 17:07:11,521 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.MBT_M1A2_Abrams'> from Groom Lake but that airbase has none available.
2021-01-11 17:07:11,521 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.MBT_T_55'> from Tonopah Test but that airbase has none available.
2021-01-11 17:07:11,522 :: ERROR :: Found killed <class 'dcs.vehicles.Artillery.SPH_2S9_Nona'> from Tonopah Test but that airbase has none available.
2021-01-11 17:07:11,522 :: ERROR :: Found killed <class 'dcs.vehicles.Artillery.SPH_2S9_Nona'> from Tonopah Test but that airbase has none available.
2021-01-11 17:07:11,523 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.MBT_T_55'> from Tonopah Test but that airbase has none available.
Traceback (most recent call last):
  File "qt_ui\windows\QWaitingForMissionResultWindow.py", line 190, in process_debriefing
  File "game\game.py", line 213, in finish_event
  File "game\event\event.py", line 168, in commit
  File "game\event\event.py", line 146, in commit_ground_object_losses
ValueError: list.remove(x): x not in list

**Comment by DanAlbert** [comment]
Given the number of things that were not recognized it looks like the state of the game was already corrupted when the results were accepted. I'm guessing that you clicked accept the first time, it processed some of the results, then encountered an error *different* from the one above. Subsequent clicks would then try to process against a broken game state and result in this error message.

I can't be sure about any of that, but I also don't know what we can do to fix this without either the complete log, or preferably the save game and the state.json that caused it.
