### ISSUE TITLE
BARCAP from carrier to only blue airfield fails to generate WPs.

### ISSUE THREAD

**Issue by MaHuJa** [dcs-liberation/dcs_liberation#790]
**Describe the bug**
With a carrier and one airfield (also LHA in the area), tasking BARCAP from the carrier onto that airfield, waypoint generation fails.

```
Traceback (most recent call last):
  File "E:\dcs_liberation_dev\src\qt_ui\windows\mission\QPackageDialog.py", line 172, in add_flight
    planner.populate_flight_plan(flight)
  File "E:\dcs_liberation_dev\src\gen\flights\flightplan.py", line 762, in populate_flight_plan
    self.regenerate_package_waypoints()
  File "E:\dcs_liberation_dev\src\gen\flights\flightplan.py", line 834, in regenerate_package_waypoints
    join_point = self.preferred_join_point()
  File "E:\dcs_liberation_dev\src\gen\flights\flightplan.py", line 880, in preferred_join_point
    self.package_airfield().position, self.package.target.position)
  File "E:\dcs_liberation_dev\src\gen\flights\flightplan.py", line 1524, in package_airfield
    raise RuntimeError(
RuntimeError: Could not find any airfield assigned to this package
2021-01-22 00:31:39,293 :: WARNING :: Cannot estimate TOT for [BARCAP] 2 x F-14B Tomcat
```

**To Reproduce**
1. Create new campaign, UAE map.
2. Buy F-14s on carrier
3. Skip turn
4. Clear packages
5. Create new package on Fujairah, add BARCAP F-14 taking off from the carrier

**Expected behavior**
Waypoints are generated, displayed on map, and until the ASAP button is pressed the takeoff time is <0.

**Additional information**

We will usually need more information for debugging. Include as much of the following as you are able:

[lib_no_wp.zip](https://github.com/Khopa/dcs_liberation/files/5852778/lib_no_wp.zip)
.liberation .log

**Version information (please complete the following information):**
 - 2.4pre, latest at time of writing.

**Additional context**
As a workaround, the BARCAP can be added to friendly ground locations nearby.

**Comment by DanAlbert** [comment]
Works for me using your save game. Maybe was fixed since the build you used.

**Comment by DanAlbert** [comment]
Or maybe not. New report in https://github.com/Khopa/dcs_liberation/issues/819
