### ISSUE TITLE
Can't generate new campaign

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#812]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
The following error occurs when clicking New Game in #1113 Preview.

Traceback (most recent call last):
  File "qt_ui\windows\QLiberationWindow.py", line 225, in newGame
  File "qt_ui\windows\newgame\QNewGameWizard.py", line 40, in __init__
  File "qt_ui\windows\newgame\QCampaignList.py", line 62, in load_campaigns
  File "qt_ui\windows\newgame\QCampaignList.py", line 37, in from_json
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 3 (char 716)

**To Reproduce**
1. Click New Game

**Version information (please complete the following information):**
 - #1113

**Comment by Starfire13** [comment]
Closing this because I'm a dumdum and missed a comma in a campaign json file.
