### ISSUE TITLE
Error upon clicking Accept Results

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#833]
**Describe the bug**
I get this error in the log when clicking accept results. Files attached below.

2021-02-02 11:17:45,406 :: INFO :: Finishing event AirWar
2021-02-02 11:17:45,407 :: INFO :: Committing mission results
2021-02-02 11:17:45,408 :: INFO :: <class 'dcs.planes.A_10C_2'> destroyed from Bassel Al-Assad
2021-02-02 11:17:45,408 :: INFO :: <class 'dcs.planes.A_10C_2'> destroyed from Bassel Al-Assad
2021-02-02 11:17:45,408 :: INFO :: <class 'dcs.planes.F_16C_50'> destroyed from Bassel Al-Assad
2021-02-02 11:17:45,409 :: INFO :: <class 'dcs.planes.F_14B'> destroyed from Bassel Al-Assad
2021-02-02 11:17:45,409 :: INFO :: <class 'dcs.planes.FA_18C_hornet'> destroyed from Bassel Al-Assad
2021-02-02 11:17:45,410 :: INFO :: <class 'dcs.planes.FA_18C_hornet'> destroyed from Bassel Al-Assad
2021-02-02 11:17:45,410 :: INFO :: <class 'dcs.planes.F_14B'> destroyed from Bassel Al-Assad
2021-02-02 11:17:45,410 :: INFO :: <class 'dcs.planes.F_16C_50'> destroyed from Bassel Al-Assad
2021-02-02 11:17:45,411 :: INFO :: <class 'dcs.planes.MiG_29S'> destroyed from Incirlik
2021-02-02 11:17:45,411 :: INFO :: <class 'dcs.planes.MiG_29S'> destroyed from Incirlik
2021-02-02 11:17:45,411 :: INFO :: <class 'dcs.planes.Su_24M'> destroyed from Incirlik
2021-02-02 11:17:45,412 :: INFO :: <class 'dcs.planes.Su_24M'> destroyed from Incirlik
2021-02-02 11:17:45,412 :: INFO :: <class 'dcs.planes.L_39ZA'> destroyed from Incirlik
2021-02-02 11:17:45,412 :: INFO :: <class 'dcs.planes.L_39ZA'> destroyed from Incirlik
2021-02-02 11:17:45,413 :: ERROR :: Found killed <class 'dcs.vehicles.Artillery.MLRS_9K57_Uragan_BM_27'> from Incirlik but that airbase has none available.
2021-02-02 11:17:45,414 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.IFV_BMP_3'> from Incirlik but that airbase has none available.
2021-02-02 11:17:45,414 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.IFV_BMP_1'> from Incirlik but that airbase has none available.
Traceback (most recent call last):
  File "qt_ui\windows\QWaitingForMissionResultWindow.py", line 190, in process_debriefing
  File "game\game.py", line 214, in finish_event
  File "game\event\event.py", line 168, in commit
  File "game\event\event.py", line 146, in commit_ground_object_losses
ValueError: list.remove(x): x not in list

**Version information (please complete the following information):**
#1127

[OPS Test 3A.zip](https://github.com/Khopa/dcs_liberation/files/5907701/OPS.Test.3A.zip)

**Comment by DanAlbert** [comment]
Usually means it crashed on the first click, you clicked again, and this is the error the second time or later.

If that's the case there's nothing we can investigate without the log of the first crash.

(Note I haven't actually had a chance to look yet, just wanted to get that said ASAP in case there's still a chance to recover the full log)

**Comment by Starfire13** [comment]
I'll replay the mission and get the full log for you.

**Comment by DanAlbert** [comment]
I think I actually got the error from the other bug you filed, so might be no need.

**Comment by DanAlbert** [comment]
(for reference since I'm not looking at this right this second: https://github.com/Khopa/dcs_liberation/issues/741)

```
  File "C:\Users\dan\src\dcs_liberation\qt_ui\windows\QWaitingForMissionResultWindow.py", line 191, in process_debriefing
    self.game.pass_turn()
  File "C:\Users\dan\src\dcs_liberation\game\game.py", line 255, in pass_turn
    self.initialize_turn()
  File "C:\Users\dan\src\dcs_liberation\game\game.py", line 292, in initialize_turn
    blue_planner.plan_missions()
  File "C:\Users\dan\src\dcs_liberation\gen\flights\ai_flight_planner.py", line 597, in plan_missions
    self.plan_mission(proposed_mission)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\ai_flight_planner.py", line 703, in plan_mission
    flight_plan_builder.populate_flight_plan(flight)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 763, in populate_flight_plan
    flight.flight_plan = self.generate_flight_plan(flight, custom_targets)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 775, in generate_flight_plan
    return self.generate_barcap(flight)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 980, in generate_barcap
    start, end = self.racetrack_for_objective(location, barcap=True)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 1053, in racetrack_for_objective
    raise PlanningError("Could not find any enemy airfields")
gen.flights.flightplan.PlanningError: Could not find any enemy airfields
```

**Comment by Starfire13** [comment]
Yes, that "Could not find any enemy airfields" line definitely occured this time too.

**Comment by Starfire13** [comment]
Could it be because I bombed the runway when redfor had only a single airbase left? So they had no functional runways at all?

**Comment by Starfire13** [comment]
Tried a fresh campaign and recieved the error below when clicking Accept Result. At this point, the other side had two airfields, but runways at both were disabled. I had disabled one airfield's runway on the previous turn, and the second airfield's runway on this turn. It appears Liberation does not like it if redfor has no usable runways left. I made VERY sure I only clicked Accept Results once this time.

2021-02-04 23:37:10,234 :: INFO :: On Debriefing update
2021-02-04 23:37:10,234 :: DEBUG :: <game.debriefing.Debriefing object at 0x00000236F204FFA0>
2021-02-04 23:38:05,253 :: DEBUG :: Death of untracked ground unit 640844045 will have no effect. This may be normal behavior.
2021-02-04 23:38:05,253 :: DEBUG :: Death of untracked ground unit 325389455 will have no effect. This may be normal behavior.
2021-02-04 23:38:05,254 :: DEBUG :: Death of untracked ground unit 325389460 will have no effect. This may be normal behavior.
2021-02-04 23:38:05,255 :: DEBUG :: Death of untracked ground unit 640844105 will have no effect. This may be normal behavior.
2021-02-04 23:38:05,255 :: DEBUG :: Death of untracked ground unit 325389413 will have no effect. This may be normal behavior.
2021-02-04 23:38:05,256 :: DEBUG :: Death of untracked ground unit 325389414 will have no effect. This may be normal behavior.
2021-02-04 23:38:05,256 :: DEBUG :: Death of untracked ground unit 325389436 will have no effect. This may be normal behavior.
2021-02-04 23:38:05,257 :: INFO :: On Debriefing update
2021-02-04 23:38:05,257 :: DEBUG :: <game.debriefing.Debriefing object at 0x00000236F204FC40>
2021-02-04 23:38:13,063 :: INFO :: Finishing event AirWar
2021-02-04 23:38:13,066 :: INFO :: Committing mission results
2021-02-04 23:38:13,075 :: INFO :: <class 'dcs.planes.FA_18C_hornet'> destroyed from Ramat David
2021-02-04 23:38:13,075 :: INFO :: <class 'dcs.planes.FA_18C_hornet'> destroyed from Ramat David
2021-02-04 23:38:13,076 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Incirlik
2021-02-04 23:38:13,076 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Incirlik
2021-02-04 23:38:13,077 :: INFO :: <class 'dcs.planes.MiG_19P'> destroyed from Incirlik
2021-02-04 23:38:13,077 :: INFO :: <class 'dcs.planes.MiG_19P'> destroyed from Incirlik
2021-02-04 23:38:13,078 :: INFO :: <class 'dcs.planes.Su_17M4'> destroyed from Incirlik
2021-02-04 23:38:13,078 :: INFO :: <class 'dcs.planes.Su_17M4'> destroyed from Incirlik
2021-02-04 23:38:13,079 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Incirlik
2021-02-04 23:38:13,079 :: INFO :: <class 'dcs.planes.MiG_21Bis'> destroyed from Incirlik
Compute frontline progression for : Damascus to Bassel Al-Assad
18
0
0
0
Damascus won !  factor > 0.5
2021-02-04 23:38:13,175 :: INFO :: finish_event: event not in the events!
2021-02-04 23:38:13,176 :: INFO :: Pass turn
2021-02-04 23:38:13,199 :: INFO :: Skip Night mission due to user settings
Traceback (most recent call last):
  File "qt_ui\windows\QWaitingForMissionResultWindow.py", line 191, in process_debriefing
  File "game\game.py", line 255, in pass_turn
  File "game\game.py", line 292, in initialize_turn
  File "gen\flights\ai_flight_planner.py", line 597, in plan_missions
  File "gen\flights\ai_flight_planner.py", line 703, in plan_mission
  File "gen\flights\flightplan.py", line 763, in populate_flight_plan
  File "gen\flights\flightplan.py", line 775, in generate_flight_plan
  File "gen\flights\flightplan.py", line 980, in generate_barcap
  File "gen\flights\flightplan.py", line 1053, in racetrack_for_objective
gen.flights.flightplan.PlanningError: Could not find any enemy airfields

**Comment by SnappyComebacks** [comment]
Also received this error recently.  Build 1259.  Happens when clicking Accept Results after capturing the last base.  Attached is a campaign, state, liberation logs, console logs and mission.

[InhererentResolve-Build_1259.zip](https://github.com/Khopa/dcs_liberation/files/6213435/InhererentResolve-Build_1259.zip)

**Comment by scribblescrabble** [comment]
I also got this error and have also attached a zip file with the campaign, state, liberation logs, console logs, and mission. I got this error when I bombed the runway on the enemy's last remaining airfield.
[Liberation Error.zip](https://github.com/Khopa/dcs_liberation/files/6214843/Liberation.Error.zip)

**Comment by DanAlbert** [comment]
Pushed a change so this state (no functioning airfields) results in a win/loss message. The crash will still happen if you try to keep playing, but that's because we don't really handle game over: https://github.com/Khopa/dcs_liberation/issues/978
