### ISSUE TITLE
KeyError: 4 when clicking Take Off

### ISSUE THREAD

**Issue by comanche001** [dcs-liberation/dcs_liberation#898]
Traceback (most recent call last):
  File "qt_ui\widgets\QTopPanel.py", line 243, in launch_mission
  File "game\game.py", line 213, in initiate_event
  File "game\event\event.py", line 58, in generate
  File "game\operation\operation.py", line 312, in generate
  File "game\operation\operation.py", line 402, in _generate_ground_conflicts
KeyError: 4

When I click Take Off I get message above. Cannot start mission....

Version 2.4.2. Save file included.
[Nevada.zip](https://github.com/Khopa/dcs_liberation/files/5998969/Nevada.zip)

**Comment by zelosos** [comment]
Got the same with key 4:
[SU25T-Time.zip](https://github.com/Khopa/dcs_liberation/files/6279899/SU25T-Time.zip)

After ending the last mission the windows was not closing when clicking accept outcome.
After restart the outcome was included.

**Comment by DanAlbert** [comment]
This is just the game over state. On turn generation:

```
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\qt_ui\widgets\QTopPanel.py", line 134, in passTurn
    self.game.pass_turn(no_action=True)
  File "C:\Users\dan\src\dcs_liberation\game\game.py", line 281, in pass_turn
    self.initialize_turn()
  File "C:\Users\dan\src\dcs_liberation\game\game.py", line 318, in initialize_turn
    blue_planner.plan_missions()
  File "C:\Users\dan\src\dcs_liberation\gen\flights\ai_flight_planner.py", line 680, in plan_missions
    self.plan_mission(proposed_mission)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\ai_flight_planner.py", line 792, in plan_mission
    flight_plan_builder.populate_flight_plan(flight)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 807, in populate_flight_plan
    flight.flight_plan = self.generate_flight_plan(flight, custom_targets)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 825, in generate_flight_plan
    return self.generate_barcap(flight)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 1074, in generate_barcap
    start, end = self.racetrack_for_objective(location, barcap=True)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 1152, in racetrack_for_objective
    raise PlanningError("Could not find any enemy airfields")
gen.flights.flightplan.PlanningError: Could not find any enemy airfields

Process finished with exit code -1
```

The enemy has no functional airfields left. You won.

The game not telling you this is https://github.com/Khopa/dcs_liberation/issues/833
