### ISSUE TITLE
Unable to estimate TOT for BAI flight

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#900]
**Describe the bug**
Error seen when attempting to set up a BAI flight on an SA-10 site. Liberation file attached.

Traceback (most recent call last):
  File "qt_ui\windows\mission\QPackageDialog.py", line 186, in add_flight
  File "gen\flights\flightplan.py", line 799, in populate_flight_plan
  File "gen\flights\flightplan.py", line 809, in generate_flight_plan
  File "gen\flights\flightplan.py", line 1018, in generate_bai
  File "gen\flights\flightplan.py", line 1544, in strike_flightplan
  File "gen\flights\flightplan.py", line 1448, in target_waypoint
  File "gen\flights\waypointbuilder.py", line 223, in bai_group
  File "gen\flights\waypointbuilder.py", line 238, in _target_point
  File "pydcs\dcs\unitgroup.py", line 72, in position
IndexError: list index out of range
2021-02-19 19:49:08,945 :: WARNING :: Cannot estimate TOT for [BAI] 4 x F-15E Strike Eagle
2021-02-19 19:49:10,647 :: WARNING :: Cannot estimate TOT for [BAI] 4 x F-15E Strike Eagle

#1201 Preview

[Black Sea Lite.zip](https://github.com/Khopa/dcs_liberation/files/6008703/Black.Sea.Lite.zip)

**Comment by Starfire13** [comment]
I have no troubles planning other missions types against this target, and also have no troubles planning BAI against other targets.

**Comment by DanAlbert** [comment]
This is because it's attempting to make a target point at each sub-group, and the PD subgroup is dead.
