### ISSUE TITLE
RuntimeError: Could not find any airfield assigned to this package

### ISSUE THREAD

**Issue by TheREALGovernor** [dcs-liberation/dcs_liberation#901]
The second time I've had this error since updating to 2.4.2 - The first time I made it through a "turn", I received "Error 4" code there was already a bug issue filed on. 

This bug showed itself when I finished my first Liberation turn after creating a new campaign. I remoted into the DCS dedicated server and clicked "Accept" on the end mission report after changing maps on the dedicated server, as I always do, and that's when this error showed itself.

Here are the last few lines of the command prompt leading up to the error:
```
Compute frontline progression for : Sochi-Adler to FOB Sochi
21
13
14
8
Sochi-Adler lost !  factor > 0.5
2021-02-18 20:01:50,572 :: INFO :: finish_event: event not in the events!
2021-02-18 20:01:50,572 :: INFO :: Pass turn
Traceback (most recent call last):
  File "qt_ui\windows\QWaitingForMissionResultWindow.py", line 191, in process_debriefing
  File "game\game.py", line 258, in pass_turn
  File "game\game.py", line 298, in initialize_turn
  File "gen\flights\ai_flight_planner.py", line 597, in plan_missions
  File "gen\flights\ai_flight_planner.py", line 703, in plan_mission
  File "gen\flights\flightplan.py", line 762, in populate_flight_plan
  File "gen\flights\flightplan.py", line 834, in regenerate_package_waypoints
  File "gen\flights\flightplan.py", line 880, in preferred_join_point
  File "gen\flights\flightplan.py", line 1524, in package_airfield
RuntimeError: Could not find any airfield assigned to this package
```

From there, it would not do anything else or let me end the round or progress.

I ended up closing the command prompt (forcing Liberation to exit), then moved the entire Liberation install into a ZIP file (also included the save file scenario). I am re-downloading and reinstalling Liberation from scratch with a new campaign and will see how this one progresses...
[State.JSON&.LiberationFile.zip](https://github.com/Khopa/dcs_liberation/files/6013571/State.JSON.LiberationFile.zip)

**Comment by TheREALGovernor** [comment]
Additional information:

This appears to happen when we create an anti-ship mission to blow up the enemy carrier group. We successfully destroy the carrier group, but aircraft remain in that spot on the map after the carrier sinks. 
Try to end the round and "accept results", but get this error in the command prompt. 
![Error Screenshot](https://user-images.githubusercontent.com/39065747/108581012-ca34a800-72f3-11eb-9c37-05ac60ff8a3c.png)


Appears to be 100% reproducible on this end.

**Comment by DanAlbert** [comment]
I get a different error:

```
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\qt_ui\widgets\QTopPanel.py", line 243, in launch_mission
    unit_map = self.game.initiate_event(game_event)
  File "C:\Users\dan\src\dcs_liberation\game\game.py", line 213, in initiate_event
    return event.generate()
  File "C:\Users\dan\src\dcs_liberation\game\event\event.py", line 58, in generate
    unit_map = Operation.generate()
  File "C:\Users\dan\src\dcs_liberation\game\operation\operation.py", line 312, in generate
    cls._generate_ground_conflicts()
  File "C:\Users\dan\src\dcs_liberation\game\operation\operation.py", line 402, in _generate_ground_conflicts
    player_gp = cls.game.ground_planners[player_cp.id].units_per_cp[enemy_cp.id]
KeyError: 18
```

This is before I can generate the mission to use the state.json, so the save file is already broken. Most likely something went wrong when processing the results of the previous turn, but without having that save there's nothing we can investigate. Having the full log probably would have helped (usually there's an earlier log message that notes the save corruption; without that information we can't do anything).
