### ISSUE TITLE
Unable to end turn due to navmesh error

### ISSUE THREAD

**Issue by Starfire13** [dcs-liberation/dcs_liberation#903]
**Describe the bug**

```
2021-02-20 11:58:05,788 :: INFO :: Finishing event AirWar
2021-02-20 11:58:05,789 :: INFO :: Committing mission results
2021-02-20 11:58:05,789 :: INFO :: <class 'dcs.planes.FA_18C_hornet'> destroyed from CVN-75 Harry S. Truman
2021-02-20 11:58:05,790 :: INFO :: <class 'dcs.planes.FA_18C_hornet'> destroyed from CVN-75 Harry S. Truman
2021-02-20 11:58:05,791 :: INFO :: <class 'dcs.planes.AV8BNA'> destroyed from LHA-5 Peleliu
2021-02-20 11:58:05,791 :: INFO :: <class 'dcs.planes.AV8BNA'> destroyed from LHA-5 Peleliu
2021-02-20 11:58:05,792 :: INFO :: <class 'dcs.planes.AV8BNA'> destroyed from LHA-5 Peleliu
2021-02-20 11:58:05,793 :: INFO :: <class 'dcs.planes.F_14B'> destroyed from CVN-75 Harry S. Truman
2021-02-20 11:58:05,793 :: INFO :: <class 'dcs.planes.Su_33'> destroyed from Admiral Gorshkov
2021-02-20 11:58:05,793 :: INFO :: <class 'dcs.planes.Su_33'> destroyed from Admiral Gorshkov
2021-02-20 11:58:05,794 :: INFO :: <class 'dcs.planes.MiG_25PD'> destroyed from Anapa-Vityazevo
2021-02-20 11:58:05,795 :: INFO :: <class 'dcs.vehicles.Armor.IFV_BMP_2'> destroyed from FOB Gelendzhik
2021-02-20 11:58:05,796 :: INFO :: <class 'dcs.vehicles.Armor.APC_BTR_80'> destroyed from FOB Gelendzhik
2021-02-20 11:58:05,797 :: INFO :: <class 'dcs.vehicles.Armor.APC_BTR_80'> destroyed from FOB Gelendzhik
2021-02-20 11:58:05,797 :: INFO :: <class 'dcs.vehicles.Armor.MBT_T_72B'> destroyed from FOB Gelendzhik
2021-02-20 11:58:05,798 :: INFO :: <class 'dcs.vehicles.AirDefence.SAM_SA_13_Strela_10M3_9A35M3'> destroyed from FOB Gelendzhik
2021-02-20 11:58:05,800 :: INFO :: Refunding 1 BMP-2 at FOB Gelendzhik
2021-02-20 11:58:05,801 :: INFO :: Refunding 1 BTR-80 at FOB Gelendzhik
2021-02-20 11:58:05,802 :: WARNING :: No campaign location for EWR Mat FOB Gelendzhik
2021-02-20 11:58:05,803 :: DEBUG :: No mizdata location for EWR at FOB Gelendzhik
2021-02-20 11:58:05,803 :: WARNING :: Falling back to random location for EWR at FOB Gelendzhik
2021-02-20 11:58:05,815 :: INFO :: Will run redeploy for FOB Gelendzhik
2021-02-20 11:58:05,817 :: INFO :: 20  units have been redeployed from Sochi-Adler to FOB Gelendzhik
Compute frontline progression for : FOB Gelendzhik to Anapa-Vityazevo
20
0
5
0
FOB Gelendzhik won !  factor > 0.5
2021-02-20 11:58:05,861 :: INFO :: finish_event: event not in the events!
2021-02-20 11:58:05,862 :: INFO :: Pass turn
2021-02-20 11:58:05,864 :: INFO :: Skip Night mission due to user settings
2021-02-20 11:58:06,011 :: INFO :: Insufficient aircraft: Not enough aircraft in range for Admiral Gorshkov capable of: AEWC
Traceback (most recent call last):
  File "qt_ui\windows\QWaitingForMissionResultWindow.py", line 193, in process_debriefing
  File "game\game.py", line 280, in pass_turn
  File "game\game.py", line 320, in initialize_turn
  File "gen\flights\ai_flight_planner.py", line 680, in plan_missions
  File "gen\flights\ai_flight_planner.py", line 792, in plan_mission
  File "gen\flights\flightplan.py", line 799, in populate_flight_plan
  File "gen\flights\flightplan.py", line 811, in generate_flight_plan
  File "gen\flights\flightplan.py", line 1076, in generate_barcap
  File "gen\flights\waypointbuilder.py", line 461, in nav_path
  File "game\navmesh.py", line 146, in shortest_path
ValueError: Origin point Point(84992.70853733181, 118623.15554918301) is outside the navmesh
```

[Files.zip](https://github.com/Khopa/dcs_liberation/files/6013845/Files.zip)

**Comment by DanAlbert** [comment]
This happens when the BARCAP target (in this case Anapa) is near the edge of the conflict and also has a threat near enough that it retreats beyond the navigable area: 
![image](https://user-images.githubusercontent.com/315852/111044982-8f102b00-8400-11eb-8600-da4311bb8ddd.png)

I doubled the size of the navigable area. The tradeoff is that any flights that might have previously routed _around_ a threat near the edge of the map may no longer do so as the zones at the edge are significantly larger now.
