### ISSUE TITLE
In GUI, unable to edit flights for Community A-4E Skyhawk

### ISSUE THREAD

**Issue by docsconz** [dcs-liberation/dcs_liberation#939]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
In Mission Package dialog, double click or right-click edit on flights of A-4E do not open the flight/waypoint/payload editing dialog.

**To Reproduce**
1. Create package that includes a flight of A-4E
2. Double click on package to open Mission Package dialog
3. Double click on A-4E flight (should open flight editing dialog

**Expected behavior**
The flight/waypoint/payload editing dialog should open.

**Additional information**
Error:
Traceback (most recent call last):
  File "qt_ui\widgets\ato.py", line 218, in <lambda>
  File "qt_ui\widgets\ato.py", line 201, in edit_flight
  File "qt_ui\dialogs.py", line 57, in open_edit_flight_dialog
  File "qt_ui\windows\mission\QEditFlightDialog.py", line 33, in __init__
  File "qt_ui\windows\mission\flight\QFlightPlanner.py", line 20, in __init__
  File "qt_ui\windows\mission\flight\payload\QFlightPayloadTab.py", line 13, in __init__
  File "qt_ui\windows\mission\flight\payload\QLoadoutEditor.py", line 40, in __init__
  File "qt_ui\windows\mission\flight\payload\QPylonEditor.py", line 67, in default_loadout
AttributeError: 'NoneType' object has no attribute 'available_on'

**Version information (please complete the following information):**
 - DCS Liberation 2.4.3

**Additional context**
attached liberation save file as txt file
[a-4 liberation golan 1973.liberation.txt](https://github.com/Khopa/dcs_liberation/files/6094044/a-4.liberation.golan.1973.liberation.txt)

**Comment by HighwaymanEd** [comment]
Seeing the same thing here looking to start an Israeli 1973 Yom Kippur scenario.

**Comment by Mustang-25** [comment]
Tested and the edit flight option works on the latest build for the A-4. Closing this report.
