### ISSUE TITLE
Unable to complete mission

### ISSUE THREAD

**Issue by alexkrebiehl** [dcs-liberation/dcs_liberation#979]
Before filing, please search the issue tracker to see if the issue has already been reported.

**Describe the bug**
After completing the mission, the "Accept Results" button does nothing. In this instance, the state file was manually submitted, as DCS Liberation did not detect the end of the mission.

**Expected behavior**
The mission to be accepted and to move on to the next turn.

**Additional information**

Logs:

```
2021-04-11 10:33:41,567 :: INFO :: Finishing event AirWar
2021-04-11 10:33:41,567 :: INFO :: Committing mission results
2021-04-11 10:33:41,568 :: ERROR :: Found killed <class 'dcs.planes.F_16C_50'> from Ramat David but that airbase has none available.
2021-04-11 10:33:41,568 :: ERROR :: Found killed <class 'dcs.planes.Su_17M4'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,568 :: ERROR :: Found killed <class 'dcs.planes.F_15C'> from Ramat David but that airbase has none available.
2021-04-11 10:33:41,568 :: ERROR :: Found killed <class 'dcs.planes.Su_24M'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,568 :: ERROR :: Found killed <class 'dcs.planes.Su_24M'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,568 :: ERROR :: Found killed <class 'dcs.planes.F_15C'> from Ramat David but that airbase has none available.
2021-04-11 10:33:41,569 :: ERROR :: Found killed <class 'dcs.planes.F_16C_50'> from Ramat David but that airbase has none available.
2021-04-11 10:33:41,569 :: ERROR :: Found killed <class 'dcs.planes.F_15C'> from Ramat David but that airbase has none available.
2021-04-11 10:33:41,569 :: ERROR :: Found killed <class 'dcs.planes.MiG_29S'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,569 :: ERROR :: Found killed <class 'dcs.planes.A_10C_2'> from Ramat David but that airbase has none available.
2021-04-11 10:33:41,569 :: ERROR :: Found killed <class 'dcs.planes.MiG_29S'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,569 :: ERROR :: Found killed <class 'dcs.planes.Su_17M4'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,569 :: ERROR :: Found killed <class 'dcs.planes.F_15C'> from Ramat David but that airbase has none available.
2021-04-11 10:33:41,570 :: ERROR :: Found killed <class 'dcs.planes.Su_17M4'> from Damascus but that airbase has none available.
2021-04-11 10:33:41,570 :: ERROR :: Found killed <class 'dcs.planes.Su_17M4'> from Damascus but that airbase has none available.
2021-04-11 10:33:41,570 :: ERROR :: Found killed <class 'dcs.planes.MiG_21Bis'> from Damascus but that airbase has none available.
2021-04-11 10:33:41,570 :: ERROR :: Found killed <class 'dcs.planes.MiG_29S'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,570 :: ERROR :: Found killed <class 'dcs.planes.MiG_29S'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,570 :: ERROR :: Found killed <class 'dcs.planes.Su_24M'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,570 :: ERROR :: Found killed <class 'dcs.planes.Su_17M4'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,570 :: ERROR :: Found killed <class 'dcs.planes.Su_17M4'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,571 :: ERROR :: Found killed <class 'dcs.planes.L_39ZA'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,571 :: ERROR :: Found killed <class 'dcs.planes.L_39ZA'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,571 :: ERROR :: Found killed <class 'dcs.planes.MiG_25PD'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,571 :: ERROR :: Found killed <class 'dcs.planes.MiG_25PD'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,571 :: ERROR :: Found killed <class 'dcs.planes.Su_24M'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,572 :: ERROR :: Found killed <class 'dcs.planes.Su_24M'> from King Hussein Air College but that airbase has none available.
2021-04-11 10:33:41,572 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.MBT_M1A2_Abrams'> from Golan North but that airbase has none available.
2021-04-11 10:33:41,572 :: ERROR :: Found killed <class 'dcs.vehicles.Artillery.SPH_2S9_Nona'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,572 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.MBT_M1A2_Abrams'> from Golan North but that airbase has none available.
2021-04-11 10:33:41,572 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.APC_Cobra'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,572 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.APC_MTLB'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,572 :: ERROR :: Found killed <class 'dcs.vehicles.Artillery.SPH_M109_Paladin'> from Golan North but that airbase has none available.
2021-04-11 10:33:41,573 :: ERROR :: Found killed <class 'dcs.vehicles.AirDefence.SAM_Avenger_M1097'> from Golan North but that airbase has none available.
2021-04-11 10:33:41,573 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.MBT_Merkava_Mk__4'> from Golan North but that airbase has none available.
2021-04-11 10:33:41,573 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.MBT_T_90'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,573 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.APC_M1043_HMMWV_Armament'> from Golan North but that airbase has none available.
2021-04-11 10:33:41,573 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.APC_Cobra'> from Marj Ruhayyil but that airbase has none available.
2021-04-11 10:33:41,573 :: ERROR :: Found killed <class 'dcs.vehicles.Armor.MBT_M1A2_Abrams'> from Golan North but that airbase has none available.
2021-04-11 10:33:41,573 :: ERROR :: Found killed <class 'dcs.vehicles.Artillery.SPH_M109_Paladin'> from Golan North but that airbase has none available.
Traceback (most recent call last):
  File "qt_ui\windows\QWaitingForMissionResultWindow.py", line 192, in process_debriefing
  File "game\game.py", line 233, in finish_event
  File "game\event\event.py", line 189, in commit
  File "game\event\event.py", line 164, in commit_ground_object_losses
ValueError: list.remove(x): x not in list
```
[liberation bug report.zip](https://github.com/Khopa/dcs_liberation/files/6292027/liberation.bug.report.zip)

**Version information (please complete the following information):**
 - DCS Liberation 2.4.3

**Comment by DanAlbert** [comment]
The actual crash (the log you pasted is the result of trying again after the first one):

```
Traceback (most recent call last):
  File "C:\Users\dan\src\dcs_liberation\qt_ui\windows\QWaitingForMissionResultWindow.py", line 193, in process_debriefing
    self.game.pass_turn()
  File "C:\Users\dan\src\dcs_liberation\game\game.py", line 280, in pass_turn
    self.initialize_turn()
  File "C:\Users\dan\src\dcs_liberation\game\game.py", line 320, in initialize_turn
    red_planner.plan_missions()
  File "C:\Users\dan\src\dcs_liberation\gen\flights\ai_flight_planner.py", line 656, in plan_missions
    self.plan_mission(proposed_mission)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\ai_flight_planner.py", line 768, in plan_mission
    flight_plan_builder.populate_flight_plan(flight)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 762, in populate_flight_plan
    flight.flight_plan = self.generate_flight_plan(flight, custom_targets)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 774, in generate_flight_plan
    return self.generate_barcap(flight)
  File "C:\Users\dan\src\dcs_liberation\gen\flights\flightplan.py", line 996, in generate_barcap
    nav_to=builder.nav_path(
  File "C:\Users\dan\src\dcs_liberation\gen\flights\waypointbuilder.py", line 436, in nav_path
    path = self.clean_nav_points(self.navmesh.shortest_path(a, b))
  File "C:\Users\dan\src\dcs_liberation\game\navmesh.py", line 146, in shortest_path
    raise ValueError(f"Origin point {destination} is outside the navmesh")
ValueError: Origin point Point(-20832.544450903253, 182386.5645768782) is outside the navmesh
```

https://github.com/Khopa/dcs_liberation/issues/903
